### ISSUE TITLE
Blank query parameters are rewrited

### ISSUE THREAD

**Issue by darkleaf** [mock-server/mockserver#1005]
**Describe the issue**
Mockserver rewrites query parameters. It's run in proxy mode.

When I send a request like `http://my-app.com/page?parameter`, my app gets `http://my-app.com/page?parameter=`.
 
**MockServer version**
5.11.2

**To Reproduce**

1. start mockserver as a proxy
2. `curl http://my-app.com/page?parameter`
3. watch app logs

**Expected behaviour**

App logs contain the original request.

**Comment by jamesdbloom** [comment]
This is now fixed in the latest SNAPSHOT version which will be released in the next week.
