### ISSUE TITLE
Vulnerability found in dependency velocity-engine-core

### ISSUE THREAD

**Issue by deporcali** [mock-server/mockserver#1006]
This project uses dependency `org.apache.velocity:velocity-engine-core` with version `2.0` which has a vulnerability for Arbitrary Code Execution. It is recommended to update the dependency to version `2.3` or higher

See https://snyk.io/vuln/SNYK-JAVA-ORGAPACHEVELOCITY-1083992 for more info 

https://github.com/mock-server/mockserver/blob/d26bf2af3015f33223ebf1fdff50657e4aedeb27/pom.xml#L60

**Comment by jamesdbloom** [comment]
This has now been upgraded
