### ISSUE TITLE
Watch file modification not triggering re-read

### ISSUE THREAD

**Issue by thenom** [mock-server/mockserver#1017]
**Describe the issue**
Replacing the contents of the initialisation file is not triggering the read of the contents and in turn new\removal of expectations.

Function described here:
https://www.mock-server.com/mock_server/initializing_expectations.html#expectation_initializer_json

> Expectation Initializer JSON File Watcher
> If a JSON expectation initializer is specified a file watcher can be enabled that watches for changes in the expectation initializer and updates the expectations when the file is modified.
> 
> If enabled the initialization json file will be watched for changes, any changes found will result in expectations being created, remove or updated by matching against their key.

**What you are trying to do**
Modify the expectations that are running on a multi-container deployment via the initialisation file on a mounted AWS EFS volume.

**MockServer version**
5.11.2

**To Reproduce**
Deploy 1+ ECS tasks all with the same EFS mount with this config:

MOCKSERVER_INITIALIZATION_JSON_PATH=/config/mockserverInitialization.json
MOCKSERVER_LIVENESS_HTTP_GET_PATH=/health
MOCKSERVER_PERSIST_EXPECTATIONS=true
MOCKSERVER_PERSISTED_EXPECTATIONS_PATH=/config/mockserverInitialization.json
MOCKSERVER_WATCH_INITIALIZATION_JSON=true

Change the contents of mockserverInitialization.json via an external client (i.e. mounted on an EC2 instance) while maintaining the permissions and owner:

```
sudo chown 65532:65532 ./efs/newMockserverInitialization.json && sudo chmod 644 ./efs/newMockserverInitialization.json")
cat ./efs/newMockserverInitialization.json > ./efs/mockserverInitialization.json"
```

Monitor the expectations via the dashboard through an LB (no stickiness so refreshing hits different container).

No change occurs and all containers still report (this is at least 15mins after the file was changed):
```
Log Messages (most recent at the top)
04-13 13:59:52.078 SERVER_CONFIGURATION   	started on port: 1080
04-13 13:59:51.773 SERVER_CONFIGURATION   	loading JSON initialization file:	"/config/mockserverInitialization.json"
04-13 13:59:51.773 INFO                   	created expectation file watcher for	"/config/mockserverInitialization.json"
04-13 13:59:51.743 INFO                   	created expectation file system persistence for
```

If you replace any of the tasks they launch correctly and read the initialisation file without issue.  My current work around is to trigger a full relaunch of all tasks in the ECS service so they all get replaced and re-read the file.

**Expected behaviour**
The new expectations to show on all containers once the file has be written

**MockServer Log**
As above for already running containers but on a new task (replaced after the initialisation file was updated):
```
Log Messages (most recent at the top)
04-13 14:23:41.416 SERVER_CONFIGURATION   	started on port: 1080
04-13 14:23:41.199 CREATED_EXPECTATION    	creating expectation:	
{...}
with id:	"a167408b-02c3-4e84-bfb6-0de8e150293c"
04-13 14:23:41.123 CREATED_EXPECTATION    	creating expectation:	
{...}
with id:	"992cbadd-299e-4b34-874f-b32f53a5ee7a"
04-13 14:23:38.233 SERVER_CONFIGURATION   	loading JSON initialization file:	"/config/mockserverInitialization.json"
04-13 14:23:38.233 INFO                   	created expectation file watcher for	"/config/mockserverInitialization.json"
04-13 14:23:38.217 INFO                   	created expectation file system persistence for
```

**Comment by thenom** [comment]
Running in additional expectations after replacing 1+ of the tasks still does not show on any of the containers, both original and previously replaced.  I still have to replace the tasks after modifying the file to get them to read it in.

**Comment by jamesdbloom** [comment]
The file watcher has been rewritten due to JDK flakiness in the so please test the latest SNAPSHOT version which will be released in a few weeks.

Can you confirm that there is no file caching in your environment but separately confirming the files have actually been changed?

**Comment by thenom** [comment]
Thanks @jamesdbloom.  There is no filecaching and i can see the changed files on the volume after the update has been done.

**Comment by jamesdbloom** [comment]
The FileWatcher has been re-written due to bugs in the JDK so this should be working correctly now.
