### ISSUE TITLE
HTTPS installation of mockserver

### ISSUE THREAD

**Issue by apolegoshko** [mock-server/mockserver#1019]
Hey there! Thanks for providing good quality product. 

Due lack of documentation regarding setting up mock server with proxy server in HTTPS mode, we have to improve documentation and provide full examples of how to setup mockserver with HTTPS.

Please correct me if I'm wrong, as far as I understand from documentation HTTPS setup of mockserver can work in 4 modes:
- Dynamic Inbound Certificate Authority X.509 & Private Key - certs are generated on a fly (this method is not trusted nearly by all browsers and custom programs)
- Static Inbound Certificate Authority X.509 & Private Key
- Dynamic Inbound Private Key & X.509 (also is not working with browsers and apps)
- Static Inbound Private Key & X.509 (simple server certificate and private key)

As Dynamic cert generations is not working properly in general, we have to stick to 2 static options with Static CA + Key or Static server cert + Key.

I was able to try both of them but the behaviour is different depending on app / stack / etc.

This was tested in Debian 10 with OpenJDK 11 installed from apt.

### **Case 1 (with Static Inbound Certificate Authority X.509 & Private Key)**

_CA Cert generation_

Root Key (openssl by default generate Private Key in PKCS#1 format)

```sh
openssl genrsa -des3 -out rootCA.key 4096
```

Create and self sign the Root Certificate

```sh
openssl req -x509 -new -nodes -key rootCA.key -sha512 -days 1024 -out rootCA.crt
```

Converting rootCA.key to pksc8 format

```sh
openssl pkcs8 -topk8 -inform PEM -in rootCA.key -out private_key_PKCS_8.pem -nocrypt
```

Start of mockserver

```sh
java -Dmockserver.certificateAuthorityCertificate="rootCA.crt" -Dmockserver.certificateAuthorityPrivateKey="private_key_PKCS_8.pem" -jar mockserver.jar -serverPort 1080
```

After Import self signed ca certificate into system using command below system util `curl` starts working and requests via curl are coming to mockserver a correctly proxied to original resources with SSL setup. 

```sh
dpkg-reconfigure ca-certs
```

But in case of golang app (in my case), f.e. I'm getting bad certificate in logs of mock server, while ca cert is imported into system widely and curl is working correctly with self signed cert.  

### **Case 2 (Static Inbound Private Key & X.509 (simple server certificate and private key)**

Generating simple self signed cert and key (openssl by default generate Private Key in PKCS#1 format).

```sh
openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout selfsigned.key -out selfsigned.crt
```

Converting key to pkcs8 format

```sh
openssl pkcs8 -topk8 -inform PEM -in selfsigned.key -out private_key_PKCS_8.pem -nocrypt
```

Start of mockserver

```sh
java -Dmockserver.x509CertificatePath="selfsigned.crt" -Dmockserver.privateKeyPath ="private_key_PKCS_8.pem"  
 -jar mockserver.jar -serverPort 1080
```

In this case neither simple curl, nor app is working. And we're getting the error right in this issue #889 

Thanks in advance. Feel free to reach me out, if you have any questions. 

Also, there is smth wrong in [documentation](https://www.mock-server.com/mock_server/HTTPS_TLS.html).

In examples we see, that variables is set to `true`, while description of variable is related to location of the custom files.

Example:
-Dmockserver.certificateAuthorityPrivateKey="true"

Example:
-Dmockserver.certificateAuthorityCertificate="true"

**Comment by banzade** [comment]
Hi @apolegoshko, Did you get this sorted? I am unable to create a custom mock-server that uses custom p12 keystore and trust-stores. I need the mock-server to use the same keys, that my real client-server uses, so that when I assert few things say in tests, they match, my software uses SSLContext for setting the keystores, I can use the dynamically created certs from mock-server and feed it to my implementation but I get issues with cert chain and invalid certificates, an instruction for how set up custom tls for mock-server would be really great, if it doesnt exists yet.
CC @jamesdbloom
