### ISSUE TITLE
MockServer fails to process/use OpenApi-Spec because  $ref is not resolved correctly.

### ISSUE THREAD

**Issue by hummelfe94** [mock-server/mockserver#1020]
**Describe the issue**
MockServer fails to load OpenAPI spec because it can't resolve $ref to  array type in openApi-Spec.

**What you are trying to do**
Create mockserver and do some verification as describe in https://mock-server.com/mock_server/verification.html ("verify requests received at exactly once by openapi and operation")

**MockServer version**
testImplementation group: 'org.mock-server', name: 'mockserver-junit-jupiter', version: '5.11.2'
testImplementation group: 'com.github.java-json-tools', name: 'json-schema-validator', version: '2.0.4'

**To Reproduce**
Steps to reproduce the issue:

1. Create JUNIT-Test with @ExtendWith({ MockServerExtension.class}), MockServerSettings(ports = 1080)
2. Create MockServerClient with OpenAPI File content provided below
3. java.lang.IllegalArgumentException: Unable to load API spec, Unable to load RELATIVE ref: emsp2.2cdrs_cdr_token

**Expected behaviour**
The openApi file is loaded without any errors. 

**MockServer Log**
![image](https://user-images.githubusercontent.com/45589473/115188843-0d817c00-a0d5-11eb-97a7-2a894df51b93.png)

Problem is that the array reference is not resolved correctly:
![image](https://user-images.githubusercontent.com/45589473/115189832-abc21180-a0d6-11eb-8eb1-b89d1f00bd72.png)

**Excerpt of my openApi-File is below in the .zip file **

**Comment by hummelfe94** [comment]
[openapi-spec-ocpi-v2.2.zip](https://github.com/mock-server/mockserver/files/6333691/openapi-spec-ocpi-v2.2.zip)

**Comment by TheCycoONE** [comment]
This also happens with Twilio's OpenAPI spec:
https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_api_v2010.json

`Unable to load API spec, Unable to load RELATIVE ref: api.v2010.account.available_phone_number_country.available_phone_number_local_capabilities*`

**Comment by jamesdbloom** [comment]
This has now been fixed in the SNAPSHOT version which will be released in the next couple of weeks so closing here.
