### ISSUE TITLE
MockServer not lunching on Windows.

### ISSUE THREAD

**Issue by alexbalak21** [mock-server/mockserver#1021]
Hello,

I am using node js to run MockServer.
I have copied the code form the site.
The server do not start on windows 10.  It just counts and displays:
...
waiting for MockServer to start retries remaining: 1
MockServer failed to start

I tried it on Ubuntu, It works fine !
I can't seem to find the problem.

Can you help me please ?
Thank you

**Comment by jamesdbloom** [comment]
Can you please try again with verbose or trace enabled so I can see the log output.

**Comment by bibiKrom** [comment]
I have the same issue. 
this is the message that i am getting on windows:
java.lang.AssertionError: Further request(s) expected leaving 1 unsatisfied expectation(s).
0 request(s) executed.
