### ISSUE TITLE
Mockserver returns JSON response with iso-8859-1 encoding as default

### ISSUE THREAD

**Issue by northernbird** [mock-server/mockserver#1032]
**Describe the issue**
If we set mockserver expectation with response header `Content-Type: application/json` (without specifying encoding), the response encoding is `iso-8859-1` but it should be `utf-8` (according to  [https://tools.ietf.org/html/rfc4627#section-3](https://tools.ietf.org/html/rfc4627#section-3))

You can fix here to use `utf-8` (or doing different way for json default encoding) :
https://github.com/mock-server/mockserver/blob/33ce88631b4e3d09b499caccfe1f7897f9fc8f18/mockserver-core/src/main/java/org/mockserver/model/MediaType.java#L233-L239

**What you are trying to do**
JSON response should be encoded with UTF-8 regardless if "charset=UTF-8" specified or not, according to https://tools.ietf.org/html/rfc4627#section-3.

**MockServer version**
5.11.2, 5.11.1

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc)
Java code for API integration test
2. Code you used to create expectations
Example
```java
@Test
  public void mockServerTest() {

    final int mockServerPort = SocketUtils.findAvailableTcpPort();
    ClientAndServer mockServer = new ClientAndServer(mockServerPort);

    String SAMPLE_JAPANESE_RESPONSE =
        "[{\"id\":1,\"description\":\"アイウエオ\"}," +
            "{\"id\":2,\"description\":\"かきくけこ\"}," +
            "{\"id\":3,\"description\":\"さしすせそ\"}," +
            "{\"id\":4,\"description\":\"なにぬねの\"}]";

    mockServer.when(
        request().withMethod("GET")
    ).respond(
        response()
            .withHeaders(new Header("Content-Type", "application/json"))
            .withBody(SAMPLE_JAPANESE_RESPONSE)
    );

    WebTestClient webTestClient = WebTestClient
        .bindToServer()
        .baseUrl("http://localhost:" + mockServerPort)
        .build();

    //then
    webTestClient.get()
        .accept(MediaType.APPLICATION_JSON)
        .exchange()
        .expectStatus().isOk()
        .expectBody().json(SAMPLE_JAPANESE_RESPONSE);

  }
```
3. What error you saw
The test above failed with 

> Expected :  [{"id":1,"description":"アイウエオ"},{"id":2,"description":"かきくけこ"},{"id":3,"description":"さしすせそ"},{"id":4,"description":"なにぬねの"}]
> Actual : [{"id":1,"description":"?????"},{"id":2,"description":"?????"},{"id":3,"description":"?????"},{"id":4,"description":"?????"}]

**Expected behavior**
What you expected to happen :
Mockserver should use `UTF-8` encoding for the content type header `Content-Type:  application/json`.

This link also mentions the same:

[https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/MediaType.html#APPLICATION_JSON_UTF8_VALUE](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/MediaType.html#APPLICATION_JSON_UTF8_VALUE)

> MediaType.APPLICATION_JSON_UTF8_VALUE is Deprecated
> as default of 5.2 in favor of APPLICATION_JSON_VALUE since major browsers like Chrome now comply with the specification and interpret correctly UTF-8 special characters without requiring a charset=UTF-8 parameter

**MockServer Log**
```
2021-06-14 16:33:02.608  INFO 7590 --- [erver-EventLog0] org.mockserver.log.MockServerEventLog    : 14931 started on port: 14931
2021-06-14 16:33:05.472  INFO 7590 --- [erver-EventLog0] org.mockserver.log.MockServerEventLog    : 14931 creating expectation:

  {
    "id" : "b7bbff32-f35d-4d7c-92a3-3492ab41be0c",
    "priority" : 0,
    "httpRequest" : {
      "method" : "GET"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "headers" : {
        "Content-Type" : [ "application/json" ]
      },
      "body" : "[{\"id\":1,\"description\":\"アイウエオ\"},{\"id\":2,\"description\":\"かきくけこ\"},{\"id\":3,\"description\":\"さしすせそ\"},{\"id\":4,\"description\":\"なにぬねの\"}]"
    }
  }

 with id:

  b7bbff32-f35d-4d7c-92a3-3492ab41be0c

2021-06-14 16:33:06.265  INFO 7590 --- [erver-EventLog0] org.mockserver.log.MockServerEventLog    : 14931 received request:

  {
    "method" : "GET",
    "path" : "/",
    "headers" : {
      "accept-encoding" : [ "gzip" ],
      "user-agent" : [ "ReactorNetty/0.9.8.RELEASE" ],
      "host" : [ "localhost:14931" ],
      "WebTestClient-Request-Id" : [ "1" ],
      "Accept" : [ "application/json" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

2021-06-14 16:33:06.268  INFO 7590 --- [erver-EventLog0] org.mockserver.log.MockServerEventLog    : 14931 request:

  {
    "method" : "GET",
    "path" : "/",
    "headers" : {
      "accept-encoding" : [ "gzip" ],
      "user-agent" : [ "ReactorNetty/0.9.8.RELEASE" ],
      "host" : [ "localhost:14931" ],
      "WebTestClient-Request-Id" : [ "1" ],
      "Accept" : [ "application/json" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 matched expectation:

  {
    "id" : "b7bbff32-f35d-4d7c-92a3-3492ab41be0c",
    "priority" : 0,
    "httpRequest" : {
      "method" : "GET"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "headers" : {
        "Content-Type" : [ "application/json" ]
      },
      "body" : "[{\"id\":1,\"description\":\"アイウエオ\"},{\"id\":2,\"description\":\"かきくけこ\"},{\"id\":3,\"description\":\"さしすせそ\"},{\"id\":4,\"description\":\"なにぬねの\"}]"
    }
  }

2021-06-14 16:33:06.275  INFO 7590 --- [erver-EventLog0] org.mockserver.log.MockServerEventLog    : 14931 returning response:

  {
    "headers" : {
      "Content-Type" : [ "application/json" ]
    },
    "body" : "[{\"id\":1,\"description\":\"アイウエオ\"},{\"id\":2,\"description\":\"かきくけこ\"},{\"id\":3,\"description\":\"さしすせそ\"},{\"id\":4,\"description\":\"なにぬねの\"}]"
  }

 for request:

  {
    "method" : "GET",
    "path" : "/",
    "headers" : {
      "accept-encoding" : [ "gzip" ],
      "user-agent" : [ "ReactorNetty/0.9.8.RELEASE" ],
      "host" : [ "localhost:14931" ],
      "WebTestClient-Request-Id" : [ "1" ],
      "Accept" : [ "application/json" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 for action:

  {
    "headers" : {
      "Content-Type" : [ "application/json" ]
    },
    "body" : "[{\"id\":1,\"description\":\"アイウエオ\"},{\"id\":2,\"description\":\"かきくけこ\"},{\"id\":3,\"description\":\"さしすせそ\"},{\"id\":4,\"description\":\"なにぬねの\"}]"
  }

 from expectation:

  b7bbff32-f35d-4d7c-92a3-3492ab41be0c
```

**Comment by robert-gdv** [comment]
I have the same issue and I can't even find a workaround, because the Content-Type Header is not changeable in my stack.

**Comment by tignioj** [comment]
same issue too

**Comment by jamesdbloom** [comment]
This has now been fixed in the latest SNAPSHOT version for both JSON and XML responses the default is now UTF-8 as per the specification.  I was previously following the specification for plain/text and didn't notice that application/json have a different specification so this have now been fixed.

**Comment by jamesdbloom** [comment]
The SNAPSHOT will be release in the next week.
