### ISSUE TITLE
Spring test context is recreated with each test class for the same configuration

### ISSUE THREAD

**Issue by slo** [mock-server/mockserver#1044]
**Describe the issue**
In case e.g. base test class is annotated with `@MockServerTest` and there are many classes which extends this class, spring context is recreated due to specific logic of `MockServerPropertyCustomizer`
It effectively boils down to case when many classes are annotated with `@MockServerTest` - because annotation is `@Inherited`.

**What you are trying to do**
Our concern is that spring context is very heavy and it should not be recreated with every test class.

**MockServer version**
5.11.2

**To Reproduce**
Steps to reproduce the issue:

1. Create 2 classes in the same package and annotate them with `@MockServerTest`
2. Run tests for whole package
3. Spring context will be recreated with every test class (in this case 2 times)

**Expected behaviour**
Only one context should be created as configuration is the same for both.

**MockServer Log**
I think providing logs does not provide any value here.

**Comment by jamesdbloom** [comment]
Now the PR is merged I assume this issue should be fixed so closing issue
