### ISSUE TITLE
Add option to allow semicolons in query parameters 

### ISSUE THREAD

**Issue by Anshelen** [mock-server/mockserver#1047]
I think it would be great to have an opportunity to ignore semicolons in query parameters. Now ';' splits query parameters that is sometimes not desirable.

My version is 5.11.2.

I didn't find any workaround. I guess it does not exist as the decision to decode ';' is made in ExtendedParameterDecoder#39 where we set 'semicolonIsNormalChar' = false when constructing Netty QueryStringDecoder

**Comment by jamesdbloom** [comment]
I have added a configuration property so this can now be controlled, the default remains the same for backward compatibility reasons.  This will shortly be in the SNAPSHOT version which will be released in the next few weeks.
