### ISSUE TITLE
Add header to upstream

### ISSUE THREAD

**Issue by eldad87** [mock-server/mockserver#1050]
**Describe the feature request**
Add an ability to add an header to upstream.

**The solution you'd like**
The application I'm testing is issuing requests to an hardcoded domain.
To examine the communication it generates, I would like to point the domain to 127.0.0.01 using the hosts file. Then use the proxy capabilities to tunnel the traffic to the real upstream using its IP & specify the domain as Host header:
Application requests -> 127.0.0.1:80 -> MockServer -> Real-IP:80 + header 'Host: domain'

**Comment by jamesdbloom** [comment]
Request modification is now possible
using a forward override.  This is not yet documented but the code is implemented in the SNAPSHOT which will be released (with documentation) in the next week or so.

**Comment by jamesdbloom** [comment]
I'm going to close this issue but I'll make sure the imminent docs include an example of the use case you mention.
