### ISSUE TITLE
Snyk vulnerability with Netty dependency

### ISSUE THREAD

**Issue by Suedo** [mock-server/mockserver#1054]
**Describe the issue**
Snyk Vulnerability with netty : https://snyk.io/vuln/SNYK-JAVA-IONETTY-1042268

**What you are trying to do**
We are using Mockserver@5.11.2 , which internally uses netty 4. Netty 4 is analysed by Snyk to have the vulnerability : https://snyk.io/vuln/SNYK-JAVA-IONETTY-1042268 

How does this effect Mockserver? Is there a fix being made for this?

**MockServer version**
5.11.2

**Comment by Suedo** [comment]
bump

**Comment by jamesdbloom** [comment]
MockSever is using the latest version of Netty which still has the reported medium severity issue.

However, MockSever is a testing tool and so the context of its use should be considered.  Any valid security review should consider the full context to avoid fixing irrelevant things and ensuring real security benefit is being added.

Are you using Mock Sever to accept production or sensitive traffic while having mTLS? If not then I don't believe the weakened validation of certificates should have any impact.

I'm closing this here as I don't believe there is likely and impact and there is also no way to fix this.
