### ISSUE TITLE
IOException creating file watcher on startup

### ISSUE THREAD

**Issue by EdRyan** [mock-server/mockserver#1056]
**Describe the issue**
I am running a mockserver docker container, mapping a local volume to the container, containing an initialization JSON file.  Loading the initialization json works, but when I enable `MOCKSERVER_WATCH_INITIALIZATION_JSON` and try to start the docker container, I get an exception trying to create the file watcher, and changes to the initialization file are not loaded automatically into mockserver.

**What you are trying to do**
I want to be able to add/change expectation request/response configurations from a file on my local disk without needing to restart the docker container every time I make a tweak to the configuration.

**MockServer version**
5.11.2

**To Reproduce**
1. Create `docker-compose.yml` and `expectations.json` as described below
2. Run `docker-compose up`

`docker-compose.yml`:
```
version: "2.4"
services:
  mockServer:
    image: mockserver/mockserver:mockserver-5.11.2
    ports:
      - 1080:1080
    volumes:
      - type: bind
        source: .
        target: /config
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/expectations.json
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
```

`expectations.json`:
```
[
  {
    "httpRequest": {
      "path": "/simpleFirst"
    },
    "httpResponse": {
      "body": "some first response"
    }
  }
]
```

**Expected behaviour**
Config file is loaded and no exceptions are encountered creating file watcher.  Subsequent changes to the config file are reflected immediately in how mockserver handles requests.

**MockServer Log**
```
Starting mockserver_mockServer_1 ... done
Attaching to mockserver_mockServer_1
mockServer_1  | 2021-08-05 18:11:16 5.11.2 SEVERE exception creating file watcher for
mockServer_1  |
mockServer_1  |   /config/expectations.json
mockServer_1  |
mockServer_1  | java.io.IOException: Function not implemented
mockServer_1  | 	at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
mockServer_1  | 	at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
mockServer_1  | 	at org.mockserver.persistence.FileWatcher.<init>(FileWatcher.java:19)
mockServer_1  | 	at org.mockserver.persistence.ExpectationFileWatcher.<init>(ExpectationFileWatcher.java:32)
mockServer_1  | 	at org.mockserver.mock.HttpState.<init>(HttpState.java:117)
mockServer_1  | 	at org.mockserver.lifecycle.LifeCycle.<init>(LifeCycle.java:51)
mockServer_1  | 	at org.mockserver.netty.MockServer.<init>(MockServer.java:50)
mockServer_1  | 	at org.mockserver.netty.MockServer.<init>(MockServer.java:41)
mockServer_1  | 	at org.mockserver.cli.Main.main(Main.java:100)
mockServer_1  |
mockServer_1  | 2021-08-05 18:11:16 5.11.2 INFO created expectation file watcher for
mockServer_1  |
mockServer_1  |   /config/expectations.json
mockServer_1  |
mockServer_1  | 2021-08-05 18:11:16 5.11.2 INFO loading JSON initialization file:
mockServer_1  |
mockServer_1  |   /config/expectations.json
mockServer_1  |
mockServer_1  | 2021-08-05 18:11:20 5.11.2 INFO creating expectation:
mockServer_1  |
mockServer_1  |   {
mockServer_1  |     "id" : "d1f31ea7-f756-47ae-b110-bf949138001a",
mockServer_1  |     "priority" : 0,
mockServer_1  |     "httpRequest" : {
mockServer_1  |       "path" : "/simpleFirst"
mockServer_1  |     },
mockServer_1  |     "times" : {
mockServer_1  |       "unlimited" : true
mockServer_1  |     },
mockServer_1  |     "timeToLive" : {
mockServer_1  |       "unlimited" : true
mockServer_1  |     },
mockServer_1  |     "httpResponse" : {
mockServer_1  |       "body" : "some first response"
mockServer_1  |     }
mockServer_1  |   }
mockServer_1  |
mockServer_1  |  with id:
mockServer_1  |
mockServer_1  |   d1f31ea7-f756-47ae-b110-bf949138001a
```

**Comment by 70m4** [comment]
Hello,
I had the same issue, and you need to configure docker to the new file sharing restrictions, follow this post: `https://stackoverflow.com/a/60814428/4223102`
or `https://docs.docker.com/desktop/windows/`

**Comment by jamesdbloom** [comment]
This issue has now been resolve as the file watcher has been reimplemented so closing.

The fix is in the SNAPSHOT and will be released in a few weeks.

**Comment by jamesdbloom** [comment]
I don't see how it possible you are having these issues in the latest version because those method calls don't exist in the latest release.
