### ISSUE TITLE
Unable to configure proxyRemoteHost and proxyRemotePort via Helm chart

### ISSUE THREAD

**Issue by tms0** [mock-server/mockserver#1087]
**Describe the issue**
Unable to configure proxyRemoteHost and proxyRemotePort via Helm chart

**MockServer version**
5.11.1

**To Reproduce**
Steps to reproduce the issue:

1. Run MockServer with Helm : `helm upgrade --install --set service.type=LoadBalancer --set service.port=1080 --set app.proxyRemoteHost=myhost --set app.proxyRemotePort=1234 mockserver http://www.mock-server.com/mockserver-5.11.1.tgz`
2. Make a request : `curl http://localhost:1080/test`
3. Result : 404, MockServer didn't try to proxify the request

**Expected behaviour**
MockServer should proxify the request if there are no matching expectations

**My analysis**
The helm chart use these values (`app.proxyRemoteHost`, `app.proxyRemotePort`) to create environment variables (`PROXY_REMOTE_HOST`, `PROXY_REMOTE_PORT`) but these variables are simply ignored. I found an [old version of the Dockerfile](https://github.com/mock-server/mockserver/blob/d5132428d3a99251a896806900a49d1d4056cc02/docker/Dockerfile) which use a [run script](https://github.com/mock-server/mockserver/blob/d5132428d3a99251a896806900a49d1d4056cc02/docker/run_mockserver.sh) where those variables were used, but now I think the only way to make it work is to override the default command, as explained in the [Docker documentation](https://mock-server.com/where/docker.html).

If my analysis is correct, a simple workaround would be to templatize the `command` in the [deployment.yaml](https://github.com/mock-server/mockserver/blob/master/helm/mockserver/templates/deployment.yaml) file.

What do you think about it ?

**Comment by jamesdbloom** [comment]
This has now been fixed, please see this integration test covering this: https://github.com/mock-server/mockserver/blob/master/container_integration_tests/helm_remote_host_and_port/integration_test.sh
