### ISSUE TITLE
Question: 404 not found calling my PUT request

### ISSUE THREAD

**Issue by birosrichard** [mock-server/mockserver#1102]
**Describe the issue**
My GET requests works just fine but I'm having problems with my PUT requests. Getting 404 not found.

**What you are trying to do**
Calling PUT requests.

**MockServer version**
5.11.2

**To Reproduce**
```
"httpRequest": {
      "method": "PUT",
      "path": "/continueCase",
      "body": {
        "callForSignatureTask": {
          "expectedDueTime": 1,
          "expectedDueTimeUnit": "minute",,
        "caseDueDate": "30-11-2021"
      }
    },
"httpResponse": {
      "statusCode": 200,`
}
```

1. How you are running MockServer (i.e maven plugin, docker, etc)
Docker
2. Code you used to create expectations
Provided above
3. What error you saw
http://10.96.38.254:30047/continueCase 404 Not Found

**Comment by birosrichard** [comment]
Okay I got it. I removed the `body` parameter and it started working. Is `body` parameter  forbidden?

**Comment by sswastioyono18** [comment]
I think when you got error, you can check in the dashboard what cause the error. A lot of times it is because syntax issue or failure during templating

**Comment by jamesdbloom** [comment]
@birosrichard This sounds like is a syntax error, can you please confirm or post the full MockServer log so that I can see what has happened?

**Comment by jamesdbloom** [comment]
The following example shows how this should work:

###### expectation

```bash
curl -X PUT 'localhost:1080/mockserver/expectation' \
-d '{
    "httpRequest": {
        "method": "PUT", 
        "path": "/continueCase", 
        "body": {
            "callForSignatureTask": {
                "expectedDueTime": 1, 
                "expectedDueTimeUnit": "minute", 
                "caseDueDate": "30-11-2021"
            }
        }
    }, 
    "httpResponse": {
        "statusCode": 200
    }
}'
```

###### matching request

```bash
curl -X PUT 'localhost:1080/continueCase' \
--header 'Content-Type: application/json' \
-d '{
    "callForSignatureTask": {
        "expectedDueTime": 1, 
        "expectedDueTimeUnit": "minute", 
        "caseDueDate": "30-11-2021"
    }
}'
```

The syntax you provided doesn't quite look correct please copy mine and modify as required.
