### ISSUE TITLE
MockServerTest cannot be read from inherited classes

### ISSUE THREAD

**Issue by hetzijzo** [mock-server/mockserver#1104]
By default the `MockServerTest` annotation from the `mockserver-spring-test-listener` only reads the annotation from the first level class. 

When the test class extends another class, which also has a `MockServerTest`, this annotation is not processed.

`
@MockServerTest(
  "my-property=http://localhost:${mockServerPort}")
abstract class BaseTest {}
`

`
@MockServerTest(
  "my-second-property=http://localhost:${mockServerPort}")
class MyTest extends BaseTest {}
`

**Comment by jamesdbloom** [comment]
Closing this issue as the PR has provided support for this enhancement.
