### ISSUE TITLE
Should be given Complete Example of HTTPS request

### ISSUE THREAD

**Issue by irshad97feb** [mock-server/mockserver#1107]
**Describe the feature request**
Should have complete example of HTTPs connection using docker and helm chart

**What you are trying to do**
Trying to create HTTPs connection but not able to to.

**The solution you'd like**
Can be given a very good example with HTTPs connection using both docker and helm chart based configurations.

**Comment by astrieanna** [comment]
I think my current problem would also be solved by this documentation. Specifically, I'm using `mkcert` to generate a locally trusted rootCA, and I'd like to either give mock-server the rootCA or a cert generated with `mkcert`, but I'm getting all kinds of java SSL errors that the current documentation doesn't help with.

**Comment by jamesdbloom** [comment]
Duplicate of https://github.com/mock-server/mockserver/issues/1107 so closing this issue
