### ISSUE TITLE
Running as a browser proxy

### ISSUE THREAD

**Issue by jackiehamchen** [mock-server/mockserver#1109]
**Describe the feature request**
Description of the new feature,
Running mockserver as a browser proxy to supports a website-based variant of the proxy/intercept pattern, allowing to modify specific AJAX requests or swap out CSS/Javascript files.

**What you are trying to do**
Description of what you are trying to do so we can understand the context of the feature request
I would like to set a browser proxy to the mockserver e.g. host:1080 then browse to a website (System Under Test). Any resources fetched whose requests are matched by mockserver's expectation I have configured will be overridden by the mockserver's response (expectation).

**The solution you'd like**
If you know, describe how you think the feature should be implemented / or should work
Configuring mockserver to mock remote servers so that when browser proxy is set to the mockserver, the requests that match with the expectation will get mockserver's response. This would help when some specific web requests get an error and mockserver can return mock response e.g. http 200. With this use case, the client (System Under Test) does not need to change its configuration or hard code the mockserver host and port.

Client's Browser -> MockServer (localhost:1080) -> System Under Test (Web)

**Describe alternatives you've considered**
If they exist, describe any alternative solutions you've considered.

**Comment by jamesdbloom** [comment]
This already works and is documented for mac as an example, see: https://mock-server.com/proxy/configuring_sut.html#apple_mac_http_https 

However, it is up to the browser whether these setting is honoured for AJAX / JS, I suspect most don't do this.  If you need that then the JS will need to be configured to use a proxy (as I understand).
