### ISSUE TITLE
Kafka container issue

### ISSUE THREAD

**Issue by gauravmd** [mock-server/mockserver#1111]
**Describe the issue**
[confluentinc/cp-kafka:latest]","log_message":"Could not start container"
.
.
.
Command [/usr/local/bin/dub path /etc/kafka/ writable] FAILED !

**What you are trying to do**
Run the image

**MockServer version**
mockserver-5.11.2

**To Reproduce**
Run the image

1. How you are running MockServer (i.e maven plugin, docker, etc) - docker
2. Code you used to create expectations 
3. What error you saw

**Expected behaviour**
the container should start

**MockServer Log**
Log output, as INFO level (or lower)

Kafka issue reference https://github.com/confluentinc/kafka-images/issues/127

**Comment by jamesdbloom** [comment]
Not sure why this issue was raised it doesn't seem to be related to MockSever purchasing this issue posted on the wrong gitrepo.
