### ISSUE TITLE
Does mockserver uses Log4j, if yes does it have any impact of recent Log4j vulnerability issue.

### ISSUE THREAD

**Issue by sateeshd7** [mock-server/mockserver#1112]
**Describe the issue**
Description of the issue
Would like to know if Mock Server uses Log4j internally, if yes does it have any impact of Log4j vulnerability issue and when would be the next mockserver release with the latest log4j./
**What you are trying to do**
Description of what you are trying to do so we can understand the context of the problem

**MockServer version**
The version you are using (i.e. 5.11.2)

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc)
2. Code you used to create expectations
3. What error you saw

**Expected behaviour**
What you expected to happen

**MockServer Log**
Log output, as INFO level (or lower)

**Comment by hielkehoeve** [comment]
Mockserver only uses slf4j-api. The logging implementation must be provided by yourself.

**Comment by jamesdbloom** [comment]
@hielkehoeve is correct MockServer does not use Log4j
