### ISSUE TITLE
Is the project under active development?

### ISSUE THREAD

**Issue by JPR-Valo** [mock-server/mockserver#1116]
**Describe the feature request**
Hi, I would like to know if the project is currently maintained, or if I should consider using another mocking tool.

**What you are trying to do**
I am implementing a mock of my APIs

**Comment by jamesdbloom** [comment]
The project is under active development.  I would suggest this is a good project due to the flexibility supporting both mocking and proxying and the UI that shows which mocks have been executed or not and why.  Neither of these features are available currently on any other mocking tool.
