### ISSUE TITLE
Request to update the dependencies in mockserver-core 5.11.2 for fixing vulnerabilities.

### ISSUE THREAD

**Issue by linlei99** [mock-server/mockserver#1120]
**Describe the feature request**
Please update the dependencies in mockserver-core for fixing vulnerabilities.

**What you are trying to do**
The JFrog Xray  scan report shows a few of vulnerabilities under mockserver-core version 5.11.2, which has not been updated for a year. Please look at the list below for detail.
- swagger-parser:2.0.23 -> commons-io:2.4
- netty-codec:4.1.53.Final
- velocity-engine-scripting:2.2 -> velocity-engine-core:2.2

**The solution you'd like**
Please update those dependencies to the recommended fixed versions.

**Describe alternatives you've considered**
Would like to try if anyone suggests alternatives

**Comment by jamesdbloom** [comment]
These have all been updated and will be in the new released version, please see SNAPSHOT as well.

There is no technical way to update them in 5.11.2 but in 5.11.3 many dependencies have been updated.

**Comment by jamesdbloom** [comment]
Closing this issue as all dependencies that can be updated have been updated and dependabot is monitoring for any new updates
