### ISSUE TITLE
Helm chart: Allow to override runAsUser value

### ISSUE THREAD

**Issue by Snorkell** [mock-server/mockserver#1152]
**Describe the feature request**
Allow to override user id by adding `app.runAsUser` in  `values.yaml`

**What you are trying to do**
I'm trying to deploy mock server using helm on an Openshoft cluster that have security constraint on user id range that I don't have any control on

**Describe alternatives you've considered**
Forking locally to do the change

**Comment by jamesdbloom** [comment]
I've merged the PR so I'm closing this issue.  I'll will do a new release in the next two weeks or so once I've fixed a couple of minor issues.
