### ISSUE TITLE
mockserver mock external api in tests, that is called from an internal api

### ISSUE THREAD

**Issue by adnsimona** [mock-server/mockserver#1187]
Hi James,

I'd like to use mockserver's record and replay function.
Though it wouldn't be a right-away call to the api.
So our project's api is calling an external api.
I'd like to mock the external api, but not the internal api call.
Is there a way to intercept these calls and use the record & replay function on these with mockserver?

Regards,
Ádám

**Comment by jamesdbloom** [comment]
Not sure what you mean by `I'd like to mock the external api, but not the internal api call.`.  Can you please explain what you mean by external and internal.

**Comment by adnsimona** [comment]
Ok.
So let's say we have the api in our project, that has an endpoint:
GET /status
That has the following inside:

> LOGGER.info("Status called, Calling external api now.");
> String status = externalApi.getStatus(); // calls e.g. https://somesite.com/api/v12/status
> LOGGER.info("External api called, result: " + status);
> StatusRepository.add(DateTime.now(), status) // adding status to database
> LOGGER.info("Written status to DB");

I'd like to write a test that is calling our project's GET /status, but I don't like the tests to call the external api (https://somesite.com/api/v12/status) for real, and therefore I'd like to mock it.
What I'd like is that the data from the mock external api gets into the db and test if it the data is in the project's internal DB.

**Comment by jamesdbloom** [comment]
Sounds like you just need to mock the external endpoint.

First you need to confirm the the system under test to proxy all calls to the external endpoint to MockServer so you can record them.  Then you can use that to mock the external endpoint.  See: https://mock-server.com/proxy/getting_started.html and https://mock-server.com/proxy/record_and_replay.html
