### ISSUE TITLE
Not all Mockserver dependencies shaded, shaded packages not renamed

### ISSUE THREAD

**Issue by pip25** [mock-server/mockserver#1201]
**Describe the issue**
The shaded JAR keeps its included dependencies in their original package name structure, meaning they can still conflict with different versions of the same libraries. Also, some dependencies, such as netty-common, are still pulled in by Maven separately.

**What you are trying to do**
I tried including MockServer in an existing, older project that uses wildly different versions of Jackson, SLF4J etc, so I imported the shaded version via Maven. Unfortunately MockServer crashes right away during startup because of these version conflicts. Also, the project's list of Maven dependencies grows significantly, including several netty JARs.

**MockServer version**
5.12.0

**To Reproduce**
Add the shaded version of MockServer to a project with an incompatible Jackson version, for instance. MockServer will crash on startup.

**Expected behaviour**
Adding the shaded version of MockServer to a project should add only one single JAR to the Maven classpath, that being the shaded server JAR. Ideally, this file should also include the contents of the client and core JARs as well. The packages of the shaded dependencies should be renamed, for instance by adding a org.mockserver.shaded prefix to their package names, so they do not interfere with other libraries. The Maven Shade Plugin has configuration options that can facilitate this.

**Comment by jamesdbloom** [comment]
I'm working on a fix for this but it's a little hacks due to limitations in the way maven works 
- only a single Pom file irrespective or classifier and
- the shaded plugin not handling reflective creation of classes well

I'm close to a solution once I've resolved a few more issues.

**Comment by jamesdbloom** [comment]
This is now fixed as mockserver-client-java, mockserver-junit-jupiter, mockserver-junit-rule and mockserver-netty all have both a shaded classier with al packages re-named and a separate artefact called x-no-dependencies i.e. mockserver-netty-no-dependencies.

The shaded classier version still has the same transitive dependencies as that is only allowed approach with maven, thus the reason why the x-no-dependencies artefact were also created.

See here: https://oss.sonatype.org/index.html#view-repositories;snapshots~browsestorage~org/mock-server/mockserver-

**Comment by joelmarty** [comment]
I believe this should be re-opened as the shaded package still contains the embedded packages with their original name.
The capture below was done with 5.14 but it is the same for 5.15.
<img width="411" alt="image" src="https://github.com/mock-server/mockserver/assets/134835/c40d3ec7-fbe5-440b-b9d7-7da5d831eb73">

org.slf4j package not being shaded is a particularly problematic one, as many libraries and code bases use it.
