### ISSUE TITLE
Truncated responses from server

### ISSUE THREAD

**Issue by O5ten** [mock-server/mockserver#1224]
I'm receiving truncated responses from server from my proxy-generated expectations. This endpoint in particular below should yield an empty array. But it gives me half. At first i thought it was my nginx that was spooking out on buffering, but when i target the mock-server directly i receive this. 

```
$ curl -v -u $CREDENTIALS  localhost:1080/inventory/verify-sla-zones
*   Trying 127.0.0.1:1080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 1080 (#0)
* Server auth using Basic with user XXX''
> GET /inventory/verify-sla-zones HTTP/1.1
> Host: localhost:1080
> Authorization: Basic XXXXXXXXXXXXXXXXXXXXX
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 2
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Set-Cookie: XXXXXYYYYYZZZZZZZZZZZ; Path=/; HttpOnly
< Server: nginx/1.14.1
< Referrer-Policy: no-referrer
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Date: Mon, 14 Mar 2022 13:12:40 GMT
< Content-Type: application/json
< Content-Security-Policy: script-src 'self' 'unsafe-eval';
< connection: keep-alive
<
* Excess found in a read: excess = 1, size = 2, maxdownload = 2, bytecount = 0
* Connection #0 to host localhost left intact
[
```

This is what my expectation looks like. I have about 50-60 expectations where the responses together amounts to ~10Mb. 
![image](https://user-images.githubusercontent.com/3242379/158180050-35f3fb54-3e05-4d1f-b0f8-47d93751bd7b.png)

Any ideas on what is going on? 
Have i missed a configuration setting somewhere? 

It works fine when i proxy the request straight through to the real backend through the mockserver. So it seems to me hat the netty-server is the failing link here somehow. 

I'm using `mockserver/mockserver:mockserver-5.12.0`

**Comment by jamesdbloom** [comment]
Can you please provider the code / json you are using to generate your expectations that were generated by the proxy.

**Comment by jamesdbloom** [comment]
It looks like the content length is too short because the JSON is being returned pretty printed which adds a space in-between the opening and closing square brackets.  This mean the content-length of 2 is one character too short.

**Comment by O5ten** [comment]
It turned out to be the `Content-Length` header as you seem to have deduced aswell. 
I solved it on my end by cleaning out the response-headers with some `jq`-shenanigans. 

Nice that you added a warning for it, would have saved me a couple hours of RFTM, trial & error. <3
