### ISSUE TITLE
Add the ability to use endpoints examples instead of schemas examples on an OpenAPI spec

### ISSUE THREAD

**Issue by AlexRuiz7** [mock-server/mockserver#1229]
**Describe the feature request**
I'm using MockServer with an OpenAPI specification on a YAML format, and even though the specification provides examples for each of the endpoints, namely for each verb and status code, the Mock Server fails to detect the examples and provided sample data instead (`some_string_value`), as seen on the example below taken directly from a response provided by MockServer.

```json
"httpRequest": {
    "operationId": "api.controllers.default_controller.default_info",
    "specUrlOrPayload": "https://raw.githubusercontent.com/wazuh/wazuh/v4.2.5/api/api/spec/spec.yaml"
},
"httpResponse": {
    "statusCode": 200,
    "headers": {
        "content-type": [
            "application/json"
        ]
    },
    "body": {
        "data": {
            "title": "some_string_value",
            "api_version": "some_string_value",
            "revision": 0,
            "license_name": "some_string_value",
            "license_url": "some_string_value",
            "hostname": "some_string_value",
            "timestamp": "some_string_value"
        }
    }
},
```

The OpenAPI spec provides a clear response example for this operation, as seen below:

```yaml
/:
    get:
      tags:
        - API Info
      summary: 'Get API info'
      description: "Return basic information about the API"
      operationId: api.controllers.default_controller.default_info
      parameters:
        - $ref: '#/components/parameters/pretty'
      responses:
        '200':
          description: "API default info"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/BasicInfo'
              example:
                title: "Wazuh API"
                api_version: "v4.2.0"
                revision: '40100'
                license_name: "GPL 2.0"
                license_url: "https://github.com/wazuh/wazuh/blob/4.2/LICENSE"
                hostname: "wazuh"
                timestamp: "2019-04-02T08:08:11+0000"
```

**What you are trying to do**
I'd like MockServer to use this endpoint level example, as it is trying to read examples at models' level, and they are not always present as we use the same model for several endpoints (mostly to use class inheritance, so it makes sense that examples are on the final class, and not on the base class).

**The solution you'd like**
Use the example given for the endpoint, if present. The examples at endpoint level should take priority over the model's example.

**Describe alternatives you've considered**
-

**Comment by jamesdbloom** [comment]
This makes sense and should be able to be implemented in the next month or so.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/NK0On5Jv/183-endpoints-examples-instead-of-schemas-examples-on-an-openapi-spec

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
