### ISSUE TITLE
FORWARDED_REQUEST seems to be ignoring configured host for expectation httpForward.host

### ISSUE THREAD

**Issue by jhastingsiii** [mock-server/mockserver#1232]
**Describe the issue**
FORWARDED_REQUEST going to localhost:1080 instead of configured host.

**What you are trying to do**
Forward request to another host.

**MockServer version**
The version you are using (i.e. 5.13.0): 5.13.0

**To Reproduce**
Steps to reproduce the issue:
Configure expectation using PUT request below
Call GET https://localhost:1080/my/path

1. How you are running MockServer (i.e maven plugin, docker, etc): java -jar .\mockserver-netty-5.13.0-shaded.jar -serverPort 1080
2. Code you used to create expectations
PUT https://localhost:1080/expectation
```json
[{
"httpRequest": {
"method": "GET",
"path": "/my/path"
},
"httpForward": {
"host: "some-internal-host.com",
"port": 443,
"scheme": "HTTPS"
}
}]
```
3. What error you saw
404 response, FORWARDED_REQUEST matched by my configured expectation, but CURL request is made to "localhost" instead of "some-internal-host.com"

**Expected behaviour**
The following request to be made: GET https://some-internal-host.com/my/path

**MockServer Log**
Log output, as INFO level (or lower): Will edit and add logs from other machine when I get time.

**Comment by jhastingsiii** [comment]
I guess I misunderstood the output, which is just the serialization of my original request in CURL and not the actual request being forwarded. But it still doesn't seem to be going to the configured forwarded host for some reason, if I change the hostname in the outputted CURL request to the one I configured in my httpForward.host for the expectation, the response comes back fine and returns everything I expect rather than the 404 MockServer is saying the response is.

**Comment by jamesdbloom** [comment]
The example json above is not valid is this the JSON you submitted?  It should be like this:

```json
[
  {
    "httpRequest": {
      "method": "GET",
      "path": "/my/path"
    },
    "httpForward": {
      "host": "some-internal-host.com",
      "port": 443,
      "scheme": "HTTPS"
    }
  }
]
```

If you used that JSON that would explain why it doesn't work.

**Comment by jhastingsiii** [comment]
That would be the correct JSON, I was typing it from another machine and just left it out by accident. The expectation does show up under Active Expectations and the requests do show up under Received and Proxied.

**Comment by jamesdbloom** [comment]
The following example expectation, shows this working:

```bash
curl -X PUT http://localhost:1080/expectation --data '[
  {
    "httpRequest": {
      "method": "GET",
      "path": "/index.html"
    },
    "httpForward": {
      "host": "www.mock-server.com",
      "port": 443,
      "scheme": "HTTPS"
    }
  }
]'
```

With the correct response when this request is made:

```bash
curl http://localhost:1080/index.html -H "Host: www.mock-server.com"
```

In your case the endpoint your request is forwarded to is returning a 404 which is in turn returned by MockServer.  This is very common for example if the request doesn't have the correct `Host` header.

For example both the following requests return error status codes which MockServer returns back:

```bash
curl -v http://localhost:1080/index.html
*   Trying ::1:1080...
* Connected to localhost (::1) port 1080 (#0)
> GET /index.html HTTP/1.1
> Host: localhost:1080
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Server: CloudFront
< Date: Wed, 23 Mar 2022 21:44:52 GMT
< Content-Type: text/html
< X-Cache: Error from cloudfront
< Via: 1.1 0087f642e3b56028680f93cd202d0004.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: DUB2-C1
< X-Amz-Cf-Id: mJSSn4hV4n_0ERY2qFFhOAPblKvKlzxhX_paZnvwH1npfpUlQWx_Mw==
< connection: keep-alive
< content-length: 915
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: mJSSn4hV4n_0ERY2qFFhOAPblKvKlzxhX_paZnvwH1npfpUlQWx_Mw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

or:

```bash
curl -v http://localhost:1080/wrong_page.html -H "Host: www.mock-server.com"
*   Trying ::1:1080...
* Connected to localhost (::1) port 1080 (#0)
> GET /wrong_page.html HTTP/1.1
> Host: www.mock-server.com
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: CloudFront
< Date: Wed, 23 Mar 2022 21:45:24 GMT
< Content-Type: text/html
< Location: https://www.mock-server.com/wrong_page.html
< X-Cache: Redirect from cloudfront
< Via: 1.1 325491a666fd60e1d15254e969c68c84.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: DUB2-C1
< X-Amz-Cf-Id: BpMyUV--WqnFTGAoMdiaoq1FytBGc0vZGcZ3Oa84gtrPijLzmUA4yw==
< connection: keep-alive
< content-length: 183
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```

**Comment by jamesdbloom** [comment]
If you can provide the full logs for MockServer then I can confirm exactly what is happening.

**Comment by jhastingsiii** [comment]
Ah thank you, the host header was what I needed.
