### ISSUE TITLE
Error "$.timestamp: is not defined in the schema and the schema does not allow additional properties" when try to initialize with exported requestResponse file

### ISSUE THREAD

**Issue by pfichtner** [mock-server/mockserver#1236]
**Describe the issue**
MockServer unable to read the expectations it exported from records

**What you are trying to do**
Using MockServer as proxy, it records all interactions as expected. 
After retrieving the interactions as JSON and writing them to a file I am trying to start a MockServer with this json file which results in
```
schema validation errors:

  1 error:
   - $.timestamp: is not defined in the schema and the schema does not allow additional properties
  
  OpenAPI Specification: https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.13.x 
```

**MockServer version**
5.13.0

**To Reproduce**
Record some interactions, write them to a file and start a MockServer instance which initializes from that json file. 

Use the attached [example interaction](https://github.com/mock-server/mockserver/files/8343102/recordedRequestsAndResponses.txt)  (just for reference, it was retrieved using the JavaClient but that shouldn't matter and had it to name *.txt). 
`new MockServer(configuration().initializationJsonPath("path/to/the.json"), 8765);`
will crash with the exception text above. After purging `timestamp` from the json file MockServer starts and works as expected. 

**Expected behaviour**
Expecting that MockServer can read its generated file as described in the docs. If this is a bug of MockServer I guess there are tests  missing that verifies, if MockServer works with the file it previously has exported/generated. 

**MockServer Log**
no more logs needed I guess

**Comment by pfichtner** [comment]
Thanks for the clarification. The I misinterpreted https://github.com/mock-server/mockserver/issues/101#issuecomment-87293110
Thought this would give me what I was looking for. On the other hand, removing the timestamp from the rerecorded **request and response** and using them as **recorded expectations** format seems to work. Will investigate it further,

**Comment by jamesdbloom** [comment]
I've now made a change that allows **request and response** to be used as expectation as it allows the `timestamp` field as an additional property.  I'm just running the build to add this to the latest SNAPSHOT then I'll push the fix.

**Comment by pfichtner** [comment]
Hey James, great! Thanks for that!
