### ISSUE TITLE
Will upgrade spring dependency?

### ISSUE THREAD

**Issue by hhch** [mock-server/mockserver#1253]
**Describe the issue**
spring-beans-* has a bug, see 
https://github.com/spring-projects/spring-framework/commit/7f7fb58dd0dae86d22268a4b59ac7c72a6c22529

**MockServer version**
The version you are using (i.e. 5.11.1)

Will are mockserver going to upgrade spring dependency?

**Comment by jamesdbloom** [comment]
MockServer only uses Spring for `mockserver-spring-test-listener` which is on the latest version.  If you want the latest version I suggest you upgrade MockServer the current version is 5.13.0 as per the [README](https://github.com/mock-server/mockserver#previous-versions)
