### ISSUE TITLE
mockserver-client-java-no-dependencies does not resolve using gradle

### ISSUE THREAD

**Issue by serin-it** [mock-server/mockserver#1264]
**Description of the issue**
When using gradle with the following dependency: 
org.mock-server:mockserver-client-java-no-dependencies:5.13.1

gradle fails with the following error:
> Could not resolve org.mock-server:mockserver-client-java-no-dependencies:5.13.1.
         > inconsistent module metadata found. Descriptor: org.mock-server:mockserver-client-java:5.13.1 Errors: bad module name: expected='mockserver-client-java-no-dependencies' found='mockserver-client-java'

**Description of what you are trying to do so we can understand the context of the problem**
Trying to use gradle without any transitive dependencies so that there are no version conflicts with third party jars

**The version you are using (i.e. 5.13.1)**
5.13.1

**To Reproduce**
Does not get as far as running mock-server because of the dependency problem listed above. Simply using the dependency (via maven central) as follows will recreate the bug: org.mock-server:mockserver-client-java-no-dependencies:5.13.1

**Note:** Even clearing the gradle cache (/home/{user-name}/.gradle in my case on Ubuntu)  does not help.

**Comment by jamesdbloom** [comment]
I can see what the issue is.  It seems gradle does extra checks that maven doesn't do when it downloads a library.  It may be possible to turn these off.  These dependencies work find for maven but due to gradles extra checks they don't currently work.  I know how to fix it but I want to add an integration test for gradle before pushing the fix to ensure it stays fixed.

**Comment by serin-it** [comment]
That was quick! Sounds very promising, thanks.

**Comment by jamesdbloom** [comment]
I'll push a fix to the SNAPSHOT version in the next day or so.

**Comment by serin-it** [comment]
I can confirm this works in 5.13.2, thanks.
