### ISSUE TITLE
Add hint at Docker Hub so users know about the stauts jamesdbloom/mockserver Docker image

### ISSUE THREAD

**Issue by bennetelli** [mock-server/mockserver#1268]
Hi there, 

after some investigation we found the reason for these two docker images. 

It would be great if there could be a hint for it somewhere. Maybe that would save time for other users who are wondering about these two images as well. 

Best regards :)

**Comment by jamesdbloom** [comment]
jamesdbloom/mockserver is legacy and deprecated but only there for backward compatibility, as far as I'm aware docker doesn't support redirects (like github) or any way of making a repository deprecated.

**Comment by jamesdbloom** [comment]
given the MockServer website has pointed users toward mockserver/mockserver for > 1 year, I'd be happy to stop pushing to jamesdbloom/mockserver for all future versions (i.e. 5.14.x onwards)

**Comment by bennetelli** [comment]
Ah. I didn't know that docker doesn't have a feature like that. Makes sense to me. 
Even now that we know the difference, I still think it could be helpful to add a sentence like yours at the beginning of the docker hub page: https://hub.docker.com/r/jamesdbloom/mockserver/

**Comment by bennetelli** [comment]
Just forgot to say: thanks for your quick response and your work on mockserver :)

**Comment by jamesdbloom** [comment]
That page sadly is pulled from the repo so it can't be customised uniquely to that repo, any change would also appear for mockserver/mockserver.

**Comment by jamesdbloom** [comment]
I've updated some small text on that page but for now that is most I can do so closing this issue.

**Comment by bennetelli** [comment]
Thanks :)
