### ISSUE TITLE
Add support for API specifications in ".yml" files

### ISSUE THREAD

**Issue by dkozhuharov** [mock-server/mockserver#1279]
**Describe the feature request**
Currently the server supports loading API specs coming in ".yaml" files. Sometimes - for files of that format - the ".yml" extension is used.

**What you are trying to do**
Enable MockServe to upload API specifications, when their file has a suffix of ".yml". 

**The solution you'd like**
The handling logic will be completely identical to the one for handling ".yaml" files.

**Describe alternatives you've considered**
None

**Comment by jamesdbloom** [comment]
Thanks, I have merged the PR so this is now fixed.
