### ISSUE TITLE
Injected instance is null (Constructor Injection)

### ISSUE THREAD

**Issue by frudolph77** [mock-server/mockserver#1288]
**Describe the issue**
It seems that injecting `MockServerClient` into constructor is not working.

**What you are trying to do**
I'm trying to use MockServer as a 'standalone' MockServer to run IntegrationTests.

I have added the following to the pom:** 
```xml
<dependency>
    <groupId>org.mock-server</groupId>
    <artifactId>mockserver-junit-jupiter</artifactId>
    <version>5.13.2</version>
</dependency>
```
I'm not using `...-no-dependencies` because it breaks the logging in the project, due to multiple SLJ4J bindings.

In my TestCase im using 
```java
@ExtendWith(MockServerExtension.class)
@MockServerSettings(ports = {3000})
public class OperatorTest extends AbstractOperatorTest {

    private final ClientAndServer client;

    public OperatorTest(ClientAndServer client) {
        this.client = client;
        client.when(
              request()
                  .withMethod("POST")
                  .withPath("/api/token")
                  .withBody("...")
          )
          .respond(
              response()
                  .withStatusCode(200)
                  .body(
                      // ...
                  )
          );
    }

    @Test
    void testSomething() {
        // ...
    }
}
```

**MockServer version**
5.13.2

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer 
    as JUnit 5 Test Extension
2. Code you used to create expectations
   Not relevant because of NullPointerException
3. What error you saw
   NullPointerExecption at `client.when()`

**Expected behaviour**
`ClientAndServer` or `MockServerClient` Instance in constructor not to be null

**MockServer Log**
But in the LOG I see this
```
13:32:09.991 [MockServer-EventLog0] INFO  3000 started on port: 3000
```

So the MockServer is started, and I also see the logs of the incoming request when I disable the configuring of expectations

 

When using injection to `@BeforeAll` or test case the injected client is **not** null, but in the specific case I can't use these approaches. It's mandatory to init the MockServer in the Constructor of the TestClass.

**Comment by jamesdbloom** [comment]
I can see the issue you mentioned with multiple SLF4J bindings, it seems that the shaded plugins includes optional dependencies from the pom which seems like a bug in the shaded plugin to me.

I'm just testing a fix for that first before looking at the issue you mentioned above.

**Comment by jamesdbloom** [comment]
The SNAPSHOT version now no longer had the jdk14 SLF4J bindings in the shaded or no-dependencies jars.

**Comment by jamesdbloom** [comment]
I can't reproduce this error but you haven't provided the code for `AbstractOperatorTest` which I imagine is what may be causing the problem in you case.

If you provide the code for `AbstractOperatorTest` I may be able to understand why this is not working in your case.
