### ISSUE TITLE
How do I customize the logging format for my logging service that uses logstash and logback (datadog)

### ISSUE THREAD

**Issue by red8888** [mock-server/mockserver#1309]
**Describe the issue**
I use datadog which by default can read java logs as configured here: https://docs.datadoghq.com/logs/log_collection/java/?tab=logback#configure-your-logger

**What you are trying to do**
Is it possible to configure logging like in that link? It says I need to add the Logstash encoder dependency to the pom but I don't think I have access to mockserver's pom right? 

I can see I can specify a logback config like this `-Dlogback.configurationFile=<fully qualified directory path>/example_logback.xml`

But how do I add the logstach encoder dependency? 
```
<dependency>
  <groupId>ch.qos.logback</groupId>
  <artifactId>logback-classic</artifactId>
  <version>1.2.9</version>
</dependency>
<dependency>
  <groupId>net.logstash.logback</groupId>
  <artifactId>logstash-logback-encoder</artifactId>
  <version>6.6</version>
</dependency>
```

**MockServer version**
5.13.2

EDIT
=== 
Just want to add at the very least setting the logging to output in json would be a step forward. How can I set mockserver to log in json?

**Comment by natrem** [comment]
@red8888 how do use mock-server? If it is as an embedded server or maven plugin then you can control dependencies.
You should also specify how you integrate it (I mean the specific dependencies or process you use to start it.

**Comment by jamesdbloom** [comment]
This is possible by using the JUL to SLF4j bridge, for example:

```xml
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>jul-to-slf4j</artifactId>
    <version>1.7.36</version>
</dependency>
```

However in recent versions of the no-dependency or shaded jars an extra logging binding was included due to a but in the shading plugin around optional maven dependencies.  That has been fixed in: [#2711c](https://github.com/mock-server/mockserver/commit/2711c33469277fe049d58a8bbaef0b18693e447a).  However to avoid this issue used the mockserver version with transitive dependencies:

```xml
<dependency>
  <groupId>org.mock-server</groupId>
  <artifactId>mockserver-netty</artifactId>
  <version>5.13.2</version>
</dependency>
```

**Comment by jamesdbloom** [comment]
Also see logback documentation: https://www.slf4j.org/legacy.html#jul-to-slf4j

**Comment by red8888** [comment]
@natrem I just use the official mockserver docker image
