### ISSUE TITLE
Referrer domain does not get overridden with the host when httpOverrideForwardedRequest

### ISSUE THREAD

**Issue by jacqueswest** [mock-server/mockserver#1339]
**Describe the issue**
Everything is working besides the referrer URL domain is not updated with the Host I need to override it with.
The documentation is not clear on the referrer URL/domain override

Is this a current issue or a configuration issue on myside?

**What you are trying to do**
I am currently mocking a webpage and I need all HTML pages to be forwarded.

**MockServer version**
Dockerised 5.13.2

**To Reproduce**

1. Create an expectation with response header of a webpage that uses referrer URL's

**Expected behavior**
The referrer domain must also be overridden

**MockServer Log**
I cannot add as it can contain sensitive information

**Comment by jamesdbloom** [comment]
Can you please provide more information such as an example of how your are creating your expectations and why you think the referrer domain should be updated.

**Comment by jacqueswest** [comment]
Hi James,

Thanks for the reply. 

It actually turned out we had a configuration issue on our side. I will close the ticket.
