### ISSUE TITLE
Bouncycastle discontinued to support JDK 1.5 artifacts.

### ISSUE THREAD

**Issue by nickstolwijk** [mock-server/mockserver#1354]
**Describe the issue**
As of version 1.71 Bouncycastle no longer publishes the `*-jdk15on` artifacts. Mockserver should move to the `*-jdk18on` version of these artifacts. (Or `-jdk15to18`, but I don't know if that is necessary)

> Packaging Change (users of 1.70 or earlier): BC 1.71 changed the jdk15on jars to jdk18on so the base has now moved to Java 8. For earlier JVMs, or containers/applications that cannot cope with multi-release jars, you should now use the jdk15to18 jars.

Source: https://bouncycastle.org/latest_releases.html

**What you are trying to do**
I am trying to ban the `*-jdk15on` artifacts in my project in favour of the `*-jdk18on` artifacts, but now I need to exclude the `*-jdk15on` artifacts from the Mockserver artifact.

```
<dependency>
      <groupId>org.mock-server</groupId>
      <artifactId>mockserver-junit-jupiter</artifactId>
      <version>5.13.2</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.bouncycastle</groupId>
          <artifactId>bcprov-jdk15on</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.bouncycastle</groupId>
          <artifactId>bcpkix-jdk15on</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```
**MockServer version**
5.13.2

**To Reproduce**
Steps to reproduce the issue:

1. Add Mockserver as a dependency to your POM.
2. Run `mvn dependency:tree -Dincludes="org.bouncycastle:*"`
3. I saw dependencies on discontinued artifacts.

**Expected behaviour**
I expect to only see dependencies that are still supported, like the Bouncycastle `*-jdk18on` artifacts.

**Comment by jamesdbloom** [comment]
Closing as PR now merged
