### ISSUE TITLE
I cannot access to the mockserver-netty-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by agutierrezasapp** [mock-server/mockserver#1367]
**Describe the issue**
I cannot access to the file in dockerfile

**What you are trying to do**
Copy the mockserver-netty-jar-with-dependencies.jar 

**MockServer version**
5.13.2

**To Reproduce**
Steps to reproduce the issue:

I have the following code

```
FROM jamesdbloom/mockserver:mockserver-5.12.0 AS mockserver

FROM openjdk:13-alpine3.9 as etm-mock

USER root
WORKDIR /home/etm
RUN apk add --no-cache \
    curl \
    bash

RUN mkdir -p /home/etm

ADD init.sh /home/etm/init.sh
ADD entrypoint.sh /home/etm/entrypoint.sh
ADD healthcheck.sh /home/etm/healthcheck.sh

HEALTHCHECK --interval=2s --retries=30 CMD /home/etm/healthcheck.sh

EXPOSE 8080

COPY --from=mockserver /mockserver-netty-jar-with-dependencies.jar /home/etm/mockserver.jar
```
If I change to the `FROM jamesdbloom/mockserver:mockserver-5.13.2 AS mockserver`
I Have the following error
`COPY failed: stat /var/lib/docker/aufs/mnt/2f0bce55225f349b62ed674cf8a58ca31241de58a924d7d55d88908ee8764c20/mockserver-netty-jar-with-dependencies.jar: no such file or directory`

**Comment by jamesdbloom** [comment]
The MockServer image is based on distroless so I can't make any guarantees about how it works to copy files out of as that image is not designed for that.

If you want to add the mockserver jar I suspect it would be much simpler to just download it from nexus as follows:

```docker
RUN wget --max-redirect=10 -O/home/etm/mockserver.jar "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=org.mock-server&a=mockserver-netty&c=jar-with-dependencies&e=jar&v=5.13.2"
```
