### ISSUE TITLE
Clear expectations by regex path not working as expected

### ISSUE THREAD

**Issue by luccasmtxr** [mock-server/mockserver#1374]
Issue:
Trying to clear all expectations that match a regex path.

Basically i need to remove all expectations that match a specific path, but when try to use CLEAR api passing a regex path as a parameter it doesnt match all of the expectations that i need, the ones with path parameters keep existing, even though follow the same path.

MockServer version
5.13.2

To Reproduce
Steps to reproduce the issue:
i run mockserver 5.13.2 in docker in my local machine.
create multiple expectations, from a local file using:
`curl -v -X PUT "http://localhost:1080/mockserver/openapi" -d "{"specUrlOrPayload": $(cat $PWD/openapi.json)}"`

im using https://petstore.swagger.io/ for testing purposes

![image](https://user-images.githubusercontent.com/58783585/175556620-3c2862c8-f0ff-4004-bd3c-f9798b0e954f.png)
![image (1)](https://user-images.githubusercontent.com/58783585/175556668-dcbd8772-fec6-47d3-9e4b-8f26b13117ca.png)

call the clear api which like so:
`
curl -v -X PUT "http://localhost:1080/mockserver/clear" -d '{
    "path": "/petshop.*"   
}'
`
![image (2)](https://user-images.githubusercontent.com/58783585/175556796-d202c42d-d62e-4d25-9d29-9ac0d5ef0fd1.png)
![image (3)](https://user-images.githubusercontent.com/58783585/175556820-c15b98ba-a8a5-4710-872b-8fbb6502add5.png)

Expected behaviour
Clear all the expectations that follow this regex path.

**Comment by jamesdbloom** [comment]
this is now fixed, it will be pushed to the SNAPSHOT shortly and will be released in the next few days.
