### ISSUE TITLE
Reset request only history 

### ISSUE THREAD

**Issue by VicentVallsBM** [mock-server/mockserver#1379]
**Describe the feature request**
Be able to clear all the request history from MockServer API

**What you are trying to do**
When we use mock-server in the automated testing context, it's great be able to know when a request is done. Have a great control about the request our tested application is or not doing is key. Some times we want to check with one input the service calls one service X and with other input the service calls one other service Y.

I created 2 test with 2 asserts:
 - testInputXCallsServiceX
   - execute the logic
   - verify call to X was done
   - verify call to Y was't done
 - testInputXCallsServiceY
   - execute the logic
   - verify call to Y was done
   - verify call to X was't done (fails because was called in the test before)

If I was able to clean the history from the MockServer API, We will be able to make all test independent.
 - testInputXCallsServiceX
   - Clean the mock server's request history 
   - execute the logic
   - verify call to X was done
   - verify call to Y was't done
 - testInputXCallsServiceY
   - Clean the mock server's request history 
   - execute the logic
   - verify call to Y was done
   - verify call to X was't done

**The solution you'd like**
We can add an optional flag or parameter with valid values(requests or all) to the Mock Server API  reset call ( https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.13.x#/control/put_mockserver_reset ) 
or as part of the url :
 - mockserver/reset/requests

**Describe alternatives you've considered**
I considered execute the reset and add again the expectation but if we use it in most of the test the perfomance is terrible.

**Note**
If you give me some guide I can try to implement it and send the MR.

**Comment by jamesdbloom** [comment]
This is already supported using clear and the `type` parameter.  This wasn't very clear from the OpenAPI which I have now added here: https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.13.x?loggedInWithGitHub=true#/control/put_mockserver_clear.  I have also improve the document https://mock-server.com/mock_server/clearing_and_resetting.html#button_client_clear_logs_by_req and given a specific example of how to do this: https://mock-server.com/mock_server/clearing_and_resetting.html#button_client_clear_all_logs
