### ISSUE TITLE
Helm chart cannot have multiple releases in the same namespace

### ISSUE THREAD

**Issue by Gentoli** [mock-server/mockserver#1394]
**Describe the issue**
Name for K8s object in the [chart](https://github.com/mock-server/mockserver/tree/28732e18678866e618e7d68fbbb8b288ae932377/helm/mockserver) should be unique to the release. 

**What you are trying to do**
Have multiple mock server instance running in the same k8s namespace.

**MockServer version**
chart version 5.10.0

**To Reproduce**
Steps to reproduce the issue:

```
helm template test-2 mockserver/mockserver -n some-ns --version 5.10.0 | grep 'name:'
helm template test-1 mockserver/mockserver -n some-ns --version 5.10.0 | grep 'name:'
```
With outputs:

``` zsh
% helm template test-2 mockserver/mockserver -n some-ns --version 5.10.0 | grep 'name:'
  name: test-2-mockserver
    - name: serviceport
  name: mockserver
      name: mockserver
        - name: mockserver
            - name: serviceport
            - name: LOG_LEVEL
            - name: SERVER_PORT
  name: "test-2-mockserver-service-test"
    - name: curl
% helm template test-1 mockserver/mockserver -n some-ns --version 5.10.0 | grep 'name:'
  name: test-1-mockserver
    - name: serviceport
  name: mockserver
      name: mockserver
        - name: mockserver
            - name: serviceport
            - name: LOG_LEVEL
            - name: SERVER_PORT
  name: "test-1-mockserver-service-test"
    - name: curl

```
both generate a deployment with name `mockserver`

**Expected behaviour**
the names are different.

**MockServer Log**
n/a

**Comment by jamesdbloom** [comment]
This can be achieved using the `nameOverride` value in the helm chart.

as follows:

```bash
helm template test-2 mockserver/mockserver -n some-ns --version 5.10.0 --set nameOverride=foo | grep name:
```

However I'm not sure the way these variables are used is very clear so I'm looking into this currently.  I'll leave this ticket open until I've finished reviewing the naming.

**Comment by jamesdbloom** [comment]
In addition to the 'nameOverride' value that can be used now the naming is driven from release name so multiple releases with different names don't clash
