### ISSUE TITLE
Allow returning not valid JSON response

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [mock-server/mockserver#1415]
**Describe the issue**
Returning a 200 response with a not valid json is failing.

**What you are trying to do**
I want to test that a Retrofit adapter is able to map the real exception, `SerializationException`, to an `Unknown` branch on a `sealed class`.

Looks like MockServer is checking that the Json is invalid.

**Expected behaviour**
Allowing returning an invalid json string.

**Comment by jamesdbloom** [comment]
You need to specific the invalid JSON as a string body and specific the correct content-type for the response, as follows:

```java
new ClientAndServer(1080)
    .when(
        request()
            .withMethod("GET")
            .withPath("/invalid_json")
    )
    .respond(
        response()
            .withHeader("Content-Type", MediaType.APPLICATION_JSON_UTF_8.toString())
            .withBody("{ \"name\", \"", MediaType.APPLICATION_JSON_UTF_8)
    );
```
