### ISSUE TITLE
Upload oficial image to public ECR (gallery.ecr.aws)

### ISSUE THREAD

**Issue by clucca-gb** [mock-server/mockserver#1430]
**Describe the feature request**
Mockserver doesn't have the image from a verified account at AWS Elastic Container Registry.
It would be great that Mockserver added a mirror at [ECR](https://gallery.ecr.aws/?searchTerm=mockserver) for the [current image](https://hub.docker.com/r/mockserver/mockserver) and kept it up to date like a current image

**What you are trying to do**
My company needs a trusty image to use with sonar to run tests with Docker .

**The solution you'd like**
Just provide an image.

**Describe alternatives you've considered**
I think, there's no other alternatives to solve this.

**Comment by clucca-gb** [comment]
Hello! Thanks for your reply.
Yeah, I agree with you and now we use this image, but our environment are on AWS, using ECR would save resource and tools in addition to have more usage limits.

**Comment by jamesdbloom** [comment]
Can you please explain how using ECR save resources and tools or have more usage limits?
