### ISSUE TITLE
MockServerClient always uses new/empty configuration

### ISSUE THREAD

**Issue by smithap** [mock-server/mockserver#1453]
I want to pass in an updated socket timeout:

org.mockserver.configuration.Configuration c = new org.mockserver.configuration.Configuration();
c.maxSocketTimeoutInMillis(30_000L);
mockServer = startClientAndServer(c, port);

but I think the configuration in the client is not honoured? A fresh Configuration is always created at https://github.com/mock-server/mockserver/blob/master/mockserver-client-java/src/main/java/org/mockserver/client/MockServerClient.java#L366

So if/when a timeout occurs, the error message in the exception says:

org.mockserver.httpclient.SocketCommunicationException: Response was not received from MockServer after 20000 milliseconds, to wait longer please use "mockserver.maxSocketTimeout" system property or ConfigurationProperties.maxSocketTimeout(long milliseconds)
	at org.mockserver.httpclient.NettyHttpClient.sendRequest(NettyHttpClient.java:192)
	at org.mockserver.client.MockServerClient.sendRequest(MockServerClient.java:393)

Or perhaps I'm just doing something wrong?

**Comment by jamesdbloom** [comment]
Good catch, I'll fix that.
