### ISSUE TITLE
Its possible to proxy ssl?

### ISSUE THREAD

**Issue by Tankonyako** [mock-server/mockserver#1459]
It possible respond certificate from httprequest? not self-signed mock server

**Comment by jamesdbloom** [comment]
Yes, please see documentation: https://www.mock-server.com/mock_server/HTTPS_TLS.html

**Comment by Tankonyako** [comment]
can you give one example? i need forward ssl from ExpectationResponseCallback to output, it possible?

**Comment by Tankonyako** [comment]
when i connecting to proxy getting ssl error in browser because it trying to use mockserver self signed

**Comment by Tankonyako** [comment]
also i #1429 response about port, and it bugged when connecting from different types like socks and other

**Comment by jamesdbloom** [comment]
Your browser needs to trust the MockServer certificate, please see here: https://mock-server.com/mock_server/HTTPS_TLS.html#verify_trust_chain

**Comment by Tankonyako** [comment]
it possible make without this?
