### ISSUE TITLE
the content of chart package 5.14.0 on download list is not up to date

### ISSUE THREAD

**Issue by edaooo** [mock-server/mockserver#1523]
**Describe the issue**
the content of chart package 5.14.0 on download list is not up to date

**What you are trying to do**
Got ingress and helper issue as you fixed on history but not updated on package 5.14.0

**MockServer version**
5.14.0

**To Reproduce**
1. Download https://github.com/mock-server/mockserver/blob/master/helm/charts/mockserver-5.14.0.tgz
2. untar
3. Check ingress.yaml and compares to https://github.com/mock-server/mockserver/blob/master/helm/mockserver/templates/ingress.yaml

**Expected behaviour**
Should be the same content

**MockServer Log**
None. Chart render error.

**Comment by jamesdbloom** [comment]
The content of the chart 5.14.0 is the content when version 5.14.0 was released.  The chart changes do not get back ported so that is expected.

A new version will be released in the next week which will contain the new chart content.
