### ISSUE TITLE
Helm Install of 5.14.0 should take an array as an input for ingress path

### ISSUE THREAD

**Issue by cdestefano-777** [mock-server/mockserver#1564]
Hello, I am installing the most recent version of the helm charts (5.14.0). Currently, we are passing in the same variables as 5.13.2, but encountering the error: 

`Error: UPGRADE FAILED: template: mockserver/templates/ingress.yaml:33:28: executing "mockserver/templates/ingress.yaml" at <.Values.ingress.path>: can't evaluate field Values in type interface {}`

The paths should read or process an array rather than a string value for the value of path, which is throwing the above error.

**Comment by zifter** [comment]
Faced with the same.
Mistake is here: https://github.com/mock-server/mockserver/blob/mockserver-5.14.0/helm/mockserver/templates/ingress.yaml#L33
Fix described here:
https://stackoverflow.com/questions/56671452/helm-chart-error-cant-evaluate-field-values-in-type-interface

**Comment by zifter** [comment]
Fix is here: #1565

**Comment by pashchuk** [comment]
@zifter Thanks for the quick fix here.
Guys do you know when we can roll out a new version of helm chart?
