### ISSUE TITLE
Create Tar for 5.14.1

### ISSUE THREAD

**Issue by cdestefano-777** [mock-server/mockserver#1594]
**Describe the issue**
In `mockserver/helm/charts`, changes were pushed to 5.14.0 to upgrade to 5.14.1, which includes changes to the ingress. The most recent changes cannot be pull ed from the repository without the tar. 5.14.1 is not an available version for helm installation.

**MockServer version**
Installation of 5.14.1

**Comment by KerchumA222** [comment]
I would like this too. The new version contains a small change to runAsUser which is currently blocking some of my work.

**Comment by jamesdbloom** [comment]
ok this must have been released for that release or more like the tar wasn't pushed to S3 I'll take a look

**Comment by KerchumA222** [comment]
Any update on this? Anything I can help with?
