### ISSUE TITLE
How to use expectations with Mustache templates using REST API?

### ISSUE THREAD

**Issue by kichel98** [mock-server/mockserver#1743]
Hello,
I found information about templating responses in three ways in the documentation:
- mustache templates
- velocity templates
- javascript templates.

But in the definition of your REST API I see that `templateType` of `HttpTemplate` schema is an enum with only two values: `JAVASCRIPT` or `VELOCITY`.

I would like to use mustache template but I do not know how to do it when I use Mockserver with a Helm chart, not in Java code (I saw only that example in the docs). Could you provide an example how to create an expectation with mustache templates using REST API?

**Comment by hellojennpark** [comment]
`{
  "method": "GET",
  "path": "/user/profile",
  "queryStringParameters": {
    "userId": ["12345"]
  },
  "headers": {
    "Accept": ["application/json"]
  }
}
`


`{
  "httpResponseTemplate": {
    "templateType": "MUSTACHE",
    "template": "{ \"statusCode\": 200, \"body\": \"User ID: {{request.queryStringParameters.userId.0}} - Requested {{request.method}} on {{request.path}}\", \"headers\": { \"Content-Type\": [\"application/json\"] } }",
    "delay": {
      "timeUnit": "SECONDS",
      "value": 1
    }
  }
}
`
