### ISSUE TITLE
Docker image for Arm64/v8

### ISSUE THREAD

**Issue by ungrim97** [mock-server/mockserver#1787]
**Describe the feature request**
Provide a docker image that targets arm64/v8 architecture

**What you are trying to do**
Run a mockserver docker container on arm64 architecture

**The solution you'd like**
A docker image targeting arm64/v8

**Comment by GerMoranBYON** [comment]
Duplicate of https://github.com/mock-server/mockserver/pull/1665

**Comment by ungrim97** [comment]
@GerMoranOverstock Oops. So it is. Sorry for that

**Comment by GerMoranBYON** [comment]
@ungrim97 Just pointing it out as its not easy to find.
Unfortunately still awaiting for it to be reviewed 😿
