### ISSUE TITLE
How to get header response without name and values key ?

### ISSUE THREAD

**Issue by govindndr** [mock-server/mockserver#583]
Hi,

httpResponse = httpResponse
                    .withStatusCode(200).
                    .withHeaders(
                       "Content-Type", MediaType.APPLICATION_JSON),                       
                    )                 
                    .withBody("Hello")

For above request I get response as below. 
"statusCode" : 200,
  "headers" : [ {
    "name" : "Content-Type",
    "values" : [ "application/json" ]
  }
 ],
  "body" : "Hello"

Here header has name and values as keys.  But, how to get header simply as "Content-Type": "application/json"

**Comment by govindndr** [comment]
I have mock-server:mockserver-netty:3.10.2 and I use ExpectationCallback()

**Comment by jamesdbloom** [comment]
I'm not sure what you are asking?

I suggest you look at the documentation on the website at: http://mock-server.com/mock_server/getting_started.html

Also it seems you are using a very old version of MockServer the current version is: 5.5.1

**Comment by a459787545** [comment]
Hello, how can I solve this error?
<img width="1423" alt="2019-01-20 11 45 42" src="https://user-images.githubusercontent.com/16471580/51435044-e0ea1a00-1ca9-11e9-9c44-24c900316e87.png">

**Comment by govindndr** [comment]
Can I get response with this header format?
{
"Content-Type": "application/json"
}

Instead of 

"headers" : [ {
"name" : "Content-Type",
"values" : [ "application/json" ]
}
]
