### ISSUE TITLE
Unable to start docker image via go failed with executable file not found in $PATH

### ISSUE THREAD

**Issue by vikas-getconnect** [mock-server/mockserver#625]
When I am starting docker image via go. Seeing the following error  
2019/05/09 14:19:59 API error (400): {"message":"OCI runtime create failed: container_linux.go:344: starting container process caused \"exec: \\\"\\\": executable file not found in $PATH\": unknown"}

**Comment by jamesdbloom** [comment]
Can you give the command you are using of the go code you are using.

**Comment by lanwen** [comment]
Happens also using testcontainers lib v1.12 with 5.5.1 mockserver
Command in that case looks like this: `"-logLevel INFO -serverPort 1080"`

so maybe just old version of the container was used

**Comment by jamesdbloom** [comment]
That error is no MockServer error that is a docker error so I suspect there is something wrong with your testcontainers or docker setup.

@lanwen can you please provide more details about how you are running testcontainers.

**Comment by lanwen** [comment]
Definitely, that's not a Mockserver error, just docker image from 5.5.1 is incompatible with mockserver module of 1.12+ testcontainers. Posted here as a notice on what it could generally be. In my case just using latest mockserver fixing an issue

**Comment by jamesdbloom** [comment]
So does this work with the latest MockServer version 5.8.0?

**Comment by lanwen** [comment]
Didn't check with 5.8.0 but works with 5.7.0 for sure
