### ISSUE TITLE
Feature request: get Expectations by identifier

### ISSUE THREAD

**Issue by CC007** [mock-server/mockserver#629]
At the moment the `MockServerClient` allows you to get or clear a list of `Expectation`s by `HttpRequest`. This is good and all, but sometimes you want to be able to get or clear an `Expectation` by a unique name. 

Right now (to my knowledge) `Expectation`s aren't named yet, so it would be nice if it was possible to give an `Expectation` a name during creation, so that they could be retrieved with a new method something like `MockServerClient.getExpectation(String name)`

**Comment by jamesdbloom** [comment]
@CC007 can you please explain more about your use case so I understand why you need this and in what circumstances you would use it.

**Comment by CC007** [comment]
A usecase would be if you want to deploy a single mock server somewhere in your Enterprise testing environment. It would then be needed to service the following needs while multiple applications are using the mock server at the same time:

 - the ability to verify if all expectations for a certain application test suite have been met
 - the ability to clean up the expectations for a certain application test suite whenever an unexpected error occurs

I need to be able to do both these things while other application test suites can continue working without being disturbed.

**Comment by CC007** [comment]
Right now I am using the workaround of the expectation that "not a certain header is set to not a certain value" for instance: "not `testId` is not `<commitId>-<buildNr>`", but this is very hacky and requires that headers other than `testId` to never have that header value. It is very unlikely that I ever will need that value in the header, but it would be nice to not have such a weird exception.

**Comment by jamesdbloom** [comment]
@CC007 it is normal to use headers to support running tests in parallel as documented here: http://mock-server.com/mock_server/running_tests_in_parallel.html.

However, I have added support for expectations have an `id` field that can be used to update the expectation as part of a separate feature to support both persistence and a file watcher that updates the expectations when a JSON expectation initialised is modified.  Those features required `id` to ensure an efficient implementation.  I haven't yet exposed this in the client but I do intend on doing that is due course.  Currently (in the SNAPSHOT version) it is exposed via the HTTP API.

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/Ub200rQu/82-update-expectations-by-id-via-java-and-javascript-client
