### ISSUE TITLE
HTTP Client error in documentation for HttpClassCallback

### ISSUE THREAD

**Issue by DavyGarcon** [mock-server/mockserver#647]
Hi,

I'm using REST API to configure my mockserver instance, and for a callback use case i found  the usage of HttpClassCallback in swagger doc (https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.x.x), this object doesn't work for me.
But in the example (http://www.mock-server.com/mock_server/creating_expectations.html#button_response_class_callback), i found the usage of HttpResponseCallback, this last one works.
It's just a question of documentation update for me.

**Comment by jamesdbloom** [comment]
yes for example the following command works on my local machine:

```bash
java -Dmockserver.initializationJsonPath=/Users/jamesbloom/git/mockserver/mockserver/mockserver-core/src/test/resources/org/mockserver/server/initialize/initializerJson.json -jar ~/Downloads/remotecontent.jar -serverPort 1080 -logLevel INFO
```

I have also added an extra log output to make it clearer what expectations have been created by the file initialiser.

**Comment by jamesdbloom** [comment]
I'm not sure what you mean when you say `this object doesn't work for me` can you please explain what you are trying to do and what doesn't work?  Or please show me which lines in the documentation you feel are not clear.

**Comment by DavyGarcon** [comment]
Hi,

i tried to configure an Expectation with a Java Callback, my last try was  :

```JSON
{
	 "httpRequest":{
    "method" : "POST",
    "path" : "/my/path"    ,
    "body": {
            "type": "REGEX",
            "regex": "(.\r*\n*)*someKey(.\r*\n*)*someKey(.\r*\n*)*"
        }
  },

    "httpResponseClassCallback" : {
        "callbackClass" : "my.class.path.to.callback.Callback"
    }
}
```
I used **httpResponseClassCallback** object and this one works well. 
But my first try was like described on the [swagger doc](https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.2.x) and i used **httpClassCallback** like :

```JSON
{
	 "httpRequest":{
    "method" : "POST",
    "path" : "/my/path"    ,
    "body": {
            "type": "REGEX",
            "regex": "(.\r*\n*)*someKey(.\r*\n*)*someKey(.\r*\n*)*"
        }
  },

    "httpClassCallback" : {
        "callbackClass" : "my.class.path.to.callback.Callback"
    }
}
```

With this last one the mockserver instance return an error. I think it is an error in the swagger documentation, but maybe i missed something.

**Comment by jamesdbloom** [comment]
Thanks I’ll update the documents

**Comment by jamesdbloom** [comment]
I think you may be looking at an old version of the documentation.  What version of MockServer are you running?  The latest version 5.8.x of the swagger documentation is at: https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.8.x#/Expectation.  The link you added above is for version 5.2.x and that part of the API has changed.  Is there a link you followed that is out of date that I can update?
