### ISSUE TITLE
mockserver.proxyAuthenticationUsername not working

### ISSUE THREAD

**Issue by aturbati** [mock-server/mockserver#669]
Hello,
following the page http://www.mock-server.com/mock_server/configuration_properties.html I've tried to configure the mockserver to use the Authentication, but it seems to ignore such configuration.
I'm executing the mockserver via the console (I've tried both in Windows 10 ad in Linux Ubuntu) using the following command:
java -Dmockserver.proxyAuthenticationUsername=test -Dmockserver.proxyAuthenticationPassword=test -jar .\mockserver-netty-5.6.1-jar-with-dependencies.jar -serverPort 8012
I've also tried the "test" for the -Dmockserver.proxyAuthenticationPassword (as specified in http://www.mock-server.com/mock_server/configuration_properties.html , so using the quotation marks). Then I've tried via a configuration file:
java -Dmockserver.propertyFile=./mockserver.properties -jar mockserver-netty-5.6.1-jar-with-dependencies.jar -serverPort 8012
and in the configuration file I've placed:
mockserver.proxyAuthenticationUsername=test
mockserver.proxyAuthenticationPassword=test
But everytime the proxy was still accessible with wrong credentials or no credentials at all.
Am I doing something wrong? Is there anyone who was able to set the Authentication in 5.6.1 (or in any older version)?
Thank you

Andrea

**Comment by jamesdbloom** [comment]
I’ll take a look at this issue, this week

**Comment by jamesdbloom** [comment]
These properties are not designed to set the authentication details for onward proxies but instead to configure MockServer HTTP CONNECT requests to require authentication.

I have however added additional properties that allow you to set username and password for onward / forward proxies, these settings are:
```java
mockserver.forwardProxyAuthenticationUsername
mockserver.forwardProxyAuthenticationPassword
```

**Comment by jamesdbloom** [comment]
I have now updated the documentation as well.  This is now available in the SNAPSHOT version: http://mock-server.com/where/maven_central.html#sonatype_snapshot and will be released in the next few weeks.  Only once this is released will the documentation be updated.
