### ISSUE TITLE
ProxyPass implementation

### ISSUE THREAD

**Issue by astachowiak** [mock-server/mockserver#679]
In my integration test I need to support proxypass functionality of apache httpd. This means that the application cannot simply use forward() as I need:
- proxy to a remove server (HTTPS) - forward as is now
- replace HOST header to match the remote host - callback class on request 
- replace domain in cookies coming from the remote hose - callback class on response

At this moment it seems that one can use either forward() which forwards query as is to a remove host. Or modify the request but then the query will be done to the local host. And there is no way to modify the response before sending it to client.

I would like to ask to add such feature if possible.

**Comment by jamesdbloom** [comment]
So if I understand you correctly when a request is modified using `HttpOverrideForwardedRequest` (i.e. `forwardOverriddenRequest()`) then you would like the response to also be modified, for example in the case where a `Location` header is returned for a redirect?

**Comment by jamesdbloom** [comment]
If you can provide some HTTP request and response examples of exactly what is missing that would be helpful so I can fully understand what you would need.

**Comment by jamesdbloom** [comment]
It is now possible to override response objects using http://mock-server.com/mock_server/creating_expectations.html#button_forward_overridden.  However, I do agree that more simple proxy pass style funtionality (as per apache) could be helpful.  I've created an item on the backlog for this so I am going to close this ticket as backlog items (i.e. new feature) are tracked in Trello so they can be easy prioritised, see: https://trello.com/c/2IjJ5e27/67-apache-style-simple-proxypass-functionality
