### ISSUE TITLE
Load the default mocks configuration from chart config

### ISSUE THREAD

**Issue by mykola-mokhnach** [mock-server/mockserver#687]
Hello,

First I would like to say thanks for your hard work @jamesdbloom . The project you are working on is very useful and helpful.

I have a question/suggestion. We would like to deploy mock server as a part of our project's helm chart. Currently the only way to configure mocks (at least the one we figured out so far) is to perform REST API requests. This requires either a shell script or a client code to be executed after the mock server pod started. 
What we would like to be able to provide is the initial mocks configuration directly in helm chart as a part of values.yaml (let say it could have the same content as an expectation initialisation JSON file). Something very similar to `initializationFiles` parameter described in https://github.com/helm/charts/tree/master/stable/mysql. Is such approach possible with mockserver or it needs to be implemented first?

**Comment by jamesdbloom** [comment]
I'll look into it and get back to you in the next couple of days.  In theory, it should be possible to mount a file into the container and provide either a system property or a properties file to tell MockServer to use the mounted file to pre-initialize with specific expectations.  I'm happy to try this and give you an example or put this into the existing helm in a simpler way and document it on the website.

**Comment by jamesdbloom** [comment]
This isn't easy with helm due to limitations in what is allowed for security reasons and the fact that work on helm 2 has pretty much stopped while they focus on helm 3.  However, I am going to try if I can get this to work by sharing config between heml charts.  Then I can add an example of how to do this if I can get it to work.  I'll update in the next few days.

**Comment by jamesdbloom** [comment]
This is now completed the documentation will be updated as part of the next release in a week or so.
