### ISSUE TITLE
In Java api a thread with connection to remote MockServer impossible to close without stopping remote server

### ISSUE THREAD

**Issue by evgenym87** [mock-server/mockserver#697]
I'm using Java API to connect MockServer at docker container, and after I set an expectation by "when" method of MockServerClient class the thread with opened session continues to exist unlimited time.
The thread is possible to close just after the call close or stop method, which close not just thread, but stop the docker container with MockServer.
I think it becouse API was firstly created for localhost running.
Is it possible to close MockServerClient thread without stopping remote MockServer, like in WireMock?

**Comment by jamesdbloom** [comment]
Yes, the MockServerClient shouldn't keep any threads open once the response is received.  I'll take a look and see what is going on.

**Comment by jamesdbloom** [comment]
This should now be resolved in the SNAPSHOT version, this fix will be in the next release which will be in the next few weeks.
