### ISSUE TITLE
Charset not parsed from valid Content-Type header

### ISSUE THREAD

**Issue by DDebray** [mock-server/mockserver#698]
Currently the content type is parsed by the class ContentTypeMapper incorrectly. It only is able to parse the charset when its not followed by additional parameters. This is allowed according to the RFC.

https://tools.ietf.org/html/rfc7231#section-3.1.1.1
>media-type = type "/" subtype *( OWS ";" OWS parameter )
>     type       = token
>     subtype    = token
>
>   The type/subtype MAY be followed by parameters in the form of
>   name=value pairs.
>
>  parameter      = token "=" ( token / quoted-string )

One example would be 

`application/soap+xml;charset=UTF-8;action="somerandomstuff"`

**Comment by jamesdbloom** [comment]
I have now fixed this, which is available in the latest SNAPSHOT version.  I will do a new release in the next few weeks which will contain this fix.

**Comment by DDebray** [comment]
well done, this is far superior to my PR :). I left a comment on the commit regarding the whitespace handling.
