### ISSUE TITLE
No support or at least documentation for starting a http, non ssl, server.

### ISSUE THREAD

**Issue by codeofnode** [mock-server/mockserver#704]
For some reason, i want to start a plain http server. (non-tls)
I have spent over an hour on documentation and code as well, i couldn't find that how its possible.

In the properties file, there is no option to disable SSL.

Whenever i make request, a plain http non ssl, it responds with 400 saying
"400 The plain HTTP request was sent to HTTPS port"

Any solution or is there anything i might be missing?

**Comment by jamesdbloom** [comment]
Are you sure the request your sending is going to MockServer because that is not an error that MockServer would return?

Can you please attach the log output from MockServer.

**Comment by jamesdbloom** [comment]
The MockServer works with both HTTP and HTTPS on the same port as it dynamically detects if the request being sent is encrypted with TLS or not therefore there is no configuration required.  All 2,000 MockServer integration tests run against both HTTP and HTTPS.

**Comment by codeofnode** [comment]
Hey @jamesdbloom Sorry for late reply.
Well i had moved to different mock server. :-| And forgot to capture the logs.

But in nutshell what i was doing is. mock-server was being used behind a load balancer (just a proxy in k8 cluster) which was terminating the SSL. So yes i was making a https request from real client (curl) but mock-server should have received plain http request. (since SSL was being terminated at load balancer and load balancer) and load balancer would be making plain http call to mock server.

I guess this much info should be sufficient to reproduce the scenario.

**Comment by jamesdbloom** [comment]
So it sounds like there is an issue with MockServer so I am going to close this issue.  Did you use the MockServer helm chart?

**Comment by codeofnode** [comment]
Yes, i used helm chart to delpoy mock-server in cluster.
