### ISSUE TITLE
日志不能重定向到文件里，只能打印到控制台

### ISSUE THREAD

**Issue by zhaotingwen** [mock-server/mockserver#712]
**Describe the issue**
Description of the issue

**What you are trying to do**
Description of what you are trying to do so we can understand the context of the problem

**MockServer version**
The version you are using (i.e. 5.7.2)

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc)
2. Code you used to create expectations
3. What error you saw

**Expected behaviour**
What you expected to happen

**MockServer Log**
Log output, as INFO level (or lower)

**Comment by zhaotingwen** [comment]
配置这个java.util.logging.config.file后，没有效果

**Comment by jamesdbloom** [comment]
Can you please your issue in English?

**Comment by zhaotingwen** [comment]
Describe the issue
Logs cannot be redirected to a file, only printed to the console.

What you are trying to do
![image](https://user-images.githubusercontent.com/13743627/72117542-168b8580-3389-11ea-8c43-85111cdee895.png)


MockServer version
The version you are using 5.8.1

To Reproduce
Steps to reproduce the issue:

How you are running MockServer (i.e maven plugin, docker, etc)
The log information cannot be redirected to the file, how to use it to solve this problem.

MockServer Log
INFO

**Comment by jamesdbloom** [comment]
MockServer providing the following system properties
```bash
-Dmockserver.logLevel=INFO
-Djava.util.logging.config.file=<correct path>/example_logging_configuration.properties
``` 
to configure the logging, as decribed on http://mock-server.com/mock_server/debugging_issues.html.

I have just confirmed that is working correctly.

If this is not happening for you, please double-check the location of the logging configuration file and also make sure you looking in the correct location for the log file.  Note that `%h` as in the current example configuration writes the log file into your home directory.  I will update the configuration to remove this as it is confusing.

The current example logging configuration is as follows:

```properties
# To use this file set System Property on JVM as follows: -Djava.util.logging.config.file=/path/to/example_logging_configuration.properties

# Logging
handlers = java.util.logging.FileHandler, org.mockserver.logging.StandardOutConsoleHandler
.level = ALL
org.mockserver.level = DEBUG
io.netty.handler.ssl.SslHandler.level = WARNING
java.util.logging.SimpleFormatter.format = %1$tF %1$tT  %4$s  %5$s %n

# File Logging
java.util.logging.FileHandler.pattern = %h/mockserver.log
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.FileHandler.level = INFO

# Console Logging
org.mockserver.logging.StandardOutConsoleHandler.level = ALL
org.mockserver.logging.StandardOutConsoleHandler.formatter = java.util.logging.SimpleFormatter
```

This logs to a file called `mockserver.log` in your home directory.

It may be easier to log to a file called `mockserver.log` in your working / current directory, to that use the following configuration instead:

```properties
# To use this file set System Property on JVM as follows: -Djava.util.logging.config.file=/path/to/example_logging_configuration.properties

# Logging
handlers = java.util.logging.FileHandler, org.mockserver.logging.StandardOutConsoleHandler
.level = ALL
org.mockserver.level = DEBUG
io.netty.handler.ssl.SslHandler.level = WARNING
java.util.logging.SimpleFormatter.format = %1$tF %1$tT  %4$s  %5$s %n

# File Logging
java.util.logging.FileHandler.pattern = mockserver.log
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.FileHandler.limit=50000
java.util.logging.FileHandler.count=5
java.util.logging.FileHandler.level = INFO

# Console Logging
org.mockserver.logging.StandardOutConsoleHandler.level = ALL
org.mockserver.logging.StandardOutConsoleHandler.formatter = java.util.logging.SimpleFormatter
```

I will update the example to this new configuration to ensure no one is confused by the log file going into the home directory.
