### ISSUE TITLE
Have a way to control the order of expectation during matching process

### ISSUE THREAD

**Issue by scierniak** [mock-server/mockserver#719]
**Describe the feature request**
We can dynamically add new expectations with is great, but new expectations are always added at the end of the list and so used at the end during matching process. So the feature should allows to control the order of expectations during matching process. 

**What you are trying to do**
Basically there are 2 cases:
- if an expectation is heavily consumed (Dominant), I want it to be matched asap. It will improve the performance of matching process
- if an expectation is too generic (use as default response, if no specific response found), I want it to be matched as last as possible to try to match all specific cases before

**The solution you'd like**
As part of expectation object, we need an additional key to allow sorting like:
- "rank" with int values 0 to 99   => 0 being matched first and 99 being matched last
- "frequency" with predefined values: high, medium, low, default

then during matching process we need to use expectations sorted using the new key

Also improve the retrieve active expectations service to be able to display them sorted or not.

**Describe alternatives you've considered**
The only workaround is to load my expectations from a file when starting. The file contains expectations in expected order but if some extra expectations are added dynamically the order is not correct anymore

**Comment by jamesdbloom** [comment]
I agree with this feature and it will get implemented fairly soon.  It is the next highest priority feature in the next release.  The current release only has a small number of documentation updates to do before it is released.  Once it is released this item will be picked up as it was already in the backlog: https://trello.com/c/9G3Hkdu3/31-default-expectation-expectation-priority

**Comment by jamesdbloom** [comment]
New feature requests are now prioritised on Trello, so closing issue in GitHub as it has been accepted onto the new feature backlog.  Only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog priority can be more effectively managed, see: https://trello.com/c/9G3Hkdu3/31-default-expectation-or-expectation-priority

**Comment by jamesdbloom** [comment]
I have now added support for expectation priority which can be used to change the matching order or expectations.  Now matching priority is considered first before the creation order. This means a default expectation can be created at any time by creating a new higher priority expectation that is guaranteed to be matched first (if its priority is higher then all other expectations)
