### ISSUE TITLE
JavaDoc for deprecated client ExpectationInitializer interface points to wrong replacement interface

### ISSUE THREAD

**Issue by cmgrote** [mock-server/mockserver#720]
**Describe the issue**
The JavaDoc for the deprecated `org.mockserver.client.initialize.ExpectationInitializer` interface (in v5.9.0) currently suggests to instead use the interface `org.mockserver.client.initialize.ClientExpectationInitializer`, which does not exist.  Instead, it appears that the `org.mockserver.client.initialize.PluginExpectationInitializer` should be used.

**What you are trying to do**
Updating an existing pre-v5.9.0 class that implemented the now-deprecated `org.mockserver.client.initialize.ExpectationInitializer` interface in order to initialize expectations via the maven plugin.

**MockServer version**
5.9.0

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer: maven plugin
2. Code you used to create expectations: my own class that implements `org.mockserver.client.initialize.ExpectationInitializer`
3. What error you saw: ExpectationInitializer is now deprecated, and then tests failed (because no expectations were actually initialized as a result of the deprecation).

**Expected behaviour**
I would firstly expect that as this is the first release in which the interface is deprecated that it will still work without a code change, but would simply generate warnings that it was deprecated; however, in lieu of that I referred to the JavaDocs to look for any replacement logic to implement instead.  I would then expect that the JavaDoc would refer to the appropriate replacement interface that should be implemented, but it currently points to a non-existent interface.

**MockServer Log**
N/A

**Comment by jamesdbloom** [comment]
Thanks for detailed bug reports, I have now updated the documentation to point to the correct location.

The intention was to make this backwards compatible but because the change was across multiple repositories this was missed.  I can make it backwards compatible for the next release for what it is worth.  I will leave this ticket open until that is done.

**Comment by jamesdbloom** [comment]
This is now completed and on the SNAPSHOT version the final commit was in the maven plugin project https://github.com/mock-server/mockserver-maven-plugin/commit/75f6ce6487484871ab904fddcb8184f99ff6052f
