### ISSUE TITLE
Browser client link is not working

### ISSUE THREAD

**Issue by bulkan** [mock-server/mockserver#724]
**Describe the issue**
The browser client link referenced here and in the documentation does not work anymore

**What you are trying to do**
Load browser client

**MockServer version**
5.9.0

**To Reproduce**
Steps to reproduce the issue:

1. Go  to this link https://rawgit.com/mock-server/mockserver-client-node/mockserver-5.9.0/mockServerClient.js
2. Should exist

**Comment by jamesdbloom** [comment]
Thank I'll update it to https://raw.githubusercontent.com/mock-server/mockserver-client-node/mockserver-5.9.0/mockServerClient.js

**Comment by jamesdbloom** [comment]
This is now fixed in the repo and readme and will be deployed to the website later.
