### ISSUE TITLE
File watcher is incorrectly initialized for files in the current directory

### ISSUE THREAD

**Issue by cutedavyjones** [mock-server/mockserver#727]
**Describe the issue**
When initialization file is in the current directory, and initialization json path contains only the name of the file, file watcher is failing with NullPointerException. Expectations are initialized correctly.

**What you are trying to do**
Using mockserver standalone for mocking.

**MockServer version**
5.9.0

**To Reproduce**
Steps to reproduce the issue:

1. MacOS
2. Mockserver standalone 
3. Create file init.json next to the mockserver jar.
4. Command like 
```
java -Dmockserver.watchInitializationJson=true \
-Dmockserver.initializationJsonPath=init.json \
-jar mockserver.jar -serverPort 9090 -logLevel INFO
```

**Expected behaviour**
File watcher is created and works correctly.

**MockServer Log**
Error
```
java.lang.NullPointerException
	at org.mockserver.persistence.FileWatcher.<init>(FileWatcher.java:20)
	at org.mockserver.persistence.ExpectationFileWatcher.<init>(ExpectationFileWatcher.java:32)
	at org.mockserver.mock.HttpStateHandler.<init>(HttpStateHandler.java:84)
	at org.mockserver.lifecycle.LifeCycle.<init>(LifeCycle.java:47)
	at org.mockserver.netty.MockServer.<init>(MockServer.java:49)
	at org.mockserver.netty.MockServer.<init>(MockServer.java:40)
	at org.mockserver.cli.Main.main(Main.java:97)
```

**Workaround**
Specify full path to json without any aliases, for example 
```
-Dmockserver.initializationJsonPath=/Users/user/mockserver/init.json
``` 
**Fix**
Should be an easy fix in https://github.com/mock-server/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/persistence/FileWatcher.java 
line 16
from 
`Path directoryPath = Paths.get(filePath);`
to
`Path directoryPath = Paths.get(filePath).toAbsolutePath();`

**Comment by jamesdbloom** [comment]
This is likely caused because the underlying Java FileWatcher expects a directory and MockServer hasn't allowed for a file path to a file in the current directory.  It should be fairly easy to fix, which I'll do in the next week or so.

**Comment by jamesdbloom** [comment]
this is now fixed and is in the lastest SNAPSHOT version
