### ISSUE TITLE
Add support for XMLUnit placeholders

### ISSUE THREAD

**Issue by gyurist** [mock-server/mockserver#728]
**Describe the feature request**
XMLUnit introduced support for placeholders in version 2.6.0, adding support for these could be a great addition to the `XmlStringMatcher`: https://github.com/xmlunit/user-guide/wiki/Placeholders
This however would leak the implementation detail in of using XMLUnit behind the scenes which might not be desirable at all.

**What you are trying to do**
I'm trying to match XML request and responses with dynamic data which is harder to mock, in my particular case timestamps. I'm trying to implement unit tests for a legacy system which leans heavily on XQuery and I'd like to avoid modifying the implementation until I have some high-level unit tests available. 

**The solution you'd like**
I'd like to be able to mark certain elements and values in the XML body ignorable when creating expectations.

**Describe alternatives you've considered**
XPath would not provide the desired coverage in my case and using regex is not feasible either. Placeholders have proven to be quite useful before, JsonUnit has a similar feature as well: https://github.com/lukas-krecan/JsonUnit#ignoring-values
I've found the previous discussion about using `retrieveRecordedRequests()` and that could be a possible but a bit more involved solution in my case.

**Comment by jamesdbloom** [comment]
I am already using XmlUnit so I'm just going to test it, but this may already work.  Have you tried it yet?

**Comment by jamesdbloom** [comment]
I've now fixed the XML matcher so it supports placeholders and added several tests to confirm that.
