### ISSUE TITLE
Proxy for epicgames (and more) 40 minues after launch

### ISSUE THREAD

**Issue by comtihon** [mock-server/mockserver#729]
**Describe the issue**
We started the service to test webhook from external system, so it is available from the outside.
After 40 minutes of runtime we discovered we have hundreds of request from  proxy.ru pointing to epicgames, facebook, clinicadeazeitao and other websites.

If it is not the intent, I guess you should carefully check the server's and libraries code.

**Comment by jamesdbloom** [comment]
Can you please provide more context.  There is no code in MockServer that would make such requests, therefore I suspect either your own code or some other scanning software was hitting the MockServer.

**Comment by comtihon** [comment]
I haven't added my code. It is either an external scanning software or something inside Mockserver, which registers itself as a proxy.
What information do you need from us?

**Comment by jamesdbloom** [comment]
There is nothing inside MockServer that registers itself anywhere.  So it must be scanning software.  Please feel free to search the code base for those domain names, you won't find any references to them at all.  

I'm just wanting more information so I can help to make suggestions as to why you may be seeing that traffic.  

How did you deploy MockServer?
Where did you deploy it?
Did someone configure the OS to point to MockServer as a proxy?
