### ISSUE TITLE
Json Validation does not accept "null" as valid json

### ISSUE THREAD

**Issue by saadkalim-earnin** [mock-server/mockserver#731]
**Describe the issue**
When the json "null" is sent in the request body, an exception is thrown in `org.mockserver.matchers.JsonStringMatcher#matches`
`org.json.JSONException: Unparsable JSON string: null`.

This means I am unable to match an expectation when the body is the json "null".

I think the problem is in the JSONAssert library
https://github.com/skyscreamer/JSONassert/issues/83

**What you are trying to do**
Set up an expectation in mock server with "null" as the body, content type json.
Try to match this expectation by making a request to mock server with "null" as the body. The content type should be json.

**MockServer version**
5.9.1-SNAPSHOT

**To Reproduce**
Steps to reproduce the issue:

1. Set up an expectation in mock server with "null" as the body, content type json.
2. Try to match this expectation by making a request to mock server with "null" as the body. The content type should be json.
`org.json.JSONException: Unparsable JSON string: null` at `org.mockserver.matchers.JsonStringMatcher#matches`

**Expected behaviour**
"null" should be allowed as valid json, as discussed here https://stackoverflow.com/questions/8526995/is-null-valid-json-4-bytes-nothing-else.

**MockServer Log**
```
2020-02-19 11:45:09  org.mockserver.log.MockServerEventLog  FINE  failed to perform json match

	null

 with

	null

 because

	Unparsable JSON string: null
```

**Comment by jamesdbloom** [comment]
This has now been fixed as I have replaced JSONassert with JsonUnit as per #738

**Comment by JavierSegoviaCordoba** [comment]
@jamesdbloom is it possible to disable Json validation?
