### ISSUE TITLE
Support ordered interactions and verification.

### ISSUE THREAD

**Issue by DominicCliftonNEKTAN** [mock-server/mockserver#74]
When two systems interact they often need to perform a set sequence of interactions where the order of these interactions is critical, for example:

get balance
withdraw money
get balance

when testing interactions we need to know the interactions happened in the correct order.  the following sequences highlight this and should not allow the test to pass since the result would be incorrect.

withdraw money
get balance
get balance

or

get balance
get balance
withdraw money

Any assertion should show which requests were out of order.

e.g.

expected: 
get balance
withdraw money
get balance

was:
get balance
get balance
withdraw money

**Comment by vaibhav13** [comment]
Does the ordered verification support is present for ruby client as well ?

**Comment by 3791** [comment]
Unfortunately this is not currently support in the ruby client.

I am intending on completely re-writing the ruby client, at which point I'll add all features including verification and verificationSequences, port binding and method / object callbacks.
