### ISSUE TITLE
[Question] How to setup default proxy, overriding responses for specific paths

### ISSUE THREAD

**Issue by agoldis** [mock-server/mockserver#740]
This is a follow-up question after resolving #739 

I am trying to use `mockserver` as proxy for all requests to a cloud service. 
A particular test would define custom expectations to prevent certain requests from going to the cloud server and return pre-defined response instead.

I was able to achieve proxying all the requests by creating a "catchall" expectation:

```typescript
await client.mockAnyResponse({
    httpRequest: {
      path: '.*',
    },
    httpOverrideForwardedRequest: {
      httpRequest: {
        headers: {
          Host: "cloud-service.com",
        },
        secure: true,
      },
    },
  });
```

However, adding a new expectation for specific path from a test doesn't have any effect. I guess that's because "catchAll" expectation is applied first. 

What am I missing here?

**Comment by jamesdbloom** [comment]
MockServer will match (or play) active expectations in the exact order they are added (if their priority is identical). For example, if an expectation A is added with Times.exactly(3) then expectation B is added with Times.exactly(2) with the same request matcher they will be applied in the following order A, A, A, B, B.

However, priority can be used to alter the order that expectations are matched; matching is ordered by priority (highest first) then creation (earliest first).

Priority can be used to configure a default expectation or response by specifying a negative value for priority and a very lax request matcher; the lax request matcher ensures the default expectation is always matched, but the low priority ensure it is matched last after all other expectations.

Therefore to have a default expectation either:
1. add it last
1. add it at any point but ensure all subsequent expectations have a higher priority (for example by setting the default priority to a negative value)

See: https://mock-server.com/mock_server/creating_expectations.html#button_match_request_by_negative_priority
