### ISSUE TITLE
HTTPS proxy server error: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by zippolyte** [mock-server/mockserver#744]
**Describe the issue**
Using the proxy server to record HTTPS requests, I get the following exception with any java version > 8.

```
javax.ws.rs.ProcessingException: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

Note that it works fine with java 8.

I did configure the HttpsUrlConnection with the MockServer SSL socket factory with the following, as per the documentation.
```java
HttpsURLConnection.setDefaultSSLSocketFactory(
                    new KeyStoreFactory(new MockServerLogger()).sslContext().getSocketFactory()
            );
```

**MockServer version**
`5.9.0`

**To Reproduce**
Steps to reproduce the issue:

1. Start the mock server proxy
2. Make an HTTPS through the mock server proxy
3. See the exception above

**Investigations and workaround**
After enabling `javax.net.debug=all`, I noticed one thing when java loads the trust stores:
in java 8: 
```
javax.net.ssl|DEBUG|22|MockServer-MockServer-workerEventLoop2|2020-03-16 12:24:09.840 CET|TrustStoreManager.java:113|trustStore is: /Users/hippolytehenry/Datadog/datadog-api-client-java/mockserver_keystorejks
trustStore type is: jks
```
in java > 8
```
javax.net.ssl|DEBUG|22|MockServer-MockServer-workerEventLoop2|2020-03-16 12:24:09.840 CET|TrustStoreManager.java:113|trustStore is: /Users/hippolytehenry/Datadog/datadog-api-client-java/mockserver_keystorepkcs12
trustStore type is: pkcs12
```

So then I tried the keystore type to `jks` right before setting the mockserver SSL socket factory like so
```java
java.security.Security.setProperty("keystore.type", "jks");
HttpsURLConnection.setDefaultSSLSocketFactory(
                    new KeyStoreFactory(new MockServerLogger()).sslContext().getSocketFactory()
            );
```

Surprise, the issue was gone !!!

I'm thinking there might be a bug with the certificate generation, not taking into account the proper trust store type and generating `jks` all the time.

Hope this helps !
Cheers

**Comment by jamesdbloom** [comment]
I'll look into this in the next few days

**Comment by jamesdbloom** [comment]
I have now fixed this and is in the latest SNAPSHOT version, I am also about to do a new RELEASE which will contain this fix.
