### ISSUE TITLE
about performance problem

### ISSUE THREAD

**Issue by yanguoqiang** [mock-server/mockserver#748]
I use mock-server in performance tests, but the performance is slower more and more, I find there are frequent gc.

The version I are using is 5.5.1

I'm use JMeter for performance testing

I run MockServer using 
```
nohup java -Dfile.encoding=UTF-8 -jar mockserver-netty-jar-with-dependencies.jar -serverPort 8888 -logLevel DEBUG &
```
2. Code you used to create expectations
```bash
curl -v -X PUT "http://localhost:8888/mockserver/expectation" -d '{
    "httpRequest": {
        "path": "/ddptest/wechat/getOpenid"
    },
    "httpResponseTemplate": {
        "template": "return { statusCode: 200,headers: { \"content-type\": [\"application/json;charset=UTF-8\" ] },  body: JSON.stringify({state:\"ok\",time:\"2020-02-1915:52:53\",data:{id:\"84ec5f732bad48d68d51c2b27889b445\",accessToken:\"30__qOODNgKFf5kY-sdDsqiDFbBPwmOxWjnKZklNwmCdwmEu-AeuXJxVu-Dm8_uxwV72iWq0WPrj3TpTurKHaq3GZkmmQRs3H8uvwO4Mejuoqg\",accessTokenDate:\"2020-02-19T07:52:53.564+0000\",expiresIn:\"7200\",refreshToken:\"30_LlzfTv8ulZrMWPsLEuGfmv86r8d3pNASg0buuklX9a4HtDt-qaVY0smVDgYDhvYShpi7K3toyx2rp0eu5rqPRgNCWrM4xjBzAOwCZSapHPM\",openid:Math.random().toString(36).substr(-25,25).concat(\"xxx\"),scope:\"snsapi_userinfo\",unionid:Math.random().toString(36).substr(-25,25).concat(\"xxx\"),appid:request.body[\"string\"].match(\"appid.:.([^\\\"]+)\")[1]}})};",
        "templateType": "JAVASCRIPT"
    }
}'
```

the request body is 
```json
{"code":"123","state":"ok","appid":"wx25a3492ce30895a1"}
```
3. What error you saw
there is no error, just the performance is low

**Comment by jamesdbloom** [comment]
Can you please use a more recent version of MockServer and try again.  The current version is: 5.9.0

**Comment by yanguoqiang** [comment]
OK， I try again using 5.9.0.
Is there a suggestion for -Xms and -Xmx.
There is a gc.txt for running
[gc.txt](https://github.com/mock-server/mockserver/files/4362438/gc.txt)

**Comment by yanguoqiang** [comment]
oh...
There are something wrong when I using 5.9.0. I create a creating expectation:
```
    "httpRequest": {
        "path": "/ddptest/wechat/getOpenid"
    },
    "httpResponseTemplate": {
        "template": "return { statusCode: 200,headers: { \"content-type\": [\"application/json;charset=UTF-8\" ] },  body: JSON.stringify({state:\"ok\",time:\"2020-02-1915:52:53\",data:{id:\"84ec5f732bad48d68d51c2b27889b445\",accessToken:\"30__qOODNgKFf5kY-sdDsqiDFbBPwmOxWjnKZklNwmCdwmEu-AeuXJxVu-Dm8_uxwV72iWq0WPrj3TpTurKHaq3GZkmmQRs3H8uvwO4Mejuoqg\",accessTokenDate:\"2020-02-19T07:52:53.564+0000\",expiresIn:\"7200\",refreshToken:\"30_LlzfTv8ulZrMWPsLEuGfmv86r8d3pNASg0buuklX9a4HtDt-qaVY0smVDgYDhvYShpi7K3toyx2rp0eu5rqPRgNCWrM4xjBzAOwCZSapHPM\",openid:Math.random().toString(36).substr(-25,25).concat(\"xxx\"),scope:\"snsapi_userinfo\",unionid:Math.random().toString(36).substr(-25,25).concat(\"xxx\"),appid:request.body[\"string\"].match(\"appid.:.([^\\\"]+)\")[1]}})};",
        "templateType": "JAVASCRIPT"
    }
```
，but when I post this request , there is error:
`Caused by: <eval>:3 TypeError: Cannot read property "match" from undefined`
Is there no support for "match"？
PS: the expectation is good for version 5.5.1，and I use "match" for get value of “appid” which in requets body

**Comment by jamesdbloom** [comment]
The error you are seeing is an error in your JavaScript code.  MockServer is using the JVM to execute JavaScript.  I will take a look when I get a chance to see if I can spot where the error is.

**Comment by yanguoqiang** [comment]
> The error you are seeing is an error in your JavaScript code. MockServer is using the JVM to execute JavaScript. I will take a look when I get a chance to see if I can spot where the error is.

thanks your reply。
I have known the reason for that error，My JavaScript code is right，there is `appid:request.body[\"string\"].match(\"appid.:.([^\\\"]+)\")[1]` in version 5.5.1，but it should be `appid:request.body[\"json\"].match(\"appid.:.([^\\\"]+)\")[1]`  in version 5.9.0， but I don't know why.
One more thing, I want to know，if I want to know how many ways to achieve extracting some field in  `request.body` , you see my example，I use the Regular expression to extract "appid" in `request.body`. And I see your website, "class callback" also maybe can achieve the target, but I don't know how to use(I don’t understand your example code), Can your show me more example？

PS：Is there a sample way to extract field in  `request.body` ， for example: `appid:request.body[\"json\"][\"appid\"]` , I think this way is very simple and easy to understand.


I hava tested performance using version 5.9.0, there is a obviously improvement using version 5.9.0.
![5 9 0](https://user-images.githubusercontent.com/41641177/77412067-5692ce00-6df8-11ea-9297-b551fff4fdeb.png)

Think you very much.

**Comment by jamesdbloom** [comment]
@yanguoqiang the names of the fields must have changed between version 5.5.1 and 5.9.0 from 'string' to 'json'.

Instead of using a class callback I would suggest using a method / closure callback, see: https://mock-server.com/mock_server/creating_expectations.html#button_response_method_or_closure_callback.  The method / closure callback allows you to write a method that is called when a request is received and you programmatically create the response.  This means it is easy to extract any fields you need from the request.

If you want to extract the fields in a json string you can use `JSON.parse(...)` as follows:

```javascript
JSON.parse("{ \"foo\": \"bar\" }").foo
```

This returns:

```javascript
"bar"
```

Finally, if you want good performance I wouldn't recommend using a javascript template because I would suspect that is not efficient.  Instead, I would suggest using a method / closure callback, see: https://mock-server.com/mock_server/creating_expectations.html#button_response_method_or_closure_callback

I'm going to close this issue because there is no defect.  If you have more questions please raise them via Slack questions channel: https://join-mock-server-slack.herokuapp.com/

**Comment by yanguoqiang** [comment]
OK，Think your for your reply，Good Job！
