### ISSUE TITLE
Allow to temporarily persist a value and get it back later

### ISSUE THREAD

**Issue by pilhuhn** [mock-server/mockserver#749]
**Describe the feature request**

Sometimes one wants to first store a value in a remote server (that is to be mocked) and then later retrieve it again. In testing this is done to test if the store operation really worked.
It would be good if there were a way to add to a put/post expectation to say "store data" and then later in a get expectation to be able to retrieve that value again.
The writer of the expectation would in both cases give a unique way ("primary key") to identify the data to be stored.

**What you are trying to do**

Create expectations that mock real remote servers, that are able to retrieve values that were previously stored into that remote server

**The solution you'd like**

See above. Internally I'd say this could be a Map<pk,data>.

**Comment by jamesdbloom** [comment]
This is already possible by creating an expectation within another expectation, as shown in this code example: https://mock-server.com/mock_server/creating_expectations.html#button_response_create_expecation_within_closure_callbackp.

This is the typical way this is solved but it is also possible to use class callbacks: https://mock-server.com/mock_server/creating_expectations.html#button_response_class_callback
