### ISSUE TITLE
add SBT to documentation

### ISSUE THREAD

**Issue by satyagraha** [mock-server/mockserver#753]
Hi, I've been using SBT, the Scala build tool, and I have a few tips on how to use it with MockServer. How is the HTML documentation managed? Do you use a particular HTML editor? Would the normal PR submission process work?

**Comment by jamesdbloom** [comment]
Yes, a normal PR submission process would work.  Jekyll is the framework used for the documentation.  It would be great to have SBT added to the documentation, perhaps a separate page called `Using SBT` would be the easiest way to add additional content.  I plan to add such a page on Gradle as well.

**Comment by jamesdbloom** [comment]
Do you need any additional information to write this?

**Comment by jamesdbloom** [comment]
Closing due to lack of information / activity
