### ISSUE TITLE
Password protection on expectation endpoint

### ISSUE THREAD

**Issue by davidwestonuk2000** [mock-server/mockserver#757]
We are using mockserver heavily in our development environment want to restrict who can reset the expectations on the instances through password protection or similar

I was looking at the config options and found this; can this or any other config be used to protect the /expectation endpoint?

-jvmOptions "-DmoproxyAuthenticationUsername=xxxxx -DproxyAuthenticationPassword='xxxxx'"

Thanks

**Comment by jamesdbloom** [comment]
That existing feature does not support expectations.

How ever there is a feature in the backlog already to add this support. I’m happy to raise its priority https://trello.com/c/5AncVp5r

I’m going to close this issue now as this new feature is already on the backlog but I’ll update this issue when there is progress on that backlog item (likely that will be released in 1/2 months)
