### ISSUE TITLE
Calling setDefaultStyle alters global state

### ISSUE THREAD

**Issue by mattnelson** [mock-server/mockserver#759]
**Describe the issue**
mockserver is changing the default toString style for the entire JVM.

https://github.com/mock-server/mockserver/blob/756758ebe3d032f3852411a9bb91c3c66d819ddc/mockserver-core/src/main/java/org/mockserver/model/ObjectWithReflectiveEqualsHashCodeToString.java#L15-L17

**What you are trying to do**
Trying to use mockserver and assert toString in the same JVM.

**MockServer version**
5.10.0

**To Reproduce**
Steps to reproduce the issue:

1. run junit test that uses mockserver (which alters the global state)
2. run junit test that is asserting toString style based on the default style from commons-lang3
3. toString assertion fails

**Expected behaviour**
mockserver does not alter global state.

**MockServer Log**
not applicable

**Comment by jamesdbloom** [comment]
this is now fixed in the SNAPSHOT version
