### ISSUE TITLE
withQueryStringParameters and withHeader are conflicted

### ISSUE THREAD

**Issue by keremcankabadayi** [mock-server/mockserver#761]
**Describe the issue**
I created two different expectations but only one difference is header param.

**What you are trying to do**
Here my trying to do.
Mock1 expectation:
```
{
    "id": "6c167094-a177-491a-9d9e-d3f6236e75d7",
    "httpRequest": {
      "method": "GET",
      "path": "/product",
      "queryStringParameters": {
        "relatedParty[0].id": [
          ".*"
        ],
        "status": [
          ".*"
        ]
      }
    },
    "httpResponseObjectCallback": {
      "clientId": "b7fedb88-58a9-4d4c-8cb4-c627af231cc0"
    },
    "times": {
      "unlimited": true
    },
    "timeToLive": {
      "unlimited": true
    }
  }
```
Mock2 expectation:

```
{
    "id": "636a1b4f-0208-46a8-bee7-d413736db8c9",
    "httpRequest": {
      "method": "GET",
      "path": "/product",
      "queryStringParameters": {
        "relatedParty[0].id": [
          ".*"
        ],
        "status": [
          ".*"
        ]
      },
      "headers": {
        "X-Kerem": [
          "meLikeHeaders"
        ]
      }
    },
    "httpResponseObjectCallback": {
      "clientId": "05251c05-66c1-4b8f-ac93-91718bc72b7d"
    },
    "times": {
      "unlimited": true
    },
    "timeToLive": {
      "unlimited": true
    }
  }
```

I'm getting first mock response for both expectations.
**MockServer version**
5.9.0

**To Reproduce**
Steps to reproduce the issue:

1. Java, maven
2. I shared above my both expectation with `http://localhost:4000/mockserver/retrieve?type=ACTIVE_EXPECTATIONS`
3. No error I got.

**Expected behaviour**
I expect header param to make difference than the other expectation.

**Comment by jamesdbloom** [comment]
MockServer returns the first matching expectation so if you specify the expectation without the header value first that will always be matched.  Can you confirm the order you have specified the expectations?
