### ISSUE TITLE
the length of dashboard page's static resources in header set wrong

### ISSUE THREAD

**Issue by DarrenLuo** [mock-server/mockserver#766]
**Describe the issue**
i use custom index page instead the default dashboard page, but some css and js file only load part

**What you are trying to do**
1. i delete the setting of the length in header, it work well
2. i change the method for getlength, it work well

**MockServer version**
5.10.0

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc)
2. Code you used to create expectations
3. What error you saw

**Expected behaviour**
What you expected to happen

**MockServer Log**
Log output, as INFO level (or lower)

**Comment by DarrenLuo** [comment]
#765 resolves this

**Comment by jamesdbloom** [comment]
fixed by merged PR
