### ISSUE TITLE
Add spring test module to facilitate Spring Tests with random MockServer port

### ISSUE THREAD

**Issue by masooh** [mock-server/mockserver#767]
**Describe the feature request**
Add an extra spring test module which provides a `@MockServerTest` annotation which  starts MockServer for each test instance and resets it after each test method.
The MockServer is started with a random port which also can be used to customize test properties: 
`@MockServerTest('client.serviceUrl=http://localhost:${mockServerPort}/')`

**What you are trying to do**
Context: Spring / Spring Boot
Use Case: You write a test for a client to a remote service. The client is a Spring Bean which is configured via properties. You want to replace the remote service with MockServer. As multiple tests may run on the CI server the MockServer should use a  random free port.

**The solution you'd like**
I have already implemented the feature in our company as follows: The comments in `spring.factories` explain it best:

```
# Starts the MockServer with the mockserverPort property in the environment and resets it after test methods
org.springframework.test.context.TestExecutionListener=test.mockserver.MockServerTestExecutionListener

# adds a context customizer which replaces ${mockserverPort} placeholder of the @MockServer annotation and ads it as test property
org.springframework.test.context.ContextCustomizerFactory=test.mockserver.MockServerTestCustomizerFactory
```

Usage:
`MyClient` connects to the property `myClient.remoteServiceUrl`. The remote service is mocked. 
`MockServerClient` is filled by `MockServerTestExecutionListener`.

```java
@MockServerTest('myClient.remoteServiceUrl=http://localhost:${mockServerPort}/')
@WebMvcTest
class ClientIT extends Specification {

    @Inject
    MyClient myClient

    MockServerClient mockServerClient
}
```

**Describe alternatives you've considered**

First TestPropertySource
```
@TestPropertySource(properties = ["myClient.remoteServiceUrl=http://localhost:4711"])
```
This works, but the port is fixed and may conflict with other ports on the server. If multiple tests with MockServer are running, the given ports must be managed.

**Questions**
Does this fit into this project? If yes where should it be located?

**Other**
As I have already implemented the feature I can provide a PR if it fits and all questions are discussed.

**Comment by leonard84** [comment]
Any chance we can get feedback for this, either positive or negative?

**Comment by jamesdbloom** [comment]
give me a couple of days as I'm working through adding Open API and Swagger support, then I'll respond I just want to have a little time to think properly about the implementation / ramifications, in principle it sounds like it makes sense though.

**Comment by jamesdbloom** [comment]
I'm happy to add a module for this to the project.  To speed up development can you please provide the code you have already created for:

- test.mockserver.MockServerPortPostProcessor
- test.mockserver.MockServerTestExecutionListener
- test.mockserver.MockServerTestCustomizerFactory

Then I can incorporate the same approach and ensure that it uses the best technique from MockServer and is fully covered with automated tests.

**Comment by masooh** [comment]
Sure, I will provide an PR in the next days.

**Comment by masooh** [comment]
Tests are missing, I try to provide them next week.

**Comment by masooh** [comment]
@jamesdbloom Tests are now present as well. PR is ready for review.

**Comment by masooh** [comment]
I suppose the documentation and examples module should be updated as well. I can do this later if the code is not likely to change any more.

Is the documentation really in HTML directly (`jekyll-www.mock-server.com`) or generated by Markdown/Asciidoc?

**Comment by jamesdbloom** [comment]
Yes the documentation uses Jekyll because generating by Markdown or Asciidoc is too limiting and restrictive and is therefore not possible to create a good quality site with good SEO that doesn't look like many other identical sites.

**Comment by jamesdbloom** [comment]
If you provide documentation here in markdown I'm happy to convert the documentation into Jekyll to avoid you have understand the exact implementation and macros, etc used in Jeykll.

**Comment by masooh** [comment]
@jamesdbloom Documentation added and PR is now ready for review.

**Comment by asarkar** [comment]
I came across this PR looking for something similar to [AutoConfigureWireMock](https://github.com/spring-cloud/spring-cloud-contract/tree/master/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock) provided by Spring Cloud. IMO, usage `@MockServerTest('myClient.remoteServiceUrl=http://localhost:${mockServerPort}/')` is repeating what `SpringBootTest.properties` attribute already does. There are close to a dozen ways to define external properties in Spring Boot, and no need to invent a new way really.

**Comment by masooh** [comment]
@jamesdbloom Thank you for integrating this feature.

**Comment by masooh** [comment]
@asarkar It's correct that there are other ways, but I think it's a common use case and therefore I wanted to have the option to add properties with this annotation. Nevertheless it was not necessary to implement this behavior. I have replaced it now with a delegate to `@TestPropertySource`. What do you think about it?

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@TestPropertySource
@Inherited
public @interface MockServerTest {

    @AliasFor(annotation = TestPropertySource.class, attribute = "properties")
    String[] value() default {""};
}
```

Complete change: https://github.com/masooh/mockserver/commit/4bc88eca581913beb1a113206f6a45500c74de85

**Comment by asarkar** [comment]
Hi @masooh
Let me first state what I believe to be the problems you are trying to solve:
1. Provide a way to _automatically start/stop_ mockserver with the test lifecycle.
2. _Make HTTP + HTTPS ports available as Spring Boot environment properties_.
3. Allow user to _specify ports_, or indicate that they want to use random ports.
4. Allow user to specify properties _not necessary to start mockserver_ for testing at compile time.

For 1, the recommended way to would be to use [SmartLifecycle](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/SmartLifecycle.html).

2 needs to happen before 1 if using `SmartLifecycle` is used, and can be done in an `ApplicationListener` that listens to `ApplicationPreparedEvent`. It finds free ports, if necessary, and adds a `PropertySource`.

3 can be achieved by an annotation `AutoConfigureMockServer` with a `port` attribute; `0` would mean random port. There may also be a need to support custom SSL configuration, but I don't see that in your code, so assuming that's not a feature you want to support for now.

4 is already supported by Spring Boot by presence of `application[-profile].properties`, or by the `properties` attribute available on `@SpringBootTest` annotation, and unless I'm missing something, is not a concern for mockserver.

IMO, you can pretty much lift much of the `AutoConfigureWireMock` implementation for 1 and 2. I've a [cassandra-unit-spring](https://github.com/asarkar/cassandra-unit-spring) that manages a Cassandra server start/stop for testing built similarly, except for a `SmartLifecycle`, for reasons that are not relevant to this discussion.

**Comment by asarkar** [comment]
I created [mockserver-spring](https://github.com/asarkar/mockserver-spring) that starts a `MockServer` and makes the port available as Spring Boot environment property. Stops the server when the Spring context is destroyed. I maintain other such projects that helps with Spring integration tests, so it joins the club.

**Comment by adanilev** [comment]
@masooh, would you expect this to work with junit 5 and `@SpringBootTest`? I have been trying with no success. I see the TestExecutionListener get registered but mockserver doesn't start (even though `mockServerPort` is defined).

**Comment by membersound** [comment]
At least it would make most sense if that supports junit jupiter and `@SpringBootTest`.

**Comment by leonard84** [comment]
@adanilev did you also annotate it with `@MockServerTest` ?

See this [example](https://github.com/mock-server/mockserver/blob/master/mockserver-spring-test-listener/src/test/java/org/mockserver/springtest/integration/MockServerTestExecutionListenerIntegrationTest.java).

**Comment by jamesdbloom** [comment]
Closing as implemented and no more activity

**Comment by membersound** [comment]
@jamesdbloom and what is actually the solution to the initial question topic?

**Comment by jamesdbloom** [comment]
@membersound I believe that has been provided by the merged PRs on this topic.
