### ISSUE TITLE
Initialize MockServer from OpenApi (Swagger) Schema

### ISSUE THREAD

**Issue by msnookxom** [mock-server/mockserver#768]
**Describe the feature request**

Is it possible to initialize the MockServer using an OpenAPI (Swagger) file?

**What you are trying to do**

Trying to initialize the Mock Server using an OpenAPI (Swagger) `json` file.

**The solution you'd like**

Can an OpenAPI (Swagger) `json` file be used as an Expectation Initializer?

**Describe alternatives you've considered**

N/A

**Comment by jamesdbloom** [comment]
This is now implemented and will be released in the next couple of days, also this issue is a duplicate of #550.
