### ISSUE TITLE
Make it easier to use ExpectationInitializer with docker

### ISSUE THREAD

**Issue by leozilla** [mock-server/mockserver#770]
**Describe the feature request**
Currently it is quite cumbersome to use an `ExpectationInitializer` when running mockserver in docker. (In my case I was running it with helm on k8s)
As far as I understand (and what worked for me) the `ExpectationInitializer` must be in its own jar file and this must be added to the classpath.
Unfortunately the existing entrypoint script is not prepared the include both the mockserver jar and other jars in the classpath which basically forces you to either mount a different entry point script or better yet create your own docker image.

**The solution you'd like**
I have no specific solution yet in mind, I rather want to discuss it.
Ideally I would say it should be possible to just mount the new jar(s) into the container at a predefined point, lets say `/opt/mockserver/ext` and also prepare the `run_mockserver.sh` to always include that folder in the classpath.
This way you would not be required to build your own docker image.

**Describe alternatives you've considered**
My current alternative is building my own docker image like this:

```
FROM mockserver/mockserver:mockserver-5.10.0

ADD target/secupay-expectations-*.jar /opt/mockserver/lib/
ADD run_mockserver.sh /opt/mockserver/run_mockserver.sh

WORKDIR /opt/mockserver

EXPOSE 1080

USER mockserver

ENTRYPOINT ["/opt/mockserver/run_mockserver.sh"]

CMD ["-logLevel", "INFO", "-serverPort", "1080"]
```

And adjusting the `run_mockserver.sh` to also load my jars.

```
MAIN_CLASS="org.mockserver.cli.Main"
CLASSPATH="/opt/mockserver/mockserver-netty-jar-with-dependencies.jar:/opt/mockserver/lib/*:."

runCommand "java -cp ${CLASSPATH} ${JVM_OPTIONS} -Dfile.encoding=UTF-8 ${MAIN_CLASS} ${COMMAND_LINE_OPTS} &"
```

This also allowed me to add additional dependencies to my jar which I needed in my expectation handlers.

**Comment by jamesdbloom** [comment]
I agree your suggestion makes sense, I'll see if I can implement this just before pushing out the new release in the next day or two.

**Comment by jamesdbloom** [comment]
I think supporting a predefined volume in the docker container sounds like the easiest way to solve your problem and would work for local docker and docker inside kubernetes.

**Comment by jamesdbloom** [comment]
I have a working solution now which will be part of the next release in the next few days, I'll add documentation to explain how to use it but it should be as simple as the follow:

**Given:**
- a sub directory (in your current directory) called `libs` containing jars and
- a sub directory (in your current directory) called `config` containing `mockserver.properties`
- `mockserver.properties` refers to other configuration inside the `config` with the path `/config`

**Then:**
```bash
docker run -v $(pwd)/libs:/libs -v $(pwd)/config:/config -p 1080:1080 mockserver/mockserver -serverPort 1080 -logLevel FINE
```

This will run MockServer will all the jars in the `libs` directory in the classpath and will load properties in the `mockserver.properties` file.  These properties can in turn refer to other files such as a JSON expectation initialiser file, etc inside the config directory.

This should work easily for vanilla docker or for kubernetes with configmaps.

**Comment by jamesdbloom** [comment]
closing as documentation is now complete release should happen tomorrow
