### ISSUE TITLE
generated TLS certficate excludes wildcard domains

### ISSUE THREAD

**Issue by rkuk** [mock-server/mockserver#771]
**Describe the issue**
I set a list of domains, including wildcard domains, to `sslSubjectAlternativeNameDomains` in  property file. But when I inspect the certificate generated, it shows that the certficate only includes non-wildcard domains. All the wildcard domains are discarded.

**What you are trying to do**
I want the TLS certificate generated by mockserver to include wildcard domains. So I set  `sslSubjectAlternativeNameDomains` in  property file. It shows that the certificate is generated successfully, but it only includes the non-wildcard domains which I set to `sslSubjectAlternativeNameDomains`. All the wildcard domains I set are discarded.

**MockServer version**
The version you are using (5.10.0)

**To Reproduce**
1. create mockserver.properties file in the working directory.
2. set `mockserver.sslSubjectAlternativeNameDomains=abc.com,*.abc.com` in mockserver.properties file.
3. run mockserver on localhost:1080 and visit https://localhost:1080/mockserver/dashboard in chrome.
4. inspect the certificate from chrome and see "abc.com" is in the SAN, but "*.abc.com" is not.
5. try to replace `*.abc.com` with `\*.abc.com` or `\\*.abc.com` in mockserver.properties file
6. restart mockserver and see "*.abc.com"  is still not included in the certificate.

**Others**
1. How you are running MockServer (i.e maven plugin, docker, etc)
I run MockServer in node.js via `mockserver-node` package.

2. Code you used to create expectations
none

3. What error you saw
I set the log level to ERROR, but no error message shows.

**Expected behaviour**
I want the wildcard domains set to `sslSubjectAlternativeNameDomains` in property file will be included in the certificate generated.

**MockServer Log**
log level is INFO, output is:
04:22:30	retrieving active expectations in json that match:"":{}
04:22:30	started on port: 1080

**Comment by jamesdbloom** [comment]
this is now fixed and will be in the SNAPSHOT version later today, the next RELEASE will be in a few weeks once a couple of features have been completed
