### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by ischoe** [mock-server/mockserver#773]
**Describe the issue**
I am running mockserver as a proxy + mock server with standalone java app. The Kubernetes pod has 4GB. It seems when running the pod, already 1 GB is used .When running around 20 selenium tests with three expectations added, the used memory is already doubled. And after the tests finished the memory is used. It seems to be used forever.

**What you are trying to do**
I started the jar with xmx/xms params

**MockServer version**
5.10.0

**MockServer Log**
OFF

**Comment by joyarzun** [comment]
I'm running performance tests in my app using mock-server to mock a legacy system. Services are running on K8S and mock has a 3s delay. After running the tests some times successfully at some point mock-server throw an error "java.lang.OutOfMemoryError: GC overhead limit exceeded". I think this is related to memory issues.

MockServer version
5.10.0

**Comment by svenhaag** [comment]
Same problem here in plain old Windows console via Maven:

```
mockServer.when(
                request()
                        .withMethod("POST")
                        .withPath("/service/endpoint")
                        .withQueryStringParameter("email", "foo@bar.com")
                        .withQueryStringParameter("test", "foo"))
                 .error(HttpError.error().withResponseBytes("b00m".getBytes()));
                // this works fine:
                //.respond(response().withStatusCode(500).withBody("b00m".getBytes()));

service.callEndpoint("foo@bar.com", "foo");
```
The JAVA process quickly maxes out at ~480MB. The test eventually ends after an eternity. There are no CPU resources spend.

**Comment by ndhilliprasad** [comment]
I am not an expert..one cent from my side. Try switching to G1GC (JDK 8 default to Parallel GC)

**Comment by jamesdbloom** [comment]
To reduce the amount of memory please set the maximum number of expectations as follows: https://mock-server.com/mock_server/configuration_properties.html#button_configuration_max_expectations

This will ensure both the number of expectations and the number of recorded logs don't get too large.  Alternatively, you could reduce the maximum number of recorded logs https://mock-server.com/mock_server/configuration_properties.html#button_configuration_request_log_size or the log level https://mock-server.com/mock_server/configuration_properties.html#button_configuration_log_level.

Reducing the default value for these will significantly reduce memory usage.

In addition, I. am working on. a change to dynamically modify the maximum expectation and logs based on the amount of available memory.

**Comment by jamesdbloom** [comment]
In addition, I have updated the docker container to Java 11 which honours any memory constraints for the container (Java 8 and below looked at the host settings not the container settings).  Please retest with the latest SNAPSHOT version (docker tag: mockserver-snapshot).

**Comment by jamesdbloom** [comment]
@svenhaag you issue looks like a totally unrelated problem.  Why do you think it has anything to do with this?

**Comment by jamesdbloom** [comment]
@svenhaag if you specify an error in the way you have only those bytes are returned and therefore the client will likely hang as it doesn't understand the bytes and know that the response has completed.  To improve your test use the `withDropConnection(true)` field of error.  However, I imagine Error is not what you need unless you're attempting to test how your HTTP client parses random byte strings.

I'm closing this issue as all items resolved.  If you still feel there is a memory problem with the latest SNAPSHOT version (or the existing version once it has been configured to control the amount of memory used as above) please raise an additional issue or comment here and I'll re-open.
