### ISSUE TITLE
/replace endpoint

### ISSUE THREAD

**Issue by pedrorfernandes** [mock-server/mockserver#774]
**Describe the feature request**
If we have an `Expectation` to a specific `HttpRequest` and wish to replace it with a new one, we must first call `PUT /clear` and then `PUT /expectation`, which gives a small time window where no `Expectation` is set.

An alternative to this is to use `timeToLive` and `times` parameters in a `/expectation` request. 2 equal `HttpRequest`'s with different expectations can exist, and the second will come into action when the first expires.

However, consider my scenario: using mock-server as a browser proxy for selenium automation testing in a web app. The app might fire a request to the real service during the delay between `/clear` and `/expectation`. There is no difference between the `HttpRequest`'s since it's a periodic polling to the same endpoint, and we want to test that if the endpoint starts responding with different data, the app reacts to that. Allowing the real endpoint to be called must be avoided since it might set the app into a catch error state (we also want to test that in a different scenario).

Also, using `timeToLive` is not ideal, since we want the test to go as fast as possible, and `times` is uncertain since the app might fire a certain number of requests depending on implementation details which are subject to change. To bypass this issue, we mocked the browser's time to prevent HTTP requests firing while the new `Expectation` is being set. But a `/replace` endpoint would avoid this workaround.

**What you are trying to do**
Avoid the downtime between API calls (time period with no expectations) when trying to replace a `HttpRequest` during a `PUT /clear` and `PUT /expectation`

**The solution you'd like**
Create a new endpoint `PUT /replace` which combines the functionality of `PUT /clear` + `PUT /expectation`

**Describe alternatives you've considered**
Did not think of a better alternative other than a single endpoint as of yet. Maybe a transactional endpoint with all the operations we want to execute in a single request? But that is overkill for this simple issue and would require a lot more changes.

If this solution is agreeable, I can try to implement it

**Comment by jamesdbloom** [comment]
I agree this makes sense and I have already implement a part of the solution.  If you know the `id` of the expectation that already exists and submit a new expectation with the same `id` it will do a replace of the existing expectation.  This is used as part of another solution but does work on the API.  The work needs to be finished off to document this and make sure the client code, etc handles this approach with good user experience.  Shortly I'll add this feature request to the backlog.

**Comment by pedrorfernandes** [comment]
Tested it out in the latest version and it seems to work as expected

However, is it possible to modify the HTTP response of `/expectation` to the created `Expectation` object? This way we can store the ID and thus avoid an extra request to `/retrieve?type=ACTIVE_EXPECTATIONS`

**Comment by jamesdbloom** [comment]
This is now done so the latest SNAPSHOT version returns the expectation that was upserted from '/expectation'

**Comment by jamesdbloom** [comment]
This is now implemented closing issue
