### ISSUE TITLE
Dead Link for Documentation

### ISSUE THREAD

**Issue by ben-nathanson** [mock-server/mockserver#775]
**Describe the issue**
The Swaggerhub docs for version 5.10 are linked to but not found. When I go to the page SwaggerHub responds with `Sorry, we can't find jamesdbloom / mock-server-openapi / 5.10.x `

**What you are trying to do**
Read the documentation for 5.10. 

**MockServer version**
5.10

**To Reproduce**
Steps to reproduce the issue:
[Click here](https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.10.x)

**Comment by jamesdbloom** [comment]
This is now fixed the API wasn't published by mistake.
