### ISSUE TITLE
How can we set the range of delay (500 milliseconds to 800 milliseconds) in the rest API mocks?

### ISSUE THREAD

**Issue by Sandy1526** [mock-server/mockserver#776]
How can we set the range of delay (500 milliseconds to 800 milliseconds) in the rest API mocks?

Currently, it is like below. 

> 

"delay" : 
{
"timeUnit": "MILLISECONDS"
"value": 500
}

**Comment by jamesdbloom** [comment]
Current a range of delay is not supported, although this could potentially be added.  Can you provide more information about your use case?

**Comment by jamesdbloom** [comment]
Closing due to lack of information / activity
