### ISSUE TITLE
Fail to configure custom CA certificate using steps configured in https://mock-server.com/mock_server/HTTPS_TLS.html#button_configuration_ssl_certificate_domain_name

### ISSUE THREAD

**Issue by vaibhavpatil123** [mock-server/mockserver#784]
**Describe the issue**
Fail to configure SSL on mock server using steps 
https://mock-server.com/mock_server/HTTPS_TLS.html#button_configuration_ssl_certificate_domain_name
Description of the issue
Fail to configure SSL on mock server using steps 
https://mock-server.com/mock_server/HTTPS_TLS.html#button_configuration_ssl_certificate_domain_name
**What you are trying to do**
Description of what you are trying to do so we can understand the context of the problem

**MockServer version**
The version you are using (i.e. 5.7.2)

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc)
2. Code you used to create expectations
3. What error you saw

**Expected behaviour**
What you expected to happen

**MockServer Log**
Log output, as INFO level (or lower)

**Comment by vaibhavpatil123** [comment]
https://github.com/mock-server/mockserver/blob/6936dd02718f066e890e62ded751e169b80f3f86/docker/run_mockserver.sh how to pass SSL config params using docker command line ?

**Comment by jamesdbloom** [comment]
See: https://mock-server.com/where/docker.html#docker_detailed_configuration
