### ISSUE TITLE
Dynamic mock responses using velocity templates & REST API

### ISSUE THREAD

**Issue by ndhilliprasad** [mock-server/mockserver#788]
**Describe the feature request**
Building dynamic mock responses using velocity templates & REST API

**What you are trying to do**
In most of the cases mock responses needs to be little dynamic. Let's say if you want to mock employee REST service for CRUD operations you may need to generated dynamic employee id (random uuid or integer), employee joining date etc. With current velocity templates and expectations REST API it is hard to generate dynamic response content. If we can add velocity template variable(s) predefined or customizable which can give random integer, uuid, current date with specified format will which help to build dynamic response.

**The solution you'd like**
Add a new velocity template variable dynamicContent along with request, Which will be an object of Java class DynamicContent (or something with better name) with all the supporting methods for random uuid, int and current date with specified date format.

**Comment by jamesdbloom** [comment]
Velocity templates is only one of four current ways to create dynamic response:

- Closure Callback https://mock-server.com/mock_server/creating_expectations.html#button_response_method_or_closure_callback
- JavaScript Template https://mock-server.com/mock_server/creating_expectations.html#button_javascript_templated_response
- Velocity Template https://mock-server.com/mock_server/creating_expectations.html#button_javascript_velocity_templated_response
- Class Callback https://mock-server.com/mock_server/creating_expectations.html#button_response_class_callback

Can you please explain why the other three methods don't work easily to do what you're trying to do?

**Comment by jamesdbloom** [comment]
Velocity template are only one of four ways to create dynamic responses:

- Closure Callback https://mock-server.com/mock_server/creating_expectations.html#button_response_method_or_closure_callback
- JavaScript Template https://mock-server.com/mock_server/creating_expectations.html#button_javascript_templated_response
- Velocity Template https://mock-server.com/mock_server/creating_expectations.html#button_javascript_velocity_templated_response
- Class Callback https://mock-server.com/mock_server/creating_expectations.html#button_response_class_callback
Is there a reason why one of these approach does not work in your scenario?

Can you please explain why one of the other three approaches does not work in your scenario.
