### ISSUE TITLE
Allow materialisation of responses while proxying to static text / json responses

### ISSUE THREAD

**Issue by voycey** [mock-server/mockserver#789]
**Describe the feature request**
Allow materialisation of responses from proxying to static responses - e.g. saving the responses as human readable files (e.g: json) - to allow manipulation allowing us to return a static payload.

**What you are trying to do**
We are dealing with a service that is very intermittent, to the point of us not being able to even populate the mocks. It would be useful to be able to run through the service and populate all of the mocks and then materialise these mocks to JSON to be served and manipulated. 

**The solution you'd like**
This might exist in some form already: Either an option to open the .content files or a switch to allow it to generate text / json responses that we can then use to create responses.

**Describe alternatives you've considered**
We are currently trying to archive the responses when services are up but it is difficult.

**Comment by jamesdbloom** [comment]
I think what you need already exists see: https://mock-server.com/mock_server/debugging_issues.html#retrieving_recorded_expectations

This feature allows you to use the MockServer as a proxy to record interactions with another service and then create them as expectations.

Can you please confirm if this existing feature meeting your requirements?

**Comment by jamesdbloom** [comment]
I'm going to close this issue as I believe what you need is covered by the feature described in the previous comment, if this is not case please let me know and I can re-open this issue or discuss further.

**Comment by voycey** [comment]
Hi James, 

We worked out that the .content files are json.gz files so have been working off that :)

Thanks
