### ISSUE TITLE
Capture url parameters in path and use them in path of forwarded request

### ISSUE THREAD

**Issue by Alterant-zz** [mock-server/mockserver#790]
**Describe the feature request**
Add possibility to use url parameters in path and insert them in path of forwarded request.

**What you are trying to do**
My application makes two consecutive requests to the external API. First creating entry with PUT (where id of created resource is provided), second - retrieving this entry with GET by provided id.

Expectation for the first request works perfectly.

But for the second request to work I need to make an expectation with regex like this:
```
{
    "httpRequest": {
        "method": "GET",
        "path": "/extserver/backlog/.*"
    },
   "httpOverrideForwardedRequest": {
        "httpRequest": {
            "method": "GET",
            "path": "/1.0/backlog/????????",
            "headers": {
                "Host": [
                    "otpravka-api.pochta.ru"
                ]
            },
            "secure": true,
            "socketAddress": {
                "host": "otpravka-api.pochta.ru",
                "port": 443,
                "scheme": "HTTPS"
            }
        }
    }
}
```
In the request matching path I have to use regular expression "/extserver/backlog/.*" as request will contain the resource id like this: "/extserver/backlog/12345".
And I need to forward this request to path like this: "/1.0/backlog/12345". But it is not possible to capture request path params and place them in forwarded request's path.

**The solution you'd like**
It would be great if we could use regex capturing groups (numbered or named - it does not matter) in request's path like this: "path": "/extserver/backlog/(.*)" and use captured values in forwarded request's path like this: "path": "/1.0/backlog/:1".

**Comment by jamesdbloom** [comment]
I've added support for path variables so this is now possible using an object or class callback.  In the future I will extend the support to allow named variable in the path.

The changes so far are in the SNAPSHOT release.

**Comment by Alterant-zz** [comment]
@jamesdbloom Thanks! I tried to figureout how can I use it inspecting your commits to UT and IT. But with no luck. It would be of a great help if you could show how can I setup expectation via REST applied to my example above?

**Comment by jamesdbloom** [comment]
It is not currently possible to use values from the matched request in the httpOverrideForwardedRequest however I agree it makes sense to support that.

This new feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/zNESeUnr/122-template-request-properties-in-httpoverrideforwardedrequest

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by frecco75** [comment]
Is it currently possible to use values from the matched request in the response body ?
For example if we call a /carts/{cartId} and want to have a cart object containing the given id 

```
{
  "id": {cartId}
   "items": [...]
}
```

**Comment by nbraun-wolf** [comment]
@frecco75 this isn't working for me. I just get "id": {cartId} as that in the response. No value substitution.

**Comment by jb69** [comment]
@jamesdbloom I see this was moved to next release, was there any code that has this feature in it or a planned release date. cheers and great work

**Comment by AnakinPt** [comment]
+1 for @frecco75 proposal. I want to use mockserver to simulate external services and I don't want to mock all values, because some of them come in the query parameters or in the path paramenters.

**Comment by jamesdbloom** [comment]
This has now been fixed in is being released which will be ready in the next few hours

**Comment by fuxinhao-crypto** [comment]
may I ask if it's been released? can I use the path variables in response template?

**Comment by jamesdbloom** [comment]
@fuxinhao-crypto  yes see the documentation here: https://mock-server.com/mock_server/response_templates.html#request_model_variables

**Comment by codeprimed** [comment]
Hi - is this feature supported for JSON responses?  I would like to refer to a path variables in my canned json response. Thanks.
