### ISSUE TITLE
retrieve logs doesn't show milliseconds in timestamp of request and response

### ISSUE THREAD

**Issue by garashis** [mock-server/mockserver#796]
Retrieve logs doesn't show milliseconds in timestamp of request and response.
Its important in some occasions to know the exact timestamp of request/response e.g. understand the reasons for caller getting timeout as response from mock-server is not received within expected time. This will give clear clue where is the delay or time lost, is it mock-server or the poor network.

**Comment by jamesdbloom** [comment]
this is now fixed and will be in the latest SNAPSHOT later today
