### ISSUE TITLE
Interprete json and xml content as utf8 by default if no charset is defined

### ISSUE THREAD

**Issue by Chr3is** [mock-server/mockserver#797]
Spring deprecated the APPLICATION_JSON_UTF8 MediaType because Chrome comply with the specification now https://bugs.chromium.org/p/chromium/issues/detail?id=438464.

Tests currently fail if a client posts utf8 encoded content to the client without defining the charset with `;charset=utf8` due to a body missmatch (the mockserver does not interprete the content as utf8 by default).

We should comply with the RFC as well. Everything (content-type `application/*+json` or `application/*+xml`) coming from a client should be interpreted as utf8 by deafult if no charset is given:

JSON: https://tools.ietf.org/html/rfc8259#section-8.1
XML: https://tools.ietf.org/html/rfc3470#section-5.1

**Comment by jamesdbloom** [comment]
this is now done and will be in the SNAPSHOT version shortly
