### ISSUE TITLE
Simplify stubbing and verification

### ISSUE THREAD

**Issue by leonard84** [mock-server/mockserver#805]
## Describe the feature request
Currently, we have to repeat the request twice if we want to stub and then verify an interaction.

```java
mockserver.when(
        request()
            .withMethod("POST")
            .withPath("/login")
            .withBody("{username: 'foo', password: 'bar'}")
    )
    .respond(
        response()
            .withStatusCode(302)
            .withCookie(
                "sessionId", "2By8LOhBmaW5nZXJwcmludCIlMDAzMW"
            )
            .withHeader(
                "Location", "https://www.mock-server.com"
            )
    )

mockserver.verify(
         request()
            .withMethod("POST")
            .withPath("/login")
            .withBody("{username: 'foo', password: 'bar'}"),
        VerificationTimes.atLeast(2)
    )

```

## What you are trying to do
I would like to be able to define the stubbing and verification in one go.

## The solution you'd like
I could think of two ways.

### First

Assigning an `id` to the request that will be used later
```java
mockserver.when(
        request()
            .withMethod("POST")
            .withPath("/login")
            .withBody("{username: 'foo', password: 'bar'}")
            .verifyId("login")
    )
    .respond(
        response()
            .withStatusCode(302)
            .withCookie(
                "sessionId", "2By8LOhBmaW5nZXJwcmludCIlMDAzMW"
            )
            .withHeader(
                "Location", "https://www.mock-server.com"
            )
    )
```

To verify you simple refer to the request by id.
```java
mockserver.verify(
        requestId("login"),
        VerificationTimes.atLeast(2)
    )
```
### Second
Allow the combined `when` and `verifyLater` which sets up the verification but defers its evaluation until later.

```java
mockserver.when(
        request()
            .withMethod("POST")
            .withPath("/login")
            .withBody("{username: 'foo', password: 'bar'}")
    )
    .verifyLater(VerificationTimes.atLeast(2))
    .respond(
        response()
            .withStatusCode(302)
            .withCookie(
                "sessionId", "2By8LOhBmaW5nZXJwcmludCIlMDAzMW"
            )
            .withHeader(
                "Location", "https://www.mock-server.com"
            )
    )
```

Later you call `verifyAll()` delayed verifications.
```java
mockserver.verifyAll()
```

## Final Thoughts
The method names and positions are just suggestions the important thing is to make the test code more DRY without having to add helper functions to extract the request definitions.

**Comment by masooh** [comment]
Would be a good improvement.

I would prefer the first solution. In my opinion the mock should not be customized to the test, it should try to simulate the real system. The only reason for me is to modify interaction times is if I want to reflect that the responses change in order.

**Comment by jamesdbloom** [comment]
I agree verification by expectation id would be a good idea and that would avoid the duplication.   Although in general I would say for most cases it is an anti-pattern to have specific expectations and verifications because that is duplicating the same logic twice.  In general you would only need to verify if there are very loose expectations.

**Comment by leonard84** [comment]
I come from testing with [Spock](http://spockframework.org/spock/docs/1.3/all_in_one.html#_interaction_based_testing), which has really great mocking and stubbing support built-in. With it you can combine verification and stubbing in a single instruction. Under the hood it uses AST transformations to move the mock instructions just before the `when` block and then verifies all interactions when entering the `then` block.

Some example spock code.

```groovy
when:
publisher.send("message1")

then:
1 * subscriber.receive("message1") >> "ok"
```

```groovy
1 * subscriber.receive("hello") >> "ok"
|   |          |       |           |
|   |          |       |           response generator
|   |          |       argument constraint
|   |          method constraint
|   target constraint
cardinality
```

I agree that duplicating the logic is a bad practice, but only if I have to repeat the request definition in the tests myself. On the other hand I think that stubbing and verification should use the same specificity, not just use a loose expectation because the API requires you to repeat yourself. The anti-pattern you describe is a direct result of the current API limitations, and the `id` approach would be a possible solution to that.

**Comment by jamesdbloom** [comment]
I'm not sure I agree because why do you need to assert twice that a request was sent with exactly the same assertion, I don't understand the value in that?  I agree libraries like Spock do that by fundamentally changing the underlying way the test order executes which is valid but I still see why there is any reason to test the same assertion twice.

However, I would certainly be happy to add support for validations by expectation id.  The expectation is now returned including its id in the SNAPSHOT version.  In addition it is possible to specify the id to any unique value of choice, such as a meaningful name.

I've added this item to the backlog https://trello.com/c/Q4mwXeRc/117-verification-by-expectation-id

As I have added this to the backlog I'm going to close this issue as new features are tracked in Trello but feel free to add more comments to this issue to continue the discussion as this issue will be checked prior to starting the new feature.

ETA this support will be added roughly in the next couple of months.

**Comment by leonard84** [comment]
> why do you need to assert twice that a request was sent with exactly the same assertion, I don't understand the value in that?

The `when.respond` does not assert that anything was actually sent, it is only used to return a stubbed value. If your code does not call the remote system you don't see it if you use only `when.respond`. 

If mockserver would record how many interactions occurred based on the ids then you are not really asserting the same thing twice. If that is not done internally, then the double assertion is just a side effect of the implementation.

BTW: I think it is confusing to close an accepted and not yet implemented issue.

**Comment by jamesdbloom** [comment]
I agree it does make sense to do the validation.  Although in many cases the test would fail if no response has been returned there is no guarantee that that is the case so adding the verification makes sense.

Github issues are good but they don't offer the full feature set required for a backlog.  If I don't close the issue then I'll have another 150 issues in github without the easy and simple ability to prioritise the order they are delivered or which features are in the next release, in progress, etc.  Using labels or github releases for this is pretty hard work and not that clear.  Given the feature request has been accepted onto the backlog and the backlog is not managed in github keeping the issue open would be a duplicate, especially as not all feature requests come from github.  In addition this hammers clarity into what is a bug and what is a feature request and makes it too hard to easily find bugs.

**Comment by leonard84** [comment]
Just FYI Github also added Kanban boards https://docs.github.com/en/github/managing-your-work-on-github/about-project-boards with priority and everything else, see https://github.com/mock-server/mockserver/projects. Also it is possible to assign issues to milestones (releases). 
But if you use other tools that is ok too, just wanted to let you know that they improved their capabilities quite a bit.

**Comment by jamesdbloom** [comment]
Thanks the project board feature definitely looks interesting, at some point I'll investigate because it might be integrated better to everything else.
