### ISSUE TITLE
acquire param values like requestId in JSON request body and use it in response

### ISSUE THREAD

**Issue by sirius-in-tardis** [mock-server/mockserver#806]
**Describe the feature request**
acquire param values in JSON request body  so that the value can be referred to when configuring response in expectation

**What you are trying to do**
refer to the request id in JSON request body and use it in response

When server received a request like this, the "id" is a required parameter to respond correctly. 
But it cannot be acquired yet in mock server.
request:
{
    "payload": {
          "param1": "a"
    },
    "id":  17
}
correct response:
{
    "id":  17,
    "result": {"xx": "yy"}
}

**The solution you'd like**
maybe a method in MockServerClient using the request content to dynamically configure response content

**Describe alternatives you've considered**
If they exist, describe any alternative solutions you've considered.

**Comment by jamesdbloom** [comment]
This is already possible in four ways:
- Closure Callback https://mock-server.com/mock_server/creating_expectations.html#button_response_method_or_closure_callback
- JavaScript Template https://mock-server.com/mock_server/creating_expectations.html#button_javascript_templated_response
- Velocity Template https://mock-server.com/mock_server/creating_expectations.html#button_javascript_velocity_templated_response
- Class Callback https://mock-server.com/mock_server/creating_expectations.html#button_response_class_callback

Is there a reason why one of these approach does not work in your scenario?

**Comment by sirius-in-tardis** [comment]
I followed your suggestion using a response callback and it worked. Thank you so much :)
Earlier I searched the manual page using wrong key words and did not find the solution. Sorry for the trouble.

**Comment by jamesdbloom** [comment]
No problem, happy to help
