### ISSUE TITLE
5.11 docker image is running server version 5.10

### ISSUE THREAD

**Issue by leandrorlemos** [mock-server/mockserver#809]
**Describe the issue**
I updated my mock-server-client due to renovate request and noticed that I can't upgrade my mock-server also to 5.11 when using docker. The docker mock-server tagged as mockserver/mockserver:mockserver-5.11.0 is running jar file version 5.10

```
PUT http://localhost:1080/mockserver/expectation

HTTP/1.1 201 Created
version: 5.10
connection: keep-alive
content-length: 0
```

While running the mock-server latest version with homebrew returns correct version:
```
PUT http://localhost:1080/mockserver/expectation

HTTP/1.1 201 Created
version: 5.11.0
connection: keep-alive
content-type: application/json; charset=utf-8
content-length: 335
```

Not sure if this helps but, looking at the source code that builds the image the 
[REPOSITORY_URL](https://github.com/mock-server/mockserver/blob/44afdcaa2d26391d95cceb008cb65aceed8a37ec/docker/snapshot/Dockerfile#L18) is returning the 5.10 jar file for VERSION=LATEST.

**What you are trying to do**
Run docker image mockserver/mockserver:mockserver-5.11.0 with server version 5.11.

**MockServer version**
5.11.0

**To Reproduce**
Steps to reproduce the issue:

1. Pull latest docker image mockserver/mockserver:mockserver-5.11.0
2. Execute a request to the mock-server
3. Check the header version, it will be 5.10 instead of 5.11.

**Expected behaviour**
The header version should be 5.11

**Comment by jamesdbloom** [comment]
This was an issue with docker caching the previous output I have now fixed this and updated the version for that tag.  

Also you should now be able to also see the MockServer version at the start of ever log statement immediately after the timestamp.  This make it easier to confirm the version (and also easier when logs are cut and pasted into an issue)

**Comment by leandrorlemos** [comment]
Thank you so much!!
