### ISSUE TITLE
v5.11 not mocking requests with "body"

### ISSUE THREAD

**Issue by luiscspinho** [mock-server/mockserver#814]
**Describe the issue**
When trying to mock a request with a REGEX body on the `httpRequest` object, the request is never matched, even though my body is:
```js
body: {
 type: "REGEX",
 regex: ".*"
}
```

**What you are trying to do**
I've my setup (node client, mockserver 5.11) to intercept requests depending on the body of them, and with v5.10 it was working like a charm. I updated to v5.11 and noticed that no requests were being matched. After some digging I noticed that it is the `body` object (inside `httpRequest`) that is causing this problem, even if I put it as generic as possible (`REGEX/.*`) it still happens.

**MockServer version**
Mock server 5.11, node client 5.11

**To Reproduce**
Steps to reproduce the issue:

1. Mock server 5.11 with node client 5.11
2. Mock any response with a body inside httpRequest:
```js
    httpRequest: {
      method: "GET",
      path: "/home",
      body: {
        type: "REGEX",
        regex: ".*"
      }
    },
    httpResponse: {
      statusCode: 200,
      body: "whatever)
    }

```
3. What error you saw

**Expected behaviour**
Should mock my request but it is never matched.

**Comment by jamesdbloom** [comment]
The problem is that is looks like you are attempting to break the rules of HTTP by matching on a request body for a GET request.  GET requests don't have bodies by definition.

If you use the following expectation is works correct:
```javascript
{
    "httpRequest": {
      method: "POST",
      path: "/home",
      body: {
        type: "REGEX",
        regex: ".*"
      }
    }, 
    "httpResponse": {
        "statusCode": 200,
         "body": "whatever"
    }
}
```

**Comment by luiscspinho** [comment]
Hey @jamesdbloom thanks for the reply.

What you said totally makes sense, what I'm trying to say is that on v5.10, I could have a GET with the "body"  param as generic as possible, and my request would be matched, however on v5.11 it never gets matched anymore.

I've a generic interface that serves for both my GET/POST requests, something like:
```js
    httpRequest: {
      method: param.method || "GET",
      path: param.path,
      body: {
        type: "REGEX",
        regex: param.body || ".*"
      },
      queryStringParameters: param.queryStringParameters
    },
    httpResponse: {
      statusCode: param.statusCode || 200,
      body: param.response
    }

```
I use this for any kind of requests, depending on what I want to mock. If in v5.11 I need to separate this into 2 logical (GET/POST) data structures, it's OK with me. I was just trying to understand why this changed (since I didn't notice anything on the changelog related to this), and if the change is intended. This structure, in v5.10, works like a charm even if I have a generic `body` (`REGEX/.*`) for the GET requests, all of them are matched. (same for POST requests with `queryStringParameters`)

**Comment by jamesdbloom** [comment]
I suspect the following would work:

```javascript
    httpRequest: {
      method: param.method || "GET",
      path: param.path,
      body: param.body ? {
        type: "REGEX",
        regex: ".*"
      } : undefined,
      queryStringParameters: param.queryStringParameters
    },
    httpResponse: {
      statusCode: param.statusCode || 200,
      body: param.response
    }
```

There are items in the changelog 

improved handling of body matching for control plane to clearly separate control plane and data plan matching

**Comment by jamesdbloom** [comment]
I haven't tested that code above so I can't guarantee it works but if you set the body to null then this will match empty bodies

**Comment by jamesdbloom** [comment]
However, I could look at match an empty body for a `.*` because that could be considered a match.  However, currently I think the logic doesn't even attempt to evaluate the regex because there is no body at all so that fails to match before changing the regex value.  Which could also be considered valid.  I think this is one of those edge cases that could be implemented correctly either way.

**Comment by luiscspinho** [comment]
Yes, I agree with everything you said 👍 
I'll make the change on my side for a null body, and tomorrow will get back to you with me results. If eventually you decide to consider `.*` as a valid empty body, my change would be pretty straight forward.

I'll resolve this issue right away. If you feel like implementing the other way around, thanks as well 👍

**Comment by luiscspinho** [comment]
The body as undefined has the intended behaviour, the request is matched.

Thanks @jamesdbloom
