### ISSUE TITLE
Request body matching fails when using custom content type

### ISSUE THREAD

**Issue by csomogyi-ingenico** [mock-server/mockserver#815]
**Describe the issue**
Since 5.11.0 matching on request body is failing when using custom content-type in the request. 

**What you are trying to do**
Trying to send a POST request with content type `application/x.test` and body.

**MockServer version**
5.11.0

**To Reproduce**
Steps to reproduce the issue:

```
package test;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;
import java.nio.charset.StandardCharsets;
import java.util.stream.Collectors;
import javax.servlet.http.HttpServletResponse;
import org.mockserver.integration.ClientAndServer;
import org.mockserver.matchers.TimeToLive;
import org.mockserver.matchers.Times;
import org.mockserver.model.HttpRequest;
import org.mockserver.model.HttpResponse;
import org.mockserver.model.MediaType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class BugTest {
    static Logger LOG = LoggerFactory.getLogger(BugTest.class);

    public static void main(String[] args) throws IOException {
        try (ClientAndServer clientAndServer = ClientAndServer.startClientAndServer()) {
            clientAndServer
                    .reset()
                    .when(HttpRequest.request(), Times.unlimited(), TimeToLive.unlimited(), Integer.MIN_VALUE)
                    .respond(HttpResponse.response().withStatusCode(HttpServletResponse.SC_NOT_FOUND));
            clientAndServer
                    .when(HttpRequest.request()
                            .withMethod("POST")
                            .withPath("/post/hello")
                            .withContentType(MediaType.create("application", "x.test"))
                            .withBody("apple"))
                    .respond(HttpResponse.response()
                            .withContentType(MediaType.TEXT_PLAIN)
                            .withBody("pear"));

            URL url = new URL("http://localhost:" + clientAndServer.getLocalPort() + "/post/hello");
            URLConnection urlConnection = url.openConnection();
            HttpURLConnection conn = (HttpURLConnection) urlConnection;
            conn.setRequestMethod("POST");
            conn.setDoOutput(true);
            String requestBody = "apple";
            conn.setFixedLengthStreamingMode(requestBody.length());
            conn.setRequestProperty("Content-Type", "application/x.test");
            conn.connect();
            try (OutputStream os = conn.getOutputStream()) {
                os.write(requestBody.getBytes(StandardCharsets.UTF_8));
            }
            LOG.info("Response code: {} {}", conn.getResponseCode(), conn.getResponseMessage());
            LOG.info(conn.getHeaderFields().entrySet().stream().map(Object::toString).collect(Collectors.joining("\r\n")));
            if (conn.getResponseCode() >= 200 && conn.getResponseCode() < 300)
                try (BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream(), StandardCharsets.UTF_8))) {
                    LOG.info("Body: {}", reader.readLine());
                }
        }
    }
}
```

**Expected behaviour**
The above code should indicate response with status 200. Running it with 5.10 I receive this response. When I run it with 5.11.0 then I get 404 (matching failed).

**MockServer Log**
```
13:26:11.761 [MockServer-EventLog0] INFO org.mockserver.log.MockServerEventLog - request:

  {
    "method" : "POST",
    "path" : "/post/hello",
    "headers" : {
      "Content-Type" : [ "application/x.test" ],
      "User-Agent" : [ "Java/11.0.6" ],
      "Host" : [ "localhost:55167" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "Content-Length" : [ "5" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "body" : "YXBwbGU="
  }

 didn't match expectation:

  {
    "id" : "815dc3aa-5c01-4ad2-ac58-09d34d0c67f2",
    "priority" : 0,
    "httpRequest" : {
      "method" : "POST",
      "path" : "/post/hello",
      "headers" : {
        "content-type" : [ "application/x.test" ]
      },
      "body" : "apple"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "headers" : {
        "content-type" : [ "text/plain" ]
      },
      "body" : "pear"
    }
  }

 because:

  
  method matched
  path matched
  body didn't match
```

It's also interesting that the body is seen as Base64. Also in 5.10 even if the matching with that version is successful.

**Comment by csomogyi-ingenico** [comment]
I played around a bit and it's not exactly clear but there's something to do with certain `application/*` content types. For example, `application/sql` is also causing the issue. But `application/json` is ok.

**Comment by jamesdbloom** [comment]
Version 5.10.0 had a bug in it which meant that it assumed a body was text unless it was a known binary format.  That was not strictly correct and 5.11.0 is now more correct in terms of the HTTP specification.  So unless you use a content type that is text your request will be treated as bytes and thus the bytes (the UTF-8 encoded string) won't match a string, not least because there is no way to tell your bytes are UTF-8 encoded string bytes.  

If you use a text content-type like `application.json`, `application/xml`, `plain/text`, `application/text`, etc then the body is treated as text.  If no charset is specified (i.e. `; charset=utf-8`) then the default HTTP charset is used `ISO-8859-1` unless it is `application/json`, or `application/xml` then the mime type default charset for those content types is used (as per HTTP specification) which is `UTF-8`.

**Comment by csomogyi-ingenico** [comment]
Ok, now I understand the logic. The above example will work if I change this line:

`.withBody("apple"))`

with this

`.withBody("apple".getBytes(StandardCharsets.UTF_8)))`

in my example. Then the expectation will be created with `BINARY` body.

Ok, this may sound reasonable.

But what this basically implies is that a request matcher with a combination of

`.withContentType(MediaType.create("application", "x.test"))`

and

`.withBody("apple")`

will never match anything. If so is it possible to give a warning in the log or throw an exception about it?

**Comment by jamesdbloom** [comment]
The body is match separately from the content type header the two are not really related. 

The relation comes when parsing the incoming request body.  I parse that according to the content type headers on the incoming request not on the expectation.

So a warning or error was thrown when a content type isn't specified that would force everyone one to specify a content type header matcher which is not currently required and some many not want to add that complexity to their expectations.

Does that make sense?
