### ISSUE TITLE
Add arm64 docker image for hosting on RaspberryPi devices

### ISSUE THREAD

**Issue by zaknafeyn** [mock-server/mockserver#819]
**Describe the feature request**
Add official build of Mock Server for ARM64 devices (RaspberryPi and others)

**What you are trying to do**
I'd like to run Mock Server on RPi device in a docker container. 

**The solution you'd like**
Add build of ARM docker image to automated build pipeline and export image to docker hub.

**Comment by odidev** [comment]
@reypm 
I could get the output in my local ARM64 server when I followed below steps.
1.	Executed the docker-compose.yml using command `docker-compose up -d mockServer`  in their respective directory, and after the successful execution the tagged image is created.

2.	Ran the image once after the docker-compose is successful using `docker run -it mockserver/mockserver:mockserver-5.7.2` command. We are getting required outputs in both AMD64 and ARM64 platforms. 

Please let me know if you are still facing the issues.

**Comment by deitmerit** [comment]
An arm64 image would also be very useful to be able to run Mockserver on recent Macs (with Apple Silicon CPUs).

**Comment by tazle** [comment]
The main issue appears to be that the base image in the Dockerfile is gcr.io/distroless/java:11 which doesn't have arm64 arch available. Switching to e.g. openjdk:11 would solve that and enable arm64 build.

There seems to have been some effort to create an ARM64 version of the distress images, but the ticket is still open: https://github.com/GoogleContainerTools/distroless/issues/377

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/fUHwzasD/153-add-arm64-docker-image-for-hosting-on-raspberrypi-devices

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by prashil-g** [comment]
It would be good to have arm64 images for native mac m1 support

**Comment by developmentMLPN** [comment]
@karlzakhary i work on a project that uses mock-server a lot for integration-tests. The experience on ARM is not great. While the image starts in emulation sometimes this is not a given - sometimes it just hangs and timeouts (we use a timeout to make sure the container is healthy).
