### ISSUE TITLE
unable to enable CORS for all responses using the mockserver docker 

### ISSUE THREAD

**Issue by hansparsonsinvitae** [mock-server/mockserver#825]
**Describe the issue**

i'm unable to enable CORS for all responses using the mockserver docker

**What you are trying to do**
I've tried using the command from https://github.com/mock-server/mockserver/issues/422

docker run -p 1080:1080 jamesdbloom/mockserver /opt/mockserver/run_mockserver.sh -logLevel INFO -serverPort 1080 -genericJVMOptions "-Dmockserver.enableCORSForAllResponses=true"

and tried using the examples from https://www.mock-server.com/mock_server/CORS_support.html

but i always get a java command error ( even the command listed in ticket 422 ):

```
   java -jar <path to mockserver-jetty-jar-with-dependencies.jar> -serverPort <port> [-proxyRemotePort <port>] [-proxyRemoteHost <hostname>] [-logLevel <level>] 
                                                                                                                                                                 
     valid options are:                                                                                                                                          
        -serverPort <port>           The HTTP, HTTPS, SOCKS and HTTP CONNECT                                                                                     
                                     port(
```

**MockServer version**
 5.11.1

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc) 

2. Code you used to create expectations

3. What error you saw

a Java runtime error saying that i need to at least provide a ServerPort ( log below )

**Expected behaviour**
No Java error when running command

**MockServer Log**

$ docker run -p 1080:1080 jamesdbloom/mockserver /opt/mockserver/run_mockserver.sh -logLevel INFO -serverPort 1080 -genericJVMOptions "-Dmockserver.enableCORSForAllResponses=true"
   run_mockserver.sh -serverPort <port> [-proxyRemotePort <port>] [-proxyRemoteHost <hostname>] [-logLevel <level>] [-jvmOptions <system parameters>]
                                                                                   
     valid options are:                                                            
        -serverPort <port>                      The HTTP, HTTPS, SOCKS and HTTP CONNECT
                                                port(s) for both mocking and proxying
                                                requests.  Port unification is used to
                                                support all protocols for proxying and
                                                mocking on the same port(s). Supports

   Error: At least 'serverPort' must be provided

                                                comma separated list for binding to
                                                multiple ports.
                                                
        -proxyRemotePort <port>                 Optionally enables port forwarding mode.
                                                When specified all requests received will
                                                be forwarded to the specified port, unless
                                                they match an expectation.
                                                
        -proxyRemoteHost <hostname>             Specified the host to forward all proxy
                                                requests to when port forwarding mode has
                                                been enabled using the proxyRemotePort
                                                option.  This setting is ignored unless
                                                proxyRemotePort has been specified. If no
                                                value is provided for proxyRemoteHost when
                                                proxyRemotePort has been specified,
                                                proxyRemoteHost will default to "localhost".
                                                
        -logLevel <level>                       Optionally specify log level using SLF4J levels:
                                                TRACE, DEBUG, INFO, WARN, ERROR, OFF or Java
                                                Logger levels: FINEST, FINE, INFO, WARNING,
                                                SEVERE or OFF. If not specified default is INFO
                                                
        -jvmOptions <system parameters>         Specified generic JVM options or system properties.
                                                                                   
   i.e. /opt/mockserver/run_mockserver.sh -serverPort 1080,1081 -proxyRemotePort 80 -proxyRemoteHost www.mock-server.com -logLevel DEBUG -jvmOptions "-Dmockserver.enableCORSForAllResponses=true -Dmockserver.sslSubjectAlternativeNameDomains='org.mock-server.com,mock-server.com'"

**Comment by mcopjan** [comment]
any update on this please? Experiencing the same behaviour

**Comment by tarasmurzenkovv** [comment]
I have encountered the same error while using TestContainers and latest docker image

**Comment by jamesdbloom** [comment]
Now any configuration values can be set via docker using environment variables, as per this integration test example: https://github.com/mock-server/mockserver/blob/master/container_integration_tests/docker_compose_with_expectation_initialiser/docker-compose.yml
