### ISSUE TITLE
Mock-server randomly removes expectations as soon as they're created

### ISSUE THREAD

**Issue by SundaraSK** [mock-server/mockserver#826]
**Mock-server randomly removes expectations as soon as they're created**
I am using Openshift,Sboot Services, Mock Server 5.11.0
Scenario- I need to call three parallel services from from Single request hence I have set  3 individual expectations  for one Service request (Test 1) - I am getting correct response Single request.

When i try to submit 10 request to access expectation  (10 * 3 expectations) ,some expectations are  randomly  missing 
F  due to missing expectation.
S -1*3 -expectations \are available in mock server and service request access it successfully    
For example (Smoke test 1)
SSSSSSSSSS
SSSSSSSSSS
SSSSSSSSSS
SSSSSSSSSS
SSSSSSSSSS
SSSSFSSSSS
SSSSSSSSSS
SSSSSSSSSS
SSSSSSSSSS
SSSSSSSSSS
**What you are trying to do**
Scenario- I need to call three parallel services from from Single request hence I have set  3 individual expectations  for one Service request (Test 1) - I am getting correct response.

Expectation loss is not happening in every smoke test pack (Smoke test for 10 request), out of 20 tests (20 * 10 * 3)  every few expectations are missing from mock server. 

I have verified the expectation from dash board -expectation with id are created and removed from mock server immediately, hence service is unable to access the expectation. 

**MockServer version 5.11.0**

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer -hosted in opeshift
2. Code you used to create expectations

expectation1 = {
      "id": "",
      "httpRequest": {
        "path": "/service1",
        "body": {
          "type": "REGEX",
          "regex": ""
        }
      },
      "httpResponse": {
        "body": MockLoader().load_mock('service1.xml')
      },
      "times" : {
        "remainingTimes" : 1,
        "unlimited" : False
      },
      "timeToLive": {
        "timeUnit": "HOURS",
        "timeToLive": 1
      }
    }
	

expectation2 = {
      "id": "",
      "httpRequest": {
        "path": "/service1",
        "body": {
          "type": "REGEX",
          "regex": ""
        }
      },
      "httpResponse": {
        "body": MockLoader().load_mock('service2.xml')
      },
      "times" : {
        "remainingTimes" : 1,
        "unlimited" : False
      },
      "timeToLive": {
        "timeUnit": "HOURS",
        "timeToLive": 1
      }
    }

expectation3 = {
      "id": "",
      "httpRequest": {
        "path": "/service1",
        "body": {
          "type": "REGEX",
          "regex": ""
        }
      },
      "httpResponse": {
        "body": MockLoader().load_mock('service3.xml')
      },
      "times" : {
        "remainingTimes" : 1,
        "unlimited" : False
      },
      "timeToLive": {
        "timeUnit": "HOURS",
        "timeToLive": 1
      }
    }	
	
I am using following to persist the expectations using open shift template storage volume.

 env:
                - name: MOCKSERVER_LIVENESS_HTTP_GET_PATH
                  value: /ping
                - name: MOCKSERVER_INITIALIZATION_JSON_PATH
                  value: /tmp/mockserverInitialization.json
                - name: MOCKSERVER_WATCH_INITIALIZATION_JSON
                  value: "true"
                - name: MOCKSERVER_PERSIST_EXPECTATIONS
                  value: "true"
                - name: MOCKSERVER_PERSISTED_EXPECTATIONS_PATH
                  value: /tmp/mockserverInitialization.json 

3. What error you saw

**Expectation should not be removed after creation or until it expires (time to live & time to remain valid)**
expectations are removed randomly after creation 
**MockServer Log**
08-04 12:38:16.782 NO_MATCH_RESPONSE  error:"io.netty.channel.ConnectionTimeoutException:connection timed out"

08-04 12:38:15.740 EXPECTATION_NOT_MATCHED	

08-04 12:38:16.782 REMOVED_EXPECTATION  removed expectation {
                                                                id:1
                                                                http request
                                                                http response 																

08-04 12:38:15.992 CREATED_EXPECTATION  created expectation {
                                                                id:1
                                                                http request
                                                                http response

**Comment by SundaraSK** [comment]
I have created list of expectation instead individual expectation (3 expectation ) and also added sleep between each test to avoid expectation loss, but this issue (random expectation removal) can reoccur with high volume tests, please suggest possible fix.

**Comment by LowCostCustoms** [comment]
I believe this is because you set the `MOCKSERVER_WATCH_INITIALIZATION_JSON` to the `true`. The issues is that the same file is modified and watched for updates by the same instance of mock-server. Therefore once you load your expectations into the mock-server, it writes them into this json file and after some time it notices that someone has updated this file (it actually doesn't care who has modified this file) and loads expectations from there. So it removes the existing expectation first and adds a new expectation with the same id and properties instead. Not really a but, but rather a configuration issue.

**Comment by adamhibbert** [comment]
@LowCostCustoms @SundaraSK
We had the same issue and also resolved by setting `MOCKSERVER_WATCH_INITIALIZATION_JSON` to `false`.

**Comment by maojunxyz** [comment]
@adamhibbert  @LowCostCustoms  it worked. 

We had the same issue too. Found in the mockserver web content:

> If enabled the initialization json file will be watched for changes, any changes found will result in expectations being created, remove or updated by matching against their key.
>If duplicate keys exist only the last duplicate key in the file will be processed and all duplicates except the last duplicate will be removed.
> The order of expectations in the file is the order in which they are created if they are new, however, re-ordering existing expectations does not change the order they are matched against incoming requests.


In addition, the demo shows that the stand-alone configuration is somewhat different from the cluster configuration.

```java
java \
-Dmockserver.watchInitializationJson=true \
-Dmockserver.initializationJsonPath=mockserverInitialization.json \
-jar ~/Downloads/mockserver-netty-5.11.1-jar-with-dependencies.jar -serverPort 1080,1081 -logLevel INFO
```
Clustering MockServer

```java
java \
-Dmockserver.watchInitializationJson=true \
-Dmockserver.initializationJsonPath=mockserverInitialization.json \
-Dmockserver.persistExpectations=true \
-Dmockserver.persistedExpectationsPath=mockserverInitialization.json \
-jar ~/Downloads/mockserver-netty-5.11.1-jar-with-dependencies.jar -serverPort 1080 -logLevel INFO
```

Maybe you should try it in the cluster.

**Comment by jamesdbloom** [comment]
Seems like a configuration issue only.  Also the file watcher logic has been improved recently so it is more reliable now.
