### ISSUE TITLE
Increasing memory usage with Junit5 when logging on default settings

### ISSUE THREAD

**Issue by alex-ureche** [mock-server/mockserver#827]
## Issue ##
**Describe the issue**
RAM usage during tests increases to max heap size.

**What you are trying to do**
I am running mocked tests with JUnit 5 (5.6.0) / SDK 1.8.0-251

**MockServer version**
5.10.0 and 5.11.1

**To Reproduce**
1. startClientAndServer(mockPort)
2. Mock all requests and responses - when(request).respond(response)
3. Run Tests
4. mockServer.stopAsync()

**How you are running MockServer (i.e maven plugin, docker, etc)**
Gradle  - testImplementation 'org.mock-server:mockserver-netty:5.11.1'

**Code you used to create expectations**
No expectations are set. Some requests are mocked/cleared during tests (these tests show memory spikes).

**MockServer Log**
No errors/warnings/logs are printed.

## Memory Sampling Results ##

**Testing details**
Gradle heap size - 4096M
Sampling used mem - ManagementFactory.getMemoryMXBean().getHeapMemoryUsage().getUsed() / 1024 / 1024
Sampling committed mem - ManagementFactory.getMemoryMXBean().getHeapMemoryUsage().getCommitted() / 1024 / 1024
Sampling stages - BeforeAll, BeforeEach, AfterAll and AfterEach

**5.10.0 - Logging not configured - Tests duration 42 seconds**
![LoggingOn5100](https://user-images.githubusercontent.com/48322018/89774932-7577cf80-db0f-11ea-8e71-38b75da603ef.jpg)

**5.11.1 - Logging not configured - Tests duration 16 seconds**
![LoggingOn5111](https://user-images.githubusercontent.com/48322018/89775057-af48d600-db0f-11ea-9785-4c44345556b8.jpg)

**5.11.1 - Logging reduced - Tests duration 2 seconds**
```
startClientAndServer(mockPort);
ConfigurationProperties.disableSystemOut(true);
ConfigurationProperties.logLevel("ERROR");
```
![LoggingOff5111](https://user-images.githubusercontent.com/48322018/89775193-f931bc00-db0f-11ea-8119-e79241297d22.jpg)

**Comment by jamesdbloom** [comment]
Please see #1171, in summary MockServer store log entries by design to support the use of the UI, verification, recorded expectations and other use cases.  It attempts to only use the free memory available and reduces the amount of memory used if other code in the JVM uses up the free memory, see: https://github.com/mock-server/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/memory/MemoryMonitoring.java
