### ISSUE TITLE
when multiple servers are running, connection refuse is seen when expectation is matched

### ISSUE THREAD

**Issue by lxp1250** [mock-server/mockserver#830]
**Describe the issue**
Connection is lost when Mock-server find and matched expectation. 

**What you are trying to do**
I am trying to use mock-server to forward packets. There are several services running:
Server 1 on 127.0.0.1:9000
Server 2 on 127.0.0.1:1080 (using mock-server)
Server 3 on 127.0.0.1:1090 (using mock-server)

The idea is to forward any requests on sever 3 to server 1 with modified header. However, after mock-server detects expectation matched, it always get server 1 connection refuse error. 

**MockServer version**
The version you are using: 5.11.1

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc)
Maven plugin
2. Code you used to create expectations
`
        private static String HOST = "127.0.0.1";
        private static int PORT = 1090;

        public static void start() {
                startClientAndServer(PORT);
                createExpectationForSplat();
        }

        /* Mock splat integration */
        private static void createExpectationForSplat() {
                new MockServerClient(HOST, PORT)
                        .when(
                                request()
                                        .withPath("/somepath")

                        )
                        .forward(
                                forwardOverriddenRequest(
                                        request()
                                                .withPath("/some-path")
                                                .withHeader("header1", "value 1")
                                                .withSocketAddress("127.0.0.1", 9000, SocketAddress.Scheme.HTTP)
                                )
                        );`

3. What error you saw
Connection refused on server 1, when expectation is matched

**Expected behaviour**
Requests forwarded to server 1 successfully. 

**MockServer Log**
DEBUG 18:18:13.476 [dw-74] /CDF6E1D6ABC0926AD437B88C7411C257/16E5996B8FE00C329A7393273033CD50 o.e.j.util.thread.QueuedThreadPool: ran CEP:SocketChannelEndPoint@377a4c7f{l=/127.0.0.1:9000,r=/127.0.0.1:61810,OPEN,fill=FI,flush=-,to=0/30000}{io=1/1,kio=1,kro=1}->HttpConnection@77ba1a5a[p=HttpParser{s=START,0 of -1},g=HttpGenerator@744e43f9{s=START}]=>HttpChannelOverHttp@608c631c{s=HttpChannelState@33b00031{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0}:runFillable:BLOCKING in InstrumentedQueuedThreadPool[dw]@2c3c8bbb{STARTED,8<=8<=1024,i=3,r=4,q=0}[ReservedThreadExecutor@62eddcbd{s=1/4,p=0}]
Check if the server is started: true 
DEBUG 18:18:13.530 [main]  c.o.p.l.v.api.LoadBalancerClient: Client request: POST http://127.0.0.1:1090/loadBalancers
DEBUG 18:18:13.532 [main]  c.o.p.commons.client.BaseRestClient: Generated downstream request ID ECD767D0F709085D73125AEEB3AEF9C9/D0E39E7AFC1A06EB838EF0C901CC4A4D
INFO  18:18:13.806 [main]  c.o.p.i.a.s.RequestSignerImpl: String that will be signed: date: Tue, 25 Aug 2020 01:18:13 UTC\n(request-target): post /loadBalancers\ncontent-length: 4737\ncontent-type: application/json\nx-content-sha256: Xk+p6sOdASfyr1ZvQNei/FZ6ExqhKQhAwc08mR67dgA=\naccept: application/json\nopc-request-id: ECD767D0F709085D73125AEEB3AEF9C9/D0E39E7AFC1A06EB838EF0C901CC4A4D
DEBUG 18:18:13.852 [main]  o.a.h.c.protocol.RequestAddCookies: CookieSpec selected: default
DEBUG 18:18:13.852 [main]  o.a.h.c.protocol.RequestAuthCache: Auth cache not set in the context
DEBUG 18:18:13.854 [main]  o.a.h.i.c.PoolingHttpClientConnectionManager: Connection request: [route: {}->http://127.0.0.1:1090][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
DEBUG 18:18:13.856 [main]  o.a.h.i.c.PoolingHttpClientConnectionManager: Connection leased: [id: 1][route: {}->http://127.0.0.1:1090][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
DEBUG 18:18:13.856 [main]  o.a.h.impl.execchain.MainClientExec: Opening connection {}->http://127.0.0.1:1090
DEBUG 18:18:13.856 [main]  o.a.h.i.c.DefaultHttpClientConnectionOperator: Connecting to /127.0.0.1:1090
DEBUG 18:18:13.857 [main]  o.a.h.i.c.DefaultHttpClientConnectionOperator: Connection established 127.0.0.1:61811<->127.0.0.1:1090
DEBUG 18:18:13.857 [main]  o.a.h.impl.execchain.MainClientExec: Executing request POST /loadBalancers HTTP/1.1
DEBUG 18:18:13.857 [main]  o.a.h.impl.execchain.MainClientExec: Proxy auth state: UNCHALLENGED
ERROR 18:18:13.860 [MockServer-EventLog36]  o.mockserver.log.MockServerEventLog: web socket server caught exception
! java.lang.NoSuchMethodError: org.apache.commons.lang3.builder.EqualsBuilder.setExcludeFields([Ljava/lang/String;)Lorg/apache/commons/lang3/builder/EqualsBuilder;
! at org.mockserver.model.ObjectWithReflectiveEqualsHashCodeToString.equals(ObjectWithReflectiveEqualsHashCodeToString.java:34) ~[mockserver-core-5.11.1.jar:5.11.1]
! at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:940) ~[na:1.8.0_201]
! at org.mockserver.netty.unification.PortUnificationHandler.getLocalAddresses(PortUnificationHandler.java:306) ~[mockserver-netty-5.11.1.jar:5.11.1]
! at org.mockserver.netty.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:257) ~[mockserver-netty-5.11.1.jar:5.11.1]
! at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:138) ~[mockserver-netty-5.11.1.jar:5.11.1]
! at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:500) ~[netty-codec-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511) ~[netty-transport-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]
! at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.37.Final.jar:4.1.37.Final]

**Comment by lxp1250** [comment]
I need help to figure out why "NoSuchMethodError" is raised here
`
ERROR 18:18:13.860 [MockServer-EventLog36]  o.mockserver.log.MockServerEventLog: web socket server caught exception
! java.lang.NoSuchMethodError: org.apache.commons.lang3.builder.EqualsBuilder.setExcludeFields([Ljava/lang/String;)Lorg/apache/commons/lang3/builder/EqualsBuilder;
! at org.mockserver.model.ObjectWithReflectiveEqualsHashCodeToString.equals(ObjectWithReflectiveEqualsHashCodeToString.java:34) ~[mockserver-core-5.11.1.jar:5.11.1]
! at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:940) ~[na:1.8.0_201]
! at org.mockserver.netty.unification.PortUnificationHandler.getLocalAddresses(PortUnificationHandler.java:306) ~[mockserver-netty-5.11.1.jar:5.11.1]
! at org.mockserver.netty.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:257) ~[mockserver-netty-5.11.1.jar:5.11.1]
! at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:138) ~[mockserver-netty-5.11.1.jar:5.11.1]
! at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:500) ~[netty-codec-4.1.37.Final.jar:4.1.37.Final]`

**Comment by jamesdbloom** [comment]
NoSuchMethodErrors are caused by the project including MockServer using an old version of a MockServer dependency.  Either upgrade the `commons-lang3` dependency or use the MockServer shaded dependency:

```
<dependency>
    <groupId>5.13.0</groupId>
    <artifactId>mockserver-netty</artifactId>
    <classifier>shaded</classifier>
</dependency>
```
