### ISSUE TITLE
UTF for headers (cyrillic)

### ISSUE THREAD

**Issue by astrizhachuk** [mock-server/mockserver#831]
MockServer returns invalid header?

I have the expectation:

![image](https://user-images.githubusercontent.com/25724999/91162998-8874cd00-e6d5-11ea-91b5-5817042fb36c.png)

Postman returns:
![image](https://user-images.githubusercontent.com/25724999/91163117-c114a680-e6d5-11ea-919b-8491505764b0.png)

Gitlab returns correct header (cyrillic):
![image](https://user-images.githubusercontent.com/25724999/91165771-f0c5ad80-e6d9-11ea-9909-b7413280823e.png)

Version:
latest docker image

```
"{
 "httpResponse": {
  "body": "some_response_body",
  "statusCode": 200,
  "headers": {
   "X-Gitlab-File-Name": [
    "Внешняя Обработка 2.epf"
   ]
  }
 },
 "httpRequest": {
  "headers": {
   "PRIVATE-TOKEN": [
    "-U2ssrBsM4rmx85HXzZ1"
   ]
  },
  "queryStringParameters": {
   "ref": [
    "ef3529e5486ff39c6439ab5d745eb56588202b86"
   ]
  },
  "method": "GET",
  "path": "/api/v4/projects/1/repository/files/%D0%9A%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3%20%D1%81%20%D0%BE%D1%82%D1%87%D0%B5%D1%82%D0%B0%D0%BC%D0%B8%20%D0%B8%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0%D0%BC%D0%B8%2F%D0%92%D0%BD%D0%B5%D1%88%D0%BD%D1%8F%D1%8F%20%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0%202.epf/raw"
 }
}"
```
Expecting a cyrillic header. 

![image](https://user-images.githubusercontent.com/25724999/91163944-071e3a00-e6d7-11ea-8ddc-0c9c181ae95b.png)

**Comment by jamesdbloom** [comment]
According the HTTP specification only ASCII is legal in a header, see: https://www.ietf.org/rfc/rfc0822.txt (sections 3.1.1 and 3.1.2) also see https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html (section 4.2) which refers to the first specification.

I could extend the Netty library to return UTF-8 but it wouldn't be correct HTTP.
