### ISSUE TITLE
initializationJsonPath options support for OpenAPIExpectation

### ISSUE THREAD

**Issue by guillaume-dubber** [mock-server/mockserver#836]
I'd like to be able to use OpenAPI specifications to preload expectations into MockServer.

Would it be possible to extend the current initializationJsonPath option to allow use of OpenAPIExpections? At the moment `ExpectationInitializerLoader` is using `ExpectationSerializer` by default. If it could use also use the `OpenAPIExpectationSerializer` depending on the existence of `specUrlOrPayload` for example that could work?

If it is not possible, could another initializationOpenAPIJsonPath be created to load these specifications separately?

Thank you

**Comment by jamesdbloom** [comment]
This is now supported and in the SNAPSHOT version which will be released in the next couple of weeks.
