### ISSUE TITLE
Vulnerability reported when using mockserver-netty for org.yaml_snakeyaml 1.24

### ISSUE THREAD

**Issue by engelr1974** [mock-server/mockserver#840]
**Description**
The vulnerability scanner is reporting a critical error for including a dependency on org.yaml_snakeyaml:1.24, fixed in 1.26

By continuing to use this version of MockServer, I will encounter having a security finding automatically registered for this vulnerability.

**MockServer version**
MockServer version 5.11.1

**To Reproduce**
To reproduce, run a vulnerability scanner against the mockserver-netty-5.11.1-jar-with-dependencies.jar

**Analysis**
I took some time to trace through the dependencies of mockserver-core, to ensure the snakeyaml dependency wasn't coming from something else I'm including in my base image, and believe I found the root cause as:
**io.swagger.parser.v3::swagger-parser::2.0.20 reference will need to be updated to version 2.0.21**

Following the swagger-parser path of dependencies, you'll end up as swagger-core, and it's reliance on jackson-dataformat-yaml is then ultimately the dependency that relies on org.yaml_snakeyaml

**Comment by jamesdbloom** [comment]
This has now been updated and will be in the latest SNAPSHOT once the SNAPSHOT release build completes.
