### ISSUE TITLE
Initialize expectations from location/path

### ISSUE THREAD

**Issue by x80486** [mock-server/mockserver#874]
## Describe the feature request

Today, it's possible to use `mockserver.initializationJsonPath` and point to a single JSON file that contains several expectations. If a project have several (like in **a lot**) of expectations, it would be better to organize them into sub-directories and let MockServer read that location/path (recursively) and load the expectations.

## What you are trying to do

Have the expectations isolated by functionality/categories/types, etc.

## The solution you'd like

Something like `mockserver.initializationPath` (and `mockserver.watchInitializationPath`) instead.

**Comment by carolinafbarros** [comment]
Hi @x80486,
is not related with this feature request, but I have problems using the `initializationJsonPath` specifying the JSON file path (one file only). I have an exception while loading the file (I confirm the path  file and is correct)

I'm using the mock server node and I'm defining the JSON file path inside of `jvmOptions`:

```
options: {
        serverPort: 1080,
        jvmOptions: "-Dmockserver.initializationJsonPath=tests/helpers/mock-initializer.json"
    }
```

Any clue about what I'm doing wrong?

![image](https://user-images.githubusercontent.com/11806246/101500970-11530400-3967-11eb-9530-4933e935baab.png)

**Comment by x80486** [comment]
If you have a Maven-compliant project structure, you can place a JSON file in `${project.root}/src/main/resources/expectations.json`, then you can load it by using `-Dmockserver.initializationJsonPath=src/main/resources/expectations.json`.

If you are using a different MockServer "flavor" I would keep the path right from the project's root — removing segments until it works :rofl:

The behaviour for MockServer is to load from classpath, falling back to the actual path — if the former didn't work.

**Comment by carolinafbarros** [comment]
Thanks for the suggestion @x80486.

Using the path right from the project's root doesn't work 😢 . It's really weird because If I tried with the command below on terminal effectively works. The file loaded with success. 

`java -Dmockserver.initializationJsonPath="tests/helpers/mock-initializer.json" -jar tests/mockserver-netty-5.11.1-jar-with-dependencies.jar -serverPort 1081`
