### ISSUE TITLE
Allow to refer to files for response body

### ISSUE THREAD

**Issue by x80486** [mock-server/mockserver#875]
## Describe the feature request

If a given expectation is defined in JSON, a `body` key is typically used to return some content back. Sometimes that content can be extensive enough and with many escaped characters that the JSON becomes unreadable or just too big.

It would be great if there was a way to refer to a file instead, and load that file as part of the value for that `body` key.

## What you are trying to do

To return a file as part of the content body of a given request from any expectation. If a file is used, the expectation looks neat, and the file itself doesn't lose the correct formatting.

## The solution you'd like

To use another key to refer specifically to files — somehthing like `bodyAsFile`, or `bodyFromFile`, or `bodyFile`, etc.

> Moreover, if this is considered, it can also be expanded to `httpResponseTemplate`, where `template`'s (or another key) should be able to refer/use a file location also.

## Some (Super-Simple) Examples

```json
[
  {
    "httpRequest": {
      "headers": {
        "accept": ["application/json"],
        "content-type": ["application/json"]
      },
      "method": "POST",
      "path": "/api/characters",
      "body": {
        "jsonSchema": "schemas/character.json"
      }
    },
    "httpResponseTemplate": {
      "templateType": "VELOCITY",
      "template": "templates/create-character-response.vm"
    },
    "times": {
      "unlimited": true
    }
  }
]
```

```velocity
{
  "headers": { "location": ["${request.path}/0f578684-3221-43b5-af31-7331ea55fbd2"] },
  "statusCode": 201
}
```

**Comment by ygyg70** [comment]
I am also asking this question - is this project still active? What is the recommended method for integrating a nicely formatted templates as response body?
