### ISSUE TITLE
Outdated javax.validation from Swagger causes clash with Dropwizard

### ISSUE THREAD

**Issue by kwahsog** [mock-server/mockserver#880]
**Describe the issue**
When running mockserver with latest Dropwizard (2.0.13), there is the following error:

Runtime Error - java.lang.NoSuchMethodError: org.hibernate.validator.HibernateValidatorConfiguration.addValueExtractor

This caused by an old version of javax.validation from the Swagger dependency, and needs to be excluded from maven to resolve.

e.g. 

```   
<dependency>
                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-netty</artifactId>
                <version>${mockserver.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>javax.validation</groupId>
                        <artifactId>validation-api</artifactId>
                    </exclusion>
                </exclusions>
                <scope>test</scope>
            </dependency>
```

This is the same issue as detailed here:

https://github.com/dropwizard/dropwizard/issues/3089

Should be fixed by upgrading the Swagger version.

**MockServer version**
5.11.1

**To Reproduce**
1. Run Dropwizard with Mockserver dependencies both added via Maven.

`        server.run("server", ResourceHelpers.resourceFilePath("config.yml"));`

**Expected behaviour**
Not to error.

**MockServer Log**
Can provide if helpful, but it's more of classpath issue.

**Solution**
Upgrade Swagger version. Can make PR to do so if helpful.

**Comment by jamesdbloom** [comment]
The `swagger-parser` has now been upgraded to the latest version.  Please confirm if this is still an issue in the latest SNAPSHOT version.  

If this is still an I suspect the only solution is to do the exclusion you are doing because it is likely that the `swagger-parser` library is using `validation-api` and therefore it would be risky to exclude this dependency as other users who have not included this dependency in their project will have issues.

**Comment by kwahsog** [comment]
Hmm honestly didn't fix my problem. But thanks for looking into it and upgrading it, always a good thing to do I guess.

For reference, still getting the issue as getting from mockserver-netty:

`[INFO] |  |  +- io.swagger.parser.v3:swagger-parser:jar:2.0.23:test
[INFO] |  |  |  +- io.swagger.parser.v3:swagger-parser-v2-converter:jar:2.0.23:test
[INFO] |  |  |  |  +- io.swagger:swagger-core:jar:1.6.2:test
[INFO] |  |  |  |  |  +- io.swagger:swagger-models:jar:1.6.2:test
[INFO] |  |  |  |  |  |  \- io.swagger:swagger-annotations:jar:1.6.2:test
[INFO] |  |  |  |  |  \- javax.validation:validation-api:jar:1.1.0.Final:test`

But looks like the issue is from Swagger's side then.
