### ISSUE TITLE
Is it possible remove a path prefix when fowarded request

### ISSUE THREAD

**Issue by diegobmd** [mock-server/mockserver#895]
Is it possiblw remove a path prefix when fowarded request? When I configure my mock server and to avoid duplicate paths for different hosts mocks I want do create a path prefix to organize the mocks

I'm trying to configure something like this

```json
  [
  
  {
    "priority" : 1,
    "httpRequest": {
      "path": "/samples/url/1"
    },
    "httpResponse": {
      "body": "some_response_body 1, 2"
    }
  },
  
  {
    "priority" : 0,
    "httpRequest": {
      "path": "/samples/url/.*"
    },
  
    "httpOverrideForwardedRequest": {
      "httpRequest": {
        "path": "/echo/get/json",
        "headers": {
          "Host": ["reqbin.com"]
        },
        "secure" : true,
        "socketAddress": {
          "host": "reqbin.com",
          "port": 443,
          "scheme": "HTTPS"
        }
      }
    }
  }
  
  ]
```

If I call the result expect may be 

/samples/url/1 = mock

/samples/url/2 = fowarded to reqbin.com/2

**Comment by jamesdbloom** [comment]
I'm not sure I understand this feature request can you please provide some more information and examples.

**Comment by diegobmd** [comment]
sorry was a long time but I'll try to examplain

When you foward request is it possible add a flag to strip the path prefix

eg conf

```
  {
    "priority" : 0,
    "httpRequest": {
      "path": "/samples/url/.*"
    },
  
    "httpOverrideForwardedRequest": {
      "httpRequest": {
        "path": "/echo/get/json",
        "headers": {
          "Host": ["reqbin.com"]
        },
        "secure" : true,
        "socketAddress": {
          "host": "reqbin.com",
          "port": 443,
          "scheme": "HTTPS"
        }
      }
    }
```

call `mockserver/samples/url/.1`  instead o foward to `reqbin.com/samples/url/.1` foward to `reqbin.com/.1`

**Comment by jamesdbloom** [comment]
Ok makes sense it should be possible to do this with a JavaScript or Velocit template or an object or class callback, but I'll think about if there is a way to make the more static forward actions more flexible to support this.  Envoy has some techniques that do this that could be an inspiration but they are much more complex to understand.

**Comment by jamesdbloom** [comment]
I have started an implementation that should provide what you need the initial approach would allow a path to be modified using a regex and a substitution (envoy style), for example:

```
regex: ^/(.+)/(.+)$
substitution: /prefix/$1/infix/$2/postfix
then: /some/path => /prefix/some/infix/path/postfix
or: /some/longer/path => /prefix/some/infix/longer/path/postfix
```

**Comment by jamesdbloom** [comment]
This is now completed expect for documentation.

**Comment by jamesdbloom** [comment]
This is implemented and the documentation of this is covered by this backlog item https://trello.com/c/17E54s3Y/172-documentation which is in progress so closing this issue
