### ISSUE TITLE
Update expectation by scaneario

### ISSUE THREAD

**Issue by paulo-coutinho** [mock-server/mockserver#913]
Hi,

How can i update expectation by scenario. Example:

```
  /backend/login [POST]
      -> id: login
      -> retorna arquivo login.json
   /backend/signup [POST]
      -> retorna arquivo signup.json
   /backend/login [POST]
      -> id: login
      -> scenario: login-with-error
      -> retorna arquivo login-error.json
```

When i will execute test on my C++ project i change "update" by "id" my expectation "login" that have the same route to return error now.

I read the docs but don't find any obviously.

It is possible with mock server?

Thanks and great project.

**Comment by jamesdbloom** [comment]
Update by scenario isn't possible the typical approach would be to either update by id.  Or more commonly would be to clear the expectations by using a request matcher as follows https://mock-server.com/mock_server/clearing_and_resetting.html#button_client_clear  then create a new expectation as required.
