### ISSUE TITLE
Allow for configuring nonProxyHosts

### ISSUE THREAD

**Issue by darabi** [mock-server/mockserver#917]
**Describe the feature request**
Add a configuration option for configuring `nonProxyHosts` as described in the [Java SE proxy documentation](https://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html):

> http.nonProxyHosts: a list of hosts that should be reached directly, bypassing the proxy. This is a list of patterns separated by '|'. The patterns may start or end with a '*' for wildcards. Any host matching one of these patterns will be reached through a direct connection instead of through a proxy.
For these hosts, mock-server would **not** send the request to the host configured in `proxyRemoteHost`, but uses a direct connection.

**What you are trying to do**
I am working in an environment where I have to mock two types of services:
1. some are reachable only via an upstream proxy 
1. some can be reached directly 

The upstream proxy returns an error, when it receives a request for servers of the latter type.

**The solution you'd like**
I would like to see the following in the MockServer configuration:

> **HTTP Forward Proxy Exempt Hosts
>
> Send all requests to these hosts directly, bypassing the configured remote proxy in the forwarding configuration. Similar to the Java system property `http.nonProxyHosts`, the value is a pipe-separated list which may contain asterisk as a wildcard.
> 
> Type: string Default: null
> 
> Java Code:
> 
> ConfigurationProperties.forwardProxyNonProxyHosts(String pipeSeparatedHosts)
> 
> System Property:
> 
> -Dmockserver.nonProxyHosts=...
> 
> Environment Variable:
> 
> MOCKSERVER_FORWARD_PROXY_NON_PROXY_HOSTS=...
> 
> Property File:
> 
> mockserver.forwardProxyNonProxyHosts=...
> 
> Example:
> 
> -Dmockserver.forwardProxyNonProxyHosts="localhost|host.mydomain.com|*.example.com"

**Describe alternatives you've considered**

N/A

**Comment by darabi** [comment]
@jamesdbloom: I have had a look at the code and I think I could provide a PR for the http part, but would need a bit of guidance for the https part.

Thank you

**Comment by jamesdbloom** [comment]
I agree that makes sense, I'm also happy to receive a PR.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/OPiKYbCz/158-allow-for-configuring-nonproxyhosts

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
