### ISSUE TITLE
Nottable strings seem to not work in latest version

### ISSUE THREAD

**Issue by jorge-trujillo** [mock-server/mockserver#921]
**Describe the issue**
I tried upgrading some code to the latest version, `5.11.2`, and it broke some tests that were previously fine. I tried downgrading to `5.10.0` and the tests pass once again, so it seems like a bug.

**What you are trying to do**
The test verifies that a query parameter is not being passed on a request. Mockserver then does not recognize this request on the faulty version and returns a 404.
 
**MockServer version**
Version `5.11.2`

**To Reproduce**

Using Mockserver as client and server:
```groovy
static ClientAndServer mockServerClient

  void setup() {
    if (!mockServerClient?.isRunning()) {
      mockServerClient = startClientAndServer(1080)
    }
    mockServerClient.reset()
  }
```

Expectation is created using `not`
```groovy
    String sellerId = 'someId'
    String path = '/path/to/endpoint'
    String brandId = '1234'

HttpRequest getRequest = request(path)
        .withMethod('GET')
        .withQueryStringParameter('seller_id', sellerId)
        .withQueryStringParameter('listing_status', 'REJECTED')
        .withQueryStringParameter('published', 'false')
        .withQueryStringParameter('page', '1')
        .withQueryStringParameter('per_page', '20')
        .withQueryStringParameter(not('brand_id'), not(brandId))
    mockServerClient.when(getRequest, once())
        .respond(response()
            .withStatusCode(200)
            .withHeaders(CONTENT_TYPE_HEADER)
            .withBody(jsonResponse))
```

Then in the request, the `brand_id` parameter is not provided at all. Again, this works fine in `5.10.0` but breaks in `5.11.2`. Also, note that all other tests pass, so the setup is correct.

**Expected behaviour**
Expect the test to pass with `not` as it did in previous verisions.

**MockServer Log**
Log output, as INFO level (or lower)

**Comment by joaonatalio** [comment]
Getting the same behaviour as you.

In our case we have a generic param parsing where null valued parameters would be interpreted as `Parameter.param(NottableString.not(paramName))` which worked well in `5.10.x`.

Given the refactoring changes of `5.11.x`, the method `Parameter.param(NottableString.not(it.key))` is no longer supported. Looking at how `5.10.x` was interpreting this request scenario internally, it looks something like this in a debugger:
```
...
"httpRequest" : {
    "method" : "GET",
    "path" : "/customer/v1/users",
    "queryStringParameters" : {
      "email" : [ "james@email.com" ], -> an expected param name and value
      "!firstName" : [ ".*" ] -> parsed as a nottable string
    }
  }
```

Even when we tried to force this "any regex" value in the nottablestring in `5.11.x` it still doesn't match parameters correctly when performing the request, something got broken.

**Comment by jamesdbloom** [comment]
I can't reproduce any errors with the notable string.  The basic rule is that the incoming request query string parameters must be a sub-map of the request matcher.

However this issue doesn't provide any details of matches that did not work.  Please provide example that you feel should be matched but are not currently matched.

See the following example demonstrating how not works:

```java
ClientAndServer mockServer = startClientAndServer(
    configuration()
        .logLevel("INFO")
        .detailedMatchFailures(true),
    1080
);
mockServer
    .when(
        request("/path")
            .withMethod("GET")
            .withQueryStringParameter(not("bar"), not("abc"))
            .withQueryStringParameter(not("foo"), string(".*")),
        unlimited()
    )
    .respond(
        response()
            .withStatusCode(200)
            .withBody("some_body")
    );

/*
# matches:
curl "http://localhost:1080/path?barX=abcX&fooX=random_value"
curl "http://localhost:1080/path?barX=abc&fooX=random_value"
curl "http://localhost:1080/path?barX=abcX&fooX=abc"
# does not match:
curl "http://localhost:1080/path?barX=abcX&foo=random_value"
curl "http://localhost:1080/path?bar=abc&fooX=random_value"
curl "http://localhost:1080/path?bar=abcX&foo=random_value"
curl "http://localhost:1080/path?bar=abcX&foox=random_value"
 */
```
