### ISSUE TITLE
MockServerEventLog calling wrong Disruptor constructor

### ISSUE THREAD

**Issue by pepegps** [mock-server/mockserver#931]
I am trying to execute some tests with **mockserver-netty 5.11.2** but I am receiving the following:

```
java.lang.NoSuchMethodError: com.lmax.disruptor.dsl.Disruptor.<init>(Lcom/lmax/disruptor/EventFactory;ILjava/util/concurrent/ThreadFactory;)V
```

The error is shown in runtime when instantiating ClientServer such as:

```
ClientAndServer mockServer = ClientAndServer.startClientAndServer(8080);
```

The issue is happening in maven project, which file includes:

```
<dependency>
  <groupId>org.mock-server</groupId>
  <artifactId>mockserver-netty</artifactId>
  <version>5.11.2</version>
</dependency>
```

I don't know how to check the version of  `com.lmax.Disruptor` used in mockserver-core dependency of the above mentioned lib having only the .jar (without the source). So I came here and notice the pom.xml of mockserver-core hasn't the version also. I expect the version should be transparent and supportable when importing dependency.

So I changed the ` pom.xml` to expicit the Disruptor version. It finally works.

```
<dependency>
  <groupId>org.mock-server</groupId>
  <artifactId>mockserver-netty</artifactId>
  <version>5.11.2</version>
  <scope>test</scope>
  <exclusions>
    <exclusion>
      <groupId>com.lmax</groupId>
      <artifactId>disruptor</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>com.lmax</groupId>
  <artifactId>disruptor</artifactId>
  <version>3.4.2</version>
</dependency>
```

Can someone help me to understand this behaviour?

**Comment by jamesdbloom** [comment]
The version comes from the parent pom and is 3.4.4
