### ISSUE TITLE
mockserver dependency conflict

### ISSUE THREAD

**Issue by LarsKrogJensen** [mock-server/mockserver#938]
**Describe the issue**
When using mockserver-netty and mockserver-client-java in a new maven project there are several conflicting dependencies that causes maven enforcer to fail the build.

Expectation is that mock-server mitigate version conflicts, via dependency management.

**What you are trying to do**
Use the lovely mock-server without conflicts

**MockServer version**
5.11.2

**To Reproduce**
Include maven build plugin:
`<plugin>
     <artifactId>maven-enforcer-plugin</artifactId>
          <version>3.0.0-M2</version>
                <executions>
                    <execution>
                        <id>enforce</id>
                        <configuration>
                            <rules>
                                <dependencyConvergence/>
                            </rules>
                        </configuration>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`
             

1. How you are running MockServer (i.e maven plugin, docker, etc)
   java code

**Expected behaviour**
Clean dependencies

**Maven enforced Output**
Dependency convergence error for com.google.code.findbugs:jsr305:2.0.1 paths to dependency are:
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-com.github.java-json-tools:json-schema-validator:2.2.14
        +-com.github.java-json-tools:jackson-coreutils-equivalence:1.0
          +-com.github.java-json-tools:jackson-coreutils:2.0
            +-com.github.java-json-tools:msg-simple:1.2
              +-com.github.java-json-tools:btf:1.3
                +-com.google.code.findbugs:jsr305:2.0.1
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-com.github.java-json-tools:json-schema-validator:2.2.14
        +-com.github.java-json-tools:jackson-coreutils-equivalence:1.0
          +-com.github.java-json-tools:jackson-coreutils:2.0
            +-com.github.java-json-tools:msg-simple:1.2
              +-com.google.code.findbugs:jsr305:2.0.1
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-com.github.java-json-tools:json-schema-validator:2.2.14
        +-com.github.java-json-tools:jackson-coreutils-equivalence:1.0
          +-com.github.java-json-tools:jackson-coreutils:2.0
            +-com.google.code.findbugs:jsr305:3.0.2
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-com.github.java-json-tools:json-schema-validator:2.2.14
        +-com.github.java-json-tools:json-schema-core:1.2.14
          +-com.github.java-json-tools:uri-template:0.10
            +-com.google.code.findbugs:jsr305:2.0.1
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-com.github.java-json-tools:json-schema-validator:2.2.14
        +-com.github.java-json-tools:json-schema-core:1.2.14
          +-com.google.code.findbugs:jsr305:3.0.2
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-com.github.java-json-tools:json-schema-validator:2.2.14
        +-com.google.code.findbugs:jsr305:3.0.2
[WARNING] 
Dependency convergence error for org.apache.commons:commons-lang3:3.2.1 paths to dependency are:
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-io.swagger.parser.v3:swagger-parser:2.0.23
        +-io.swagger.parser.v3:swagger-parser-v2-converter:2.0.23
          +-io.swagger:swagger-core:1.6.2
            +-org.apache.commons:commons-lang3:3.2.1
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-io.swagger.parser.v3:swagger-parser:2.0.23
        +-io.swagger.parser.v3:swagger-parser-v3:2.0.23
          +-io.swagger.core.v3:swagger-core:2.1.5
            +-org.apache.commons:commons-lang3:3.7
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-org.apache.commons:commons-lang3:3.11
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-client-java:5.11.2
    +-org.apache.commons:commons-lang3:3.11
[WARNING] 
Dependency convergence error for commons-codec:commons-codec:1.9 paths to dependency are:
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-io.swagger.parser.v3:swagger-parser:2.0.23
        +-io.swagger.parser.v3:swagger-parser-v2-converter:2.0.23
          +-io.swagger:swagger-compat-spec-parser:1.0.52
            +-org.apache.httpcomponents:httpclient:4.5.2
              +-commons-codec:commons-codec:1.9
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-commons-codec:commons-codec:1.15
[WARNING] 
Dependency convergence error for io.swagger:swagger-core:1.6.2 paths to dependency are:
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-io.swagger.parser.v3:swagger-parser:2.0.23
        +-io.swagger.parser.v3:swagger-parser-v2-converter:2.0.23
          +-io.swagger:swagger-core:1.6.2
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-io.swagger.parser.v3:swagger-parser:2.0.23
        +-io.swagger.parser.v3:swagger-parser-v2-converter:2.0.23
          +-io.swagger:swagger-parser:1.0.52
            +-io.swagger:swagger-core:1.6.1
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-io.swagger.parser.v3:swagger-parser:2.0.23
        +-io.swagger.parser.v3:swagger-parser-v2-converter:2.0.23
          +-io.swagger:swagger-compat-spec-parser:1.0.52
            +-io.swagger:swagger-core:1.6.1
[WARNING] 
Dependency convergence error for commons-io:commons-io:2.4 paths to dependency are:
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-io.swagger.parser.v3:swagger-parser:2.0.23
        +-io.swagger.parser.v3:swagger-parser-v2-converter:2.0.23
          +-io.swagger:swagger-parser:1.0.52
            +-commons-io:commons-io:2.4
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-io.swagger.parser.v3:swagger-parser:2.0.23
        +-io.swagger.parser.v3:swagger-parser-v3:2.0.23
          +-commons-io:commons-io:2.6
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-io.swagger.parser.v3:swagger-parser:2.0.23
        +-commons-io:commons-io:2.6
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-commons-io:commons-io:2.8.0
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-commons-io:commons-io:2.8.0
[WARNING] 
Dependency convergence error for com.github.java-json-tools:json-schema-validator:2.2.14 paths to dependency are:
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-com.github.java-json-tools:json-schema-validator:2.2.14
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-io.swagger.parser.v3:swagger-parser:2.0.23
        +-io.swagger.parser.v3:swagger-parser-v2-converter:2.0.23
          +-io.swagger:swagger-compat-spec-parser:1.0.52
            +-com.github.java-json-tools:json-schema-validator:2.2.8
[WARNING] 
Dependency convergence error for jakarta.xml.bind:jakarta.xml.bind-api:2.3.2 paths to dependency are:
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-io.swagger.parser.v3:swagger-parser:2.0.23
        +-io.swagger.parser.v3:swagger-parser-v3:2.0.23
          +-io.swagger.core.v3:swagger-core:2.1.5
            +-jakarta.xml.bind:jakarta.xml.bind-api:2.3.2
and
+-com.example.app:1.0.0-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.11.2
    +-org.mock-server:mockserver-core:5.11.2
      +-org.xmlunit:xmlunit-core:2.8.0
        +-jakarta.xml.bind:jakarta.xml.bind-api:2.3.3
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:

**Comment by MHajoha** [comment]
Because of this and https://github.com/java-json-tools/jackson-coreutils/issues/58, I need 70 lines of POM just to use MockServer. 😐
I'll look into fixing this if I find some time

**Comment by jamesdbloom** [comment]
I have now added maven enforcer to the project so this issue can be closed.
