### ISSUE TITLE
Set utf-8 as default encoding

### ISSUE THREAD

**Issue by Bessonov** [mock-server/mockserver#954]
**Describe the issue**
This is a follow up of https://github.com/mock-server/mockserver/issues/797 . It seems like https://github.com/mock-server/mockserver/commit/7408afbb03523736cf050a8d98d81589fcc4415b do following:

- `application/json; charset=utf-8` is set: works as expected, utf8 encoding is used
- no `Content-Type` header is set: works as expected, utf8 encoding is used
- `application/json` is set: utf8 isn't used. ISO-8859-1 is still used

From my point of view, the last one should use utf8.

**What you are trying to do**
Mock a request with utf8 encoding and `Content-Type: application/json` header. Mock Server stores it in wrong encoding.

**MockServer version**
5.11.2

**To Reproduce**
Steps to reproduce the issue:
- Send an utf8 encoded request with `Content-Type: application/json` header
- Get all recorded requests from mock server

**Expected behaviour**
utf8 should be assumed even without explicit `; charset=utf-8` part the Content-Type header

**MockServer Log**
-

**Comment by fr4ncidir** [comment]
I'm facing the same problem: the unittests on my project were continuously failing because of this.

**Comment by gusevalexey0** [comment]
:+1: Don't see any reason for not using utf-8 as default encoding with `application/json` in Content-Type header set.

**Comment by Anshelen** [comment]
This problem is especially painful when using mock-server with spring. The common restTemplate media type is APPLICATION_JSON, so you have to change it to deprecated APPLICATION_JSON_UTF8. But it causes new problems: header in Spring is 'application/json;charset=UTF-8" while in the mock server - 'application/json; charset=utf-8" so you are not able to validate it using request().withContentType(...) expectation.

**Comment by prakafox** [comment]
Still have this issue.

**Comment by jamesdbloom** [comment]
I'm pretty sure this is the correct standard for HTTP according to the exact specification but I can double check and potentially change it to the way you suggested as it's more practical.

**Comment by vrobertson** [comment]
Please take a look

https://datatracker.ietf.org/doc/html/rfc8259#section-11
> Note:  No "charset" parameter is defined for this registration. Adding one really has no effect on compliant recipients.

https://datatracker.ietf.org/doc/html/rfc8259#section-8.1
> JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8

https://www.rfc-editor.org/errata/eid5853 (Notes section)
