### ISSUE TITLE
new Date() only returns the date when the mock-server is up.

### ISSUE THREAD

**Issue by aaron-pacora** [mock-server/mockserver#967]
Hello;
This is my code, when I assign the new Date () to return the current date and time, it does not change the value, it remains static no matter how many times it consumes.

This value only changes when I restart the mock-server.

I am using docker;

```
mockServerClient(HOST, PORT).mockAnyResponse(
{
        'httpRequest': {
            'method': 'GET',
            'path': 'claims/get-claims/123456'
        },
        'httpResponse': {
            'statusCode': 200,
            'headers': [
                {"name": "Content-Type", "values": ["application/json; charset=utf-8"]},
                {"name": "Access-Control-Allow-Headers", "values": ["Content-Type"]}
            ],
            'body': JSON.stringify({
'registered_date': new Date()
})
        },
        'times': {
            'unlimited': true
        }
    }
));

```

**Comment by jamesdbloom** [comment]
That's because the date function is evaluated client side not inside MockServer so your sending a static value to MockServer.

I hope that makes sense?

Closing ticket as this is not an big in MockServer.
