### ISSUE TITLE
clear expectations by expectationId always clear all expectations even if i passed a non-existent expectationId

### ISSUE THREAD

**Issue by zhangwanli666** [mock-server/mockserver#969]
**Describe the issue**
Description of the issue

**What you are trying to do**
For the same request path, I created two expectations, and I used the expectationId obtained after to clear the corresponding expectation, and found that he would clear all the expectations of the corresponding path, instead of clearing the specified id corresponding to the expectation.

**MockServer version**
 5.11.2

**To Reproduce**
Steps to reproduce the issue:

1. i run mockserver  5.11.2 in docker in my local mac.
2. create multiple expectations, with the same request path but different response.
3. call the clear api which is cleared according to the expectationId

**Expected behaviour**
Specifying an expectationId to clear an expectation should only clear the corresponding expectation, not all matching expectations

**MockServer Log**
![image](https://user-images.githubusercontent.com/25833799/104992527-2e95ea80-5a5c-11eb-80bc-f08cedfee943.png)

**Comment by kingsleylong** [comment]
@zhangwanli666 I tried to reproduce your issue by following steps, but failed.
Could you please check your steps again? I see 4 REMOVED_EXPECTATION logs came before the "CLEARED" log, which looks like that you have made 4 clear requests.

Below is my steps:
```
curl -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
  "httpRequest" : {
    "path" : "/some/path"
  },
  "httpResponse" : {
    "body" : "some_response_body"
  }
}'

curl -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
  "httpRequest" : {
    "path" : "/some2/path"
  },
  "httpResponse" : {
    "body" : "some_response_body2"
  }
}'


curl -v -X PUT "http://localhost:1080/mockserver/clear" -d '{
    "path": "/some/path"
}'
```

Here is the log history. You can see that in the end there is still an active expectation there.
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/1475034/106570088-6464c400-6570-11eb-8ddb-f3de248f12ac.png">

**Comment by headlessgargoyle** [comment]
Also seeing this issue, in my team's mockserver setup we're just not going to support clear due to this, which strictly speaking should be fine since ID overwriting is supported cleanly. @kingsleylong, your example clears by body matching, not by ID. The equivalent would be

```
curl -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
  "id": "1",
  "httpRequest" : {
    "path" : "/some/path"
  },
  "httpResponse" : {
    "body" : "some_response_body"
  }
}'

curl -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
  "id": "2",
  "httpRequest" : {
    "path" : "/some2/path"
  },
  "httpResponse" : {
    "body" : "some_response_body2"
  }
}'


curl -v -X PUT "http://localhost:1080/mockserver/clear" -d '{
    "id": "1"
}'
```
![image](https://user-images.githubusercontent.com/5285561/139752945-2ae7b4ff-d1c9-44e3-8928-c6701412a915.png)

**Comment by jamesdbloom** [comment]
I can fix the clearing of expectations by id so that is relies only on the id and not matching by request.  I'm about to push a commit for that.  I have also improved clearing of logs and verification by id.
