### ISSUE TITLE
Certs expired

### ISSUE THREAD

**Issue by georgewilk01** [mock-server/mockserver#973]
Could you please release fresh certs?  The existing ones expired on Jan 1st, 2021.

Steps to reproduce the issue:
Downloaded and installed certs from: https://github.com/mock-server/mockserver/blob/master/mockserver-core/src/main/resources/org/mockserver/socket/CertificateAuthorityCertificate.pem

https://127.0.0.1:1080/mockserver/dashboard**Expected behaviour**

**Comment by jamesdbloom** [comment]
This is now fixed so closing this issues.
