### ISSUE TITLE
500 Internal Server Error generated from test using mockerserver-netty v5.7.0 but  works perfectly in v5.6.1

### ISSUE THREAD

**Issue by akoni2012** [mock-server/mockserver#978]
**Describe the issue**
I am having some problems with some component tests which use the mock server. With mockserver-netty v5.6.1, I am able to execute a simple test which uses TestRestTemplate to Post data to an endpoint and get back OK status. From v5.7.0, I am getting back a 500 Internal Server Error.

**What you are trying to do**
I am calling an endpoint using TestRestTemplate's exchange() method using the POST method. The return should be an object and 200 OK response.

**MockServer version**
The version you are using (i.e. 5.11.2)

**To Reproduce**
1. execute TestRestTemplate.exchange() on a POST
2. Assert response is OK i.e. assertEquals(200, responseEntity.getStatusCode().value());
3. response is 500 Internal Server Error
4. Occurs only from mockserver-netty v5.7.0 onwards.

1. How you are running MockServer (i.e maven plugin, docker, etc) 
- Maven Plugin
2. Code you used to create expectations
    @Test
    @Sql(scripts = "masses_id_matching.sql")
    public void testForSuccessResponse() {
        MassesRequest massesRequest = new MassesRequest();
        massesRequest.setPartyKey(PARTY_KEY);
        ResponseEntity<MassesResponse> responseEntity = updateMass(
            MassesResponse.class, massesRequest,
            "iugewiegwedgw",TRANSACTION_ID,"tenantKey");
        assertNotNull(responseEntity);
        assertNotNull(responseEntity.getStatusCode());
        assertEquals(200, responseEntity.getStatusCode().value());
        assertEquals(PARTY_KEY, responseEntity.getBody().getPartyKey());
    }
3. What error you saw
500
**Expected behaviour**
200

**MockServer Log**
Log output, as INFO level (or lower)

com.derin.deared.acctreset.MassesResetComponentTest > testForSuccessResponse FAILED
16:55:07.022 [DEBUG] [TestEventLogger]     org.opentest4j.AssertionFailedError: expected: <200> but was: <500>

**Comment by jamesdbloom** [comment]
MockSever 5.7.2 is a very old version so closing this issue please raise new issue with full logs if this is still a problem on version 5.11.1 onwards.
