### ISSUE TITLE
Please provide support for defining namespace prefix when using xpath matcher

### ISSUE THREAD

**Issue by cameronbraid** [mock-server/mockserver#980]
The following xml 

```

<?xml version = "1.0"?>
<SOAP-ENV:Envelope
   xmlns:SOAP-ENV = "http://www.w3.org/2001/12/soap-envelope"
   SOAP-ENV:encodingStyle = "http://www.w3.org/2001/12/soap-encoding">

   <SOAP-ENV:Body xmlns:m = "http://www.xyz.org/quotations">
      <m:GetQuotation>
         <m:QuotationsName>MiscroSoft</m:QuotationsName>
      </m:GetQuotation>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Doesnt match `new XPathBody("//GetQuotation")`

You have to resort to 

`new XPathBody("//*[local-name()='GetQuotation']")`

or more verbosely if you want to be specific about namespace prefixes (but doesn't work because xml is parsed without namespace awareness)

`new XPathBody("//*[local-name()='GetQuotation' && namespace-uri()='http://www.xyz.org/quotations
']")`

Would be nice to do 

`new XPathBody("//q:GetQuotation", Map.of("q","http://www.xyz.org/quotations"))`

**Comment by cameronbraid** [comment]
Something like https://github.com/mock-server/mockserver/pull/981 would be nice

**Comment by jamesdbloom** [comment]
@cameronbraid please rebase the PR then it can be merged (assuming the build passes)

**Comment by jamesdbloom** [comment]
@cameronbraid I've merged your PR as I could see that it passed the build locally without needing a rebase, nice job. 

Closing this issue as PR you wrote should have fixed it.

**Comment by cameronbraid** [comment]
I was a bit slow in getting to this.

Thanks heaps for merging it, and thanks for your very useful library.
