### ISSUE TITLE
Watch expecation initialization file does not work with ConfigMaps in kubernetes

### ISSUE THREAD

**Issue by Jeansen** [mock-server/mockserver#986]
**Describe the issue**
Mockserver can be told to monitor an expectation file. When mockserver is run with docker, this works as expected when run  with a volume mount to a directory. But as soon as e a file mount is used, the monitoring no longer works. The initial loading works as expected in any case. Only updates to file changes do not work and therefore do not trigger a reload.

The same holds true when mockserver is run from within a kubernetes cluster and the contents for expectations are provided by a ConfigMap. Changing the Config map contents does not trigger a reload.

**What you are trying to do**
Run mockserver with docker providing a file mount or inside a kubernetes cluster providing a ConfigMap.

**MockServer version**
 5.11.2

**To Reproduce**
Steps to reproduce the issue:

1. Create a working directory, e.g. /tmp/mock/config
2. cd into /tmp/mock
3. `echo "[]" > config/exepctations.json
4. `docker run --env MOCKSERVER_WATCH_INITIALIZATION_JSON=true  --env MOCKSERVER_INITIALIZATION_JSON_PATH=/config/expectations.json --rm -v $(pwd)/config/expectations.json:/config/expectations.json mockserver/mockserver`
5. echo "[a]" > config/expectations.json
6. Nothing happens

**Expected behaviour**
`echo "[a]" > config/expectations.json` should trigger a reload and by that print a stack trace because of invalid JSON. This works, when step 4 is modified to `docker run --env MOCKSERVER_WATCH_INITIALIZATION_JSON=true  --env MOCKSERVER_INITIALIZATION_JSON_PATH=/config --rm -v $(pwd)/config/expectations.json:/config mockserver/mockserver` where the volume mount points to a drectory. 

I've tried the same with a plain debain container, installed  inotify-tools and checked with `inotifywait -m <file>` that actually changes are made and have been synced with the container. So far, I can see no difference. When I have a volume mount to a directory or a specific file, there are always the same file events visible. So, I assume the problem lies somewhere in mockserver and how it monitors a file for changes.

**Comment by jamesdbloom** [comment]
The file watcher has recently been rewritten in the current SNAPSHOT so I'll check if this has fixed your issue or not.
