### ISSUE TITLE
Helm chart: Allow overriding the service account

### ISSUE THREAD

**Issue by reitzig** [mock-server/mockserver#990]
**Describe the feature request**

Add `app.serviceAccountName` to `values.yaml`.

**What you are trying to do**
Deploy MockServer on managed Kubernetes using the official Helm Chart, but the security policy doesn't allow

**The solution you'd like**
If you know, describe how you think the feature should be implemented / or should work

**Describe alternatives you've considered**
Workaround is to fly our own Helm chart or use something like kustomize.

**Comment by jamesdbloom** [comment]
The PR which has been merged fixes this issue so closing here.  This will be release in the next few weeks.
