### ISSUE TITLE
Helm chart: roll if the config map(s) have changed

### ISSUE THREAD

**Issue by reitzig** [mock-server/mockserver#992]
**Describe the feature request**
MockServer containers should roll when the content of the associated config map has changed.

**What you are trying to do**
I want MockServer to pick up changes to any initializers or responders I inject via JAR; ideally, whenever I change the config map, but at least when I run `helm upgrade`.

**The solution you'd like**
Since `--recreate-pods` has been deprecatedin Helm 3, the desired behavior should be part of the Helm chart (see [docs](https://v3.helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments)).

Ideally, we would _create_ the config map as part of the Helm chart, too, so we'd know when it changed (`checksum/config`).

**Describe alternatives you've considered**
`rollme` could be used to keep distance from the config map(s).

The best solution -- explicitly configuring the dependency on the ConfigMap _on_ the cluster seems to be out of reach for now: https://github.com/kubernetes/kubernetes/issues/22368

**Comment by reitzig** [comment]
Workaround: After some digging I found that we can already do this:

```yaml
podAnnotations:
  rollme: "{{ now }}"
```

Plus, `helm upgrade` doesn't seem to work with the default values, anyway:

```
Error: UPGRADE FAILED: cannot patch "mock-foo" with kind Service: Service "mock-foo" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

So I'm not sure what to make of this.

**Comment by RaymondKYLiu** [comment]
helm provide a method https://helm.sh/docs/howto/charts_tips_and_tricks/

Please see `Automatically Roll Deployments`

```
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
[...]
```

**Comment by reitzig** [comment]
@RaymondKYLiu Good call, thanks! Unfortunately, that doesn't help with this Helm Chart, as the ConfigMap isn't part of it.

**Comment by apa64** [comment]
> Plus, `helm upgrade` doesn't seem to work with the default values, anyway:
> 
> ```
> Error: UPGRADE FAILED: cannot patch "mock-foo" with kind Service: Service "mock-foo" is invalid: spec.clusterIP: Invalid value: "": field is immutable
> ```

I suggest to remove the `clusterIP` line from `service.yaml` and values too:
```yaml
  clusterIP: "{{ .Values.service.clusterIP }}"
```

**Comment by joshuasimon-taulia** [comment]
i think the simplest way to handle configmaps is to add a container to the deployment that runs https://github.com/kiwigrid/k8s-sidecar. for example, the grafana chart uses k8s-sidecar to dynamically mount dashboard and datasource configmaps
[pod template](https://github.com/grafana/helm-charts/blob/c302c6930b2feeff0eb2e81fd25e42c275869bd2/charts/grafana/templates/_pod.tpl#L163-L205)
[values.yaml](https://github.com/grafana/helm-charts/blob/c302c6930b2feeff0eb2e81fd25e42c275869bd2/charts/grafana/values.yaml#L601-L676)

**Comment by jamesdbloom** [comment]
I agree that makes sense, and is now fairly high on the backlog and so will likely be implemented in the next month or so.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/cO6wAaFR/184-helm-chart-roll-if-the-config-maps-have-changed

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.
